### ISSUE TITLE
request help: jwt-auth-cn.md

### ISSUE THREAD

**Issue by codlin** [apache/incubator-apisix#1008]
### Issue description
小白求教，[请问这个文档](https://github.com/apache/incubator-apisix/blob/master/doc/plugins/jwt-auth-cn.md)中说的username指的是终端用户吗？ 
如果一个网站有很多用户，一个个通过手动加不现实吧
谢谢
### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by membphis** [comment]
For gateways, consumers here are usually partners or channel sources. For example, a.com or b.com.

对于网关，这里的 consumer 通常是合作伙伴或渠道来源。 例如，a.com 或 b.com 这种使用域名做主体区分。

**Comment by codlin** [comment]
谢谢
