### ISSUE TITLE
request help: Plugin openid-connect 可有文档介绍？

### ISSUE THREAD

**Issue by jiezaizone** [apache/incubator-apisix#1016]
### Issue description

![image](https://user-images.githubusercontent.com/28976666/71763494-7a402980-2f17-11ea-87c6-b40d16eaa7e3.png)
这些参数属性不明白分别代表什么，该怎么填写。
想实现功能如下：
前置条件：自己有一个基于aouth2单点登录系统
登录地址http://XX/login.jsp
1、配置路由访问，没有授权跳转到登录系统登录页面进行登录操作
2、登录完成后跳转回原来页面继续访问
### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by moonming** [comment]
please refer the oauth doc: https://github.com/apache/incubator-apisix/blob/master/doc/plugins/oauth.md

**Comment by jiezaizone** [comment]
> please refer the oauth doc: https://github.com/apache/incubator-apisix/blob/master/doc/plugins/oauth.md

![image](https://user-images.githubusercontent.com/28976666/71799609-c1055f00-3090-11ea-80ae-b4da8d2c2ebf.png)
![image](https://user-images.githubusercontent.com/28976666/71799806-383af300-3091-11ea-9092-94ec3fbbbdd5.png)

I don't know what's wrong with my configuration. The url of the introspection_endpoint, redirect_uri, and discovery configuration can be accessed directly. However, after I configure it, I can access directly 500

**Comment by moonming** [comment]
Can you reproduce this problem with `curl`? Then I can reproduce this bug on my side.
Is there an error message in the `error.log`?
