### ISSUE TITLE
request help: apisix如何配置灰度访问？

### ISSUE THREAD

**Issue by jiezaizone** [apache/incubator-apisix#1017]
### Issue description
![image](https://user-images.githubusercontent.com/28976666/71763595-af00b080-2f18-11ea-9738-c4f5f820f006.png)
比如我本身的nginx有这个lua脚本，在apisix中该怎么配置？

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by membphis** [comment]
You can implement a new plugin and overwrite a method balance `.

Here is an example:

https://github.com/apache/incubator-apisix/blob/master/lua/apisix/plugins/example-plugin.lua#L66

**Comment by moonming** [comment]
Recommend using Apache APISIX's own configuration instead of external Lua code, here is an example for ab test: https://github.com/apache/incubator-apisix/blob/master/FAQ.md#how-to-support-ab-testing-via-apisix

**Comment by jiezaizone** [comment]
> Recommend using Apache APISIX's own configuration instead of external Lua code, here is an example for ab test: https://github.com/apache/incubator-apisix/blob/master/FAQ.md#how-to-support-ab-testing-via-apisix

![image](https://user-images.githubusercontent.com/28976666/71799351-f6f61380-308f-11ea-990b-d6c710fc6787.png)
I have read this document and understand that the same domain name is configured with two routes and then filtered according to vars?
Then I need to get my grayscale list in redis, how should I configure it here? Is there a demo?

**Comment by moonming** [comment]
> Then I need to get my grayscale list in redis, how should I configure it here?

you need to get your grayscale list from Redis by yourself, then call admin API to update APISIX.
