### ISSUE TITLE
request help: Service 是否可以支持多选？

### ISSUE THREAD

**Issue by jiezaizone** [apache/incubator-apisix#1018]
### Issue description
![image](https://user-images.githubusercontent.com/28976666/71763637-1d457300-2f19-11ea-9836-db7821708c54.png)
Service 
Service 是否可以支持多选？
比如说：我在server 配置了Plugin，配置了多个server，每个server都有对应一个Plugin，多选后，选中的的server中的Plugin生效。可通过配置的server 自由组合需要生效的Plugin，在不同的路由中复用
### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by membphis** [comment]
One route only can bind one service.

You can set different service which binds different plugin setting.

**Comment by moonming** [comment]
@jiezaizone 
Please use English in the public channel, thx

**Comment by jiezaizone** [comment]
> @jiezaizone
> 请在公共频道thx上使用英语

ok
