### ISSUE TITLE
feature: I want to introduce a fault-injection plugin

### ISSUE THREAD

**Issue by agile6v** [apache/incubator-apisix#1038]
Hi @moonming @membphis 

I want to introduce a plugin fault-injection like envoy's [fault-filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/fault_filter).

The purpose of introducing:
> The fault injection filter can be used to test the resiliency of microservices to different forms of failures. The filter can be used to inject delays and abort requests with user-specified error codes, thereby providing the ability to stage different failure scenarios such as service failures, service overloads, high network latency, network partitions, etc. 

In the first phase, I implement a very simple plugin which simply supports inject delay and abort requests with user-specified error codes. 

What do you think of?
Thanks.

**Comment by moonming** [comment]
LGTM.
@agile6v welcome PR

**Comment by membphis** [comment]
Looking forward to PR ^_^
