### ISSUE TITLE
bug: apisixe start fail

### ISSUE THREAD

**Issue by yangyitl** [apache/incubator-apisix#1058]
### Issue description
apisixe start fail

### Environment

* apisix version (cmd: `apisix version`):
* OS: Mac OS

### Minimal test code / Steps to reproduce the issue
1.sudo apisix start
2.
3.

### What's the actual result? (including assertion message & call stack if applicable)

lua: ./apisix:77: module 'tinyyaml' not found:
	no field package.preload['tinyyaml']
	no file '/usr/local/Cellar/apache-apisix/bin/lua/tinyyaml.lua'
	no file '/usr/local/Cellar/apache-apisix/bin/deps/share/lua/5.1/tinyyaml.lua'
	no file '/usr/local/share/lua/5.3/tinyyaml.lua'
	no file '/usr/local/share/lua/5.3/tinyyaml/init.lua'
	no file '/usr/local/lib/lua/5.3/tinyyaml.lua'
	no file '/usr/local/lib/lua/5.3/tinyyaml/init.lua'
	no file './tinyyaml.lua'
	no file './tinyyaml/init.lua'
	no file '/usr/local/Cellar/apache-apisix/bin/deps/lib64/lua/5.1/tinyyaml.so'
	no file '/usr/local/lib/lua/5.3/tinyyaml.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './tinyyaml.so'
stack traceback:
	[C]: in function 'require'
	./apisix:77: in main chunk
	[C]: in ?

**Comment by membphis** [comment]
How did you install the APISIX? please provide more install details.

**Comment by cyxinda** [comment]
When I run "/usr/bin/apisix start ",the error log is:
`/usr/local/apisix/deps/share/lua/5.1/tinyyaml.lua
/usr/local/openresty/luajit/bin/luajit: /usr/bin/apisix:78: module 'tinyyaml' not found:
	no field package.preload['tinyyaml']
	no file '/usr/local/openresty/nginx/conf/lua/tinyyaml.lua'
	no file '/usr/local/openresty/nginx/conf/deps/share/lua/5.1/tinyyaml.lua'
	no file '/usr/local/apisix/lua/tinyyaml.lua'
	no file './tinyyaml.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/tinyyaml.lua'
	no file '/usr/local/share/lua/5.1/tinyyaml.lua'
	no file '/usr/local/share/lua/5.1/tinyyaml/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/tinyyaml.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/tinyyaml/init.lua'
	no file '/usr/local/openresty/nginx/conf/deps/lib64/lua/5.1/tinyyaml.so'
	no file './tinyyaml.so'
	no file '/usr/local/lib/lua/5.1/tinyyaml.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/tinyyaml.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/bin/apisix:78: in main chunk
	[C]: at 0x00404bb0`

my OS is centos7.5
I changed the code `if script_path:sub(1, 17) == '/usr/**local**/apisix' or script_path:sub(1, 4) == '/bin' then` to `if script_path:sub(1, 17) == '/usr/bin/apisix' or script_path:sub(1, 4) == '/bin' then` in '/usr/bin/apisix',And it do work.

**Comment by membphis** [comment]
How did you install the APISIX?

**Comment by cyxinda** [comment]
I downloaded apisix of the version1.0 to my local host.Then I runned `yum -y install apisix-1.0-0.el7.noarch.rpm ` ，finished the install.
And that is all.

**Comment by membphis** [comment]
@moonming please take a look

**Comment by yangyitl** [comment]
> How did you install the APISIX? please provide more install details.

![image](https://user-images.githubusercontent.com/14830899/72591562-6941e000-393b-11ea-8734-3d4f8acb6490.png)
I installed from source  AND make init success

**Comment by membphis** [comment]
@yangyitl That is a bug for version 1.0 . We'll release a new version later.

And I advise you to fetch branch v1.0 which has fixed this bug.

`git clone -b v1.0 https://github.com/apache/incubator-apisix.git`

**Comment by membphis** [comment]
@cyxinda if you installed by yum, you can start or stop APISIX by command like this:

![image](https://user-images.githubusercontent.com/6814606/72594904-95615f00-3943-11ea-94ab-643380cd4539.png)

**Comment by cyxinda** [comment]
@membphis OK,thank you .
