### ISSUE TITLE
can apisix support acl 

### ISSUE THREAD

**Issue by zhangjimmy** [apache/incubator-apisix#1062]
Implements a basic ACL control that allows to whitelist and blacklist consumers to APIs using arbitrary group names. The ACL plugin could be more powerful once  has been implemented.
The documentation on the website has been updated, but it needs an ACL icon .
support jwt acl  first

**Comment by membphis** [comment]
we can use plugin `consumer-restriction` to support this.

https://github.com/apache/incubator-apisix/blob/master/doc/plugins/consumer-restriction.md

**Comment by fgreinacher** [comment]
New link: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/consumer-restriction.md
