### ISSUE TITLE
example-plugin.lua 404 

### ISSUE THREAD

**Issue by leehomewl** [apache/incubator-apisix#1064]
在  https://github.com/apache/incubator-apisix/blob/master/doc/architecture-design-cn.md中
  点击example-plugin的链接地址是404 ， 我检查了英文版的doc中没有问题，原因是中文版链接地址写错了，
请修改为：
https://github.com/apache/incubator-apisix/blob/master/lua/apisix/plugins/example-plugin.lua#L37

**Comment by membphis** [comment]
welcome PR to fix this
