### ISSUE TITLE
bug: dashboard can't add upstream 

### ISSUE THREAD

**Issue by wangsoft** [apache/incubator-apisix#1072]
### Issue description
add upstream error 

### Environment

* apisix version (cmd: `apisix version`):1.0
* OS: centOS 7

### Minimal test code / Steps to reproduce the issue
1. add upstream
2.
3.

### What's the actual result? (including assertion message & call stack if applicable)
no error

### What's the expected result?
add upstream ok
![企业微信截图_aba6c0cb-97c1-4294-8f3d-4daaed43d202](https://user-images.githubusercontent.com/4653300/72527851-a1e2aa80-38a4-11ea-9447-ea9e6aebc2d8.png)

**Comment by membphis** [comment]
you need to use the latest version of APISIX.
