### ISSUE TITLE
request help: allocation  upstream  and  service 

### ISSUE THREAD

**Issue by leehomewl** [apache/incubator-apisix#1073]
### Issue description
1 api管理中只有 route的， 我没有找到 api 管理中有可以直接 添加upstream 和 service的 。
   有办法可以直接通过api 只添加upstream 和service 配置的接口吗？（目前使用是可以用管理界面进行配置）

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by membphis** [comment]
Please take a look at this doc:

https://github.com/apache/incubator-apisix/blob/master/doc/admin-api-cn.md#route

![image](https://user-images.githubusercontent.com/6814606/72578991-b5c4f580-3912-11ea-98c8-0c8c9902a980.png)
