### ISSUE TITLE
request help: restart command reset configuration

### ISSUE THREAD

**Issue by juzhiyuan** [apache/incubator-apisix#1088]
### Issue description

`./bin/apisix restart` command will reset custom configuration as @Simon Chi said.

![image](https://user-images.githubusercontent.com/2106987/72787410-d373c100-3c6a-11ea-8b38-e56eba8669fc.png)

### Environment

* apisix version (cmd: `apisix version`): Unknown
* OS: Unknown

**Comment by moonming** [comment]
https://github.com/apache/incubator-apisix/blob/master/bin/apisix#L79
`nginx.conf` is read only. If you want to change config of nginx, please modify the `bin/apisix`.

**Comment by moonming** [comment]
`apisix restart` will regenerates the configuration file `nginx.conf`

**Comment by juzhiyuan** [comment]
Thanks for your reply :)
