### ISSUE TITLE
bug: the test command under Linux is incorrect with perl 5.26

### ISSUE THREAD

**Issue by spacewander** [apache/incubator-apisix#1091]
Type `make test` under Linux got `Can't locate t/APISIX.pm in @INC`.

The code in Makefile:
```
test:
ifeq ($(UNAME),Darwin)
	prove -I../test-nginx/lib -I./ -r -s t/
else
	prove -I../test-nginx/lib -r -s t/
endif
```

It seems that the difference the behavior is caused by the version of perl instead of the platform. The perl I used is `v5.26.1`.

Maybe we can always add `-I.` in the command regardless of the platform or the version of perl? Adding extra path isn't harmful.

**Comment by membphis** [comment]
welcome PR ^_^
