### ISSUE TITLE
bug: 【CORS Problem】Browser auto sends OPTIONS request, cannot match header, CURL request is fine

### ISSUE THREAD

**Issue by renyineng** [apache/incubator-apisix#1100]
### Issue description
我写了一个CORS插件，但是测试发现当路定义 header时，浏览器发起的OPTIONS预检请求 无法匹配到路由，直接返回了404，没有走到插件的header阶段，因为浏览器发起的OPTIONS请求没有携带请求数据，所以路由无法匹配成功

CURL 是没问题的，因为CURL是真正的发送的OPTIONS请求，会携带请求数据

### Environment
* apisix version  v1.0
* OS: centos7

[CORS plugins PR](https://github.com/apache/incubator-apisix/pull/1096/commits/231edce8451f2274c69034002dfab113c7cea65c)

### Minimal test code / Steps to reproduce the issue
1. 
1. Add route
```
curl http://127.0.0.1:80/apisix/admin/routes/1 -X PUT -d '
{
    "uri": "/shop/auth/login",
    "methods": ["OPTIONS","POST"],
    "vars": [
        ["http_k_project", "shop"]
    ],
    "service_id": "1"
}
```
2. Use vue axios to send post requests, because it involves cross-domain, so first send OPTIONS request, then directly 404

**Comment by membphis** [comment]
I made a test right now, it works fine. please take a look:

```shell
$ curl -i http://127.0.0.1:9080/apisix/admin/routes/1 -X PUT -d '
{
    "uri": "/shop/auth/login",
    "methods": ["OPTIONS","POST"],
    "vars": [
        ["http_k_project", "shop"]
    ],
    "plugins": {
        "redirect": {
            "uri": "/test/default.html",
            "ret_code": 301
        }
    }
}'
HTTP/1.1 200 OK
Date: Sat, 01 Feb 2020 13:02:42 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
... ...

# expect: hit
$ curl -I -X OPTIONS http://127.0.0.1:9080/shop/auth/login -H "K-Project: shop"
HTTP/1.1 301 Moved Permanently
Date: Sat, 01 Feb 2020 13:03:33 GMT
Content-Type: text/html
Content-Length: 166
Connection: keep-alive
Location: /test/default.html
Server: APISIX web server
... ...


# expect: not hit
$ curl -I -X OPTIONS http://127.0.0.1:9080/shop/auth/login -H "K-Project: shop1"
HTTP/1.1 404 Not Found
Date: Sat, 01 Feb 2020 13:03:51 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
Server: APISIX web server
```

**Comment by renyineng** [comment]
The OPTIONS that the browser sends automatically across domains does not pass the header, so it does n’t work in the browser, CURL is OK

**Comment by renyineng** [comment]
The options request automatically sent by the browser does not carry parameters, so it does not match.
https://medium.com/@hjyker/%E9%A2%84%E6%A3%80%E8%AF%B7%E6%B1%82-options-dff67adfeb66

**Comment by chenqing24** [comment]
Here is my solution for your reference：
```lua
function _M.rewrite(conf, ctx)
    -- 在开头先判断，如果是游览器为了跨域而发的OPTIONS，直接返回OK
    if 'OPTIONS' == action then
        return 200
    end

……
end
```

**Comment by membphis** [comment]
https://github.com/apache/incubator-apisix/pull/1327/files#diff-5caafc33851762ad95581b482d00332aR137

New PR has been submitted, we can close this issue now
