### ISSUE TITLE
request help: is the worker_rlimit_core too small?

### ISSUE THREAD

**Issue by spacewander** [apache/incubator-apisix#1101]
https://github.com/apache/incubator-apisix/blob/master/bin/apisix#L98
Currently we configure the `worker_rlimit_core` to 500MiB, which may be big enough for normal situation, but might truncate the core file in some cases. The size of the core file is equal to the memory used by LuaJIT + Nginx + shared memory among workers, which could be larger than 500MiB.

IMHO, it'd be better to limit the core size to 4GiB under 32 bits platform, and 16GiB elsewhere.

**Comment by membphis** [comment]
PR welcome, good catch
