### ISSUE TITLE
Is there a dashboard of grafana with the monitoring data of Prometheus

### ISSUE THREAD

**Issue by jungeFight** [apache/incubator-apisix#1103]
### Is there a dashboard of grafana with the monitoring data of Prometheus, as shown in the following figure, which I see in this link

[https://github.com/apache/incubator-apisix/blob/master/doc/plugins/prometheus-cn.md](url)

[https://github.com/apache/incubator-apisix/raw/master/doc/images/plugin/grafana_1.png](url)

**Comment by moonming** [comment]
@membphis can you share the script of grafana?

**Comment by membphis** [comment]
I will put it to `grafana` official website later.

**Comment by moonming** [comment]
@jungeFight added the doc for grafana, please check https://github.com/apache/incubator-apisix/commit/187d65764c9fb2c0895e30f328c2fe0e6a4f4479
