### ISSUE TITLE
issue: 无法正常路由分发upd

### ISSUE THREAD

**Issue by SpectorQian** [apache/incubator-apisix#1104]
### Issue description
config.yaml的配置
![image](https://user-images.githubusercontent.com/733560/73621435-09547480-4671-11ea-809b-1262da043d0f.png)
**通过apisix对外暴露9200进行路由转发，但是路由不成功**

### route配置

9201和9202是我本地开启的upd服务
curl http://127.0.0.1:9080/apisix/admin/stream_routes/2 -X PUT -d '
{
    "remote_addr": "127.0.0.1",
    "server_port": 9200,
    "upstream": {
        "nodes": {
            "127.0.0.1:9201": 1,
            "127.0.0.1:9202": 1
        },
        "type": "roundrobin"
    }
}'
![image](https://user-images.githubusercontent.com/733560/73621727-17ef5b80-4672-11ea-9504-cc73b9d2407f.png)

端口暴露：
![image](https://user-images.githubusercontent.com/733560/73621709-0ad26c80-4672-11ea-9b6b-14e088609d67.png)

**Comment by membphis** [comment]
it maybe a bug: https://github.com/apache/incubator-apisix/blob/master/lua/apisix/stream/router/ip_port.lua#L43

* route.value.server_port: number 
* vars.server_port: string

you can print more log to confirm this. PR welcome
