### ISSUE TITLE
bug: there is a typo in the test section of the jwt-auth plugin doc.

### ISSUE THREAD

**Issue by wtt20** [apache/incubator-apisix#1107]
### Issue description
https://github.com/apache/incubator-apisix/blob/master/doc/plugins/jwt-auth.md#test-plugin

“curl http://127.0.0.2...  ” should be “curl http://127.0.0.1... ”，this typo occurred on both English doc and Chinese doc. 

### Environment

* apisix version (cmd: `apisix version`): latest
* OS: 

### What's the actual result? (including assertion message & call stack if applicable)
Misleading readers.

### What's the expected result?
Fix this typo.

**Comment by membphis** [comment]
PR welcome ^_^
