### ISSUE TITLE
can not open 9100 port when enable  mqtt-proxy plugin

### ISSUE THREAD

**Issue by JohannT9527** [apache/incubator-apisix#1122]
after enable stream_proxy，the 9100 port was not open
![image](https://user-images.githubusercontent.com/61002378/74411730-f3b42b80-4e76-11ea-94cd-d4023d396d3a.png)
what should I do?

**Comment by membphis** [comment]
We need to restart the apisix server after modifying `conf/config.yaml` to regenerate a new nginx conf.

**Comment by JohannT9527** [comment]
我是使用docker安装的APISIX，修改了容器内的conf/config.yaml，然后尝试过直接重启容器，和容器内调用apisix的init方法和reload方法，结果仍然没能打开容器的9100端口。

**Comment by JohannT9527** [comment]
> We need to restart the apisix server after modifying `conf/config.yaml` to regenerate a new nginx conf.

我是使用docker安装的APISIX，修改了容器内的conf/config.yaml，然后尝试过直接重启容器，和容器内调用apisix的init方法和reload方法，结果仍然没能打开容器的9100端口。

**Comment by membphis** [comment]
@moonming please take a look at this issue

**Comment by JohannT9527** [comment]
> @moonming please take a look at this issue

我试过修改9080端口，在重启容器后修改是生效的，说明conf/config.yaml是可以正常加载的，但是stream_proxy下的配置好像一直无法生效。

**Comment by membphis** [comment]
I made a try right now, it works fine with master branch.

please confirm you exported the  port when you are using docker.

**Comment by membphis** [comment]
If you still have a problem, please provide more information.

Your apisix version, `config.yaml` file and the operation steps.

**Comment by JohannT9527** [comment]
> If you still have a problem, please provide more information.
> 
> Your apisix version, `config.yaml` file and the operation steps.

 apisix version：0.8
![image](https://user-images.githubusercontent.com/61002378/74501364-e0f83000-4f24-11ea-8eda-e44f16778b8f.png)


config.yaml如图：
![image](https://user-images.githubusercontent.com/61002378/74499781-cbccd280-4f1f-11ea-86a7-70f03d50c513.png)
![image](https://user-images.githubusercontent.com/61002378/74499817-e56e1a00-4f1f-11ea-8fed-ea52b5cb3050.png)
![image](https://user-images.githubusercontent.com/61002378/74499879-15b5b880-4f20-11ea-9c1c-1a8775b1d4b1.png)
![image](https://user-images.githubusercontent.com/61002378/74499909-29f9b580-4f20-11ea-82f7-1481abc69e69.png)

操作步骤：
1.先给apisix容器加了9111:9100的端口映射；
![image](https://user-images.githubusercontent.com/61002378/74500263-56620180-4f21-11ea-8008-a516c9e0b6fe.png)

2.进入容器，修改‘conf/config.yaml’文件，去掉了stream_proxy配置的#备注；

3.restart容器，然后测试端口
![image](https://user-images.githubusercontent.com/61002378/74500790-ff5d2c00-4f22-11ea-8b68-6955e521a4cf.png)
![image](https://user-images.githubusercontent.com/61002378/74501159-36800d00-4f24-11ea-9aa6-94c230e303e7.png)
![image](https://user-images.githubusercontent.com/61002378/74501189-4861b000-4f24-11ea-94e1-894c8b98b981.png)
![image](https://user-images.githubusercontent.com/61002378/74501226-66c7ab80-4f24-11ea-946b-5466841b34a9.png)
容器外部

![image](https://user-images.githubusercontent.com/61002378/74501054-d9845700-4f23-11ea-904f-8c770aebf428.png)容器内部

我的操作有问题吗？

**Comment by itime** [comment]
`make init`

it's work for me

**Comment by membphis** [comment]
@JohannT9527 close this PR first. if you still have this problem, you can reopen it.
