### ISSUE TITLE
Feature: introduce proxy caching plugin

### ISSUE THREAD

**Issue by agile6v** [apache/incubator-apisix#1127]
Hi，

I want to introduce a proxy caching plugin, but there are several choices.

1. Based on Nginx's built-in proxy cache in ngx_http_proxy_module, it store data on disk.
2. Based on lua_shared_dict in ngx-lua-module, it store data on memory.
3. Based on external storage such as redis and other redis-like storage system.

Each option has its own scenario, but i think option 1 supports more functionality and less code needs to be implemented. In addition, I'd perfer to abstract these options into a plugin and then by parameters to distinguish.

What do you think of?

**Comment by membphis** [comment]
> * Based on Nginx's built-in proxy cache in ngx_http_proxy_module, it store data on disk.

The `ngx_http_proxy_module` depends on the Nginx configuration file. We need to modify the Nginx core to use it dynamically. This is not an easy task.

> * Based on lua_shared_dict in ngx-lua-module, it store data on memory.

This is the simplest,

**Comment by moonming** [comment]
I perfer the option 1, which is more stable and easier to learn.
and one more thing, @agile6v you can send a [DISCUSS] email to mailinglist such like architecture selection topic.
