### ISSUE TITLE
request help:  fail to proxy grpc request

### ISSUE THREAD

**Issue by Iflengmo** [apache/incubator-apisix#1144]
### Issue description
apisix代理grpc服务
准备了apisix给的grpc示例服务，设置好路由

```shell
curl http://127.0.0.1:9080/apisix/admin/routes/1 -X PUT -d '
{
    "methods": ["POST", "GET"],
    "uri": "/helloworld.Greeter/SayHello",
    "service_protocol": "grpc",
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:50051": 1
        }
    }
}'
```

自己openssl做了pem格式的cert和key，添加了证书，sni这个参数这里如何设置？
自定义设置了foo.com

grpcurl -insecure -import-path ./proto  -proto helloworld.proto  \
    -d '{"name":"apisix"}' 127.0.0.1:9443 helloworld.Greeter.SayHello

按照文档上说的来访问，结果是

ERROR:
  Code: Internal
  Message: transport: received the unexpected content-type "text/html"
将127.0.0.1改为了foo.com访问，结果依旧是这样的。
### Environment

* apisix version (cmd: `apisix version`):1.0
* OS:centos7.2

**Comment by membphis** [comment]
@nic-chen do you know the reason about this issue ?

**Comment by nic-chen** [comment]
抱歉，我这边没能够重现这个问题。

Travis每次都会跑这个基础用例，应该不至于有问题：https://github.com/apache/incubator-apisix/blob/master/t/grpc-proxy-test.sh

你可以把Apache APISIX的log贴上来，看看gRPC服务有没有输出什么内容。



Sorry, I can't reproduce this issue.

Travis runs this test case every time, and it should not be a problem: https: //github.com/apache/incubator-apisix/blob/master/t/grpc-proxy-test.sh

You can upload the Apache APISIX log and see if the gRPC server outputs anything.

**Comment by nic-chen** [comment]
duplicate issue with  #1209

close.
