### ISSUE TITLE
question: How it judge that the dependience is exist or not?

### ISSUE THREAD

**Issue by wanzhenhan** [apache/incubator-apisix#1162]
### Issue description
When I install apisix offline on the step "make deps", it report 
"luarocks install rockspec/apisix-master-0.rockspec --tree=deps --only-deps --local
Missing dependencies for apisix master-0:
   lua-resty-template 1.9 (not installed)
   lua-resty-etcd 0.8 (not installed)
   lua-resty-balancer 0.02rc5 (not installed)
   lua-resty-ngxvar 0.5 (not installed)
   lua-resty-jit-uuid 0.0.7 (not installed)
   lua-resty-healthcheck-iresty 2.0 (not installed)
   lua-resty-jwt 0.2.0 (not installed)
   lua-resty-cookie 0.1.0 (not installed)
   lua-resty-session 2.24 (not installed)
   opentracing-openresty 0.1 (not installed)
   lua-resty-radixtree 1.7 (not installed)
   lua-protobuf 0.3.1 (not installed)
   lua-resty-openidc 1.7.2-1 (not installed)
   luafilesystem 1.7.0-2 (not installed)
   lua-tinyyaml 0.1 (not installed)
   lua-resty-prometheus 1.0 (not installed)
   jsonschema 0.5 (not installed)
   lua-resty-ipmatcher 0.3 (not installed)
"
I am sure that all dependience is installed by "luarocks list" and the version is correct 
Then I  want to know how it judge that the dependience is exist or not.

### Environment

* apisix version (cmd: `apisix version`):
* OS: Centos 7

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by membphis** [comment]
> Then I want to know how it judge that the dependience is exist or not.

luarocks list --tree=deps --local

**Comment by membphis** [comment]
@wanzhenhan please use a meaningful title

**Comment by membphis** [comment]
old issue
