### ISSUE TITLE
change: disables logging of errors about not found files into error_log for admin api.

### ISSUE THREAD

**Issue by membphis** [apache/incubator-apisix#1168]
When the user opens an independent service port for the dashboard, the dashboard may access some non-existing files (such as ICO). These not found logs are meaningless.

We can disable these error logs by default.

we can add the directive here:
https://github.com/apache/incubator-apisix/blob/master/bin/apisix#L248

```
log_not_found off;
```

here is the directive about `log_not_found`:
http://nginx.org/en/docs/http/ngx_http_core_module.html#log_not_found

**Comment by dabue** [comment]
It's an interesting feature, I want to do this job.

**Comment by Akayeshmantha** [comment]
@membphis  is this task in progress ?

**Comment by membphis** [comment]
No progress at this time, if you are interested, welcome to contribute PR

**Comment by membphis** [comment]
@dabue Have you made any progress?

**Comment by dabue** [comment]
&nbsp;I pushed 1 commit ,&nbsp; check it please.
  ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"YuanSheng Wang"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年3月3日(星期二) 晚上9:30
 收件人:&nbsp;"apache/incubator-apisix"<incubator-apisix@noreply.github.com&gt;;
 抄送:&nbsp;"Guosheng Yang"<88786912@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
 主题:&nbsp;Re: [apache/incubator-apisix] change: disables logging of errors about not found files into error_log for admin api. (#1168)

 

 
@dabue Have you made any progress?
