### ISSUE TITLE
doc: add English doc `doc/profile-cn.md`

### ISSUE THREAD

**Issue by membphis** [apache/incubator-apisix#1170]
there is the Chinese doc, need an English doc.

https://github.com/apache/incubator-apisix/pull/1147/files#diff-7142d50dcd279d8e6d2ea2cb50f83a41

**Comment by Akayeshmantha** [comment]
@membphis  I would like to work on this task

**Comment by membphis** [comment]
@Akayeshmantha thanks you, waiting for your PR

**Comment by Akayeshmantha** [comment]
@membphis  added the PR.
