### ISSUE TITLE
bad code style

### ISSUE THREAD

**Issue by membphis** [apache/incubator-apisix#1180]
https://github.com/apache/incubator-apisix/pull/1167/files#diff-62edadffc237f13dc28a694080d293a8R543

we need a better style, here is an example:

```
local function system_dns_resolver()
    local file, err = io.open("/etc/resolv.conf")
    if err then
        return nil, err
    end

    local dns_addrs = {}
    ... ...

    file:close()
    return dns_addrs
end
```

**Comment by Akayeshmantha** [comment]
Hi, @membphis  I would like to work on this issue. Is it only the function that you pointed or the whole file we have to refactor?

**Comment by membphis** [comment]
> Hi, @membphis I would like to work on this issue. Is it only the function that you pointed or the whole file we have to refactor?

Fix this function first.

If you can find more other similar points, welcome to fix them together.

I have assigned this issue to you. ^_^

**Comment by Akayeshmantha** [comment]
@membphis  quick question am new to lua is there a starting guide for developers to set up dev environment. I wanted to test the modified function.
