### ISSUE TITLE
bug: failed to call `apisix init` after apisix was installed by luarocks

### ISSUE THREAD

**Issue by membphis** [apache/incubator-apisix#1184]
### Issue description

https://travis-ci.org/apache/incubator-apisix/jobs/657178537#L1420

### Environment

* apisix version (cmd: `apisix version`):  https://github.com/apache/incubator-apisix/commit/e1ac426443293c6140ddb257e482537edd43c36a
* OS: ubuntu

### Minimal test code / Steps to reproduce the issue
https://github.com/apache/incubator-apisix/blob/master/.travis/linux_apisix_luarocks_runner.sh

**Comment by Akayeshmantha** [comment]
isn't it obvious since luarocks not getting installed from the script?
https://github.com/apache/incubator-apisix/blob/master/.travis/linux_apisix_luarocks_runner.sh

**Comment by Akayeshmantha** [comment]
isn't this missing in the script @membphis ? 
`create_lua_deps() {
    sudo luarocks make --lua-dir=${OPENRESTY_PREFIX}/luajit rockspec/apisix-master-0.rockspec --tree=deps --only-deps --local
    echo "Create lua deps cache"
    sudo rm -rf build-cache/deps
    sudo cp -r deps build-cache/
    sudo cp rockspec/apisix-master-0.rockspec build-cache/
}`

**Comment by membphis** [comment]
This bug should be that the Lua search path does not include `apisix.core.profile`.
We need to add one.

**Comment by Akayeshmantha** [comment]
@membphis  I would like to work on this issue

**Comment by membphis** [comment]
> @membphis I would like to work on this issue

OK, I have assigned it to you.

**Comment by Akayeshmantha** [comment]
Hi @membphis I was looking through this issue.

And as I found lua_path is set on below locations in bin/apisix file.
1. https://github.com/apache/incubator-apisix/blob/429f0165c202035b18b4437a84c6edc9007fc440/bin/apisix#L113

2. https://github.com/apache/incubator-apisix/blob/429f0165c202035b18b4437a84c6edc9007fc440/bin/apisix#L173

but am not quite sure as I searched found out that lua search path should be set during the run time.

Any help here would be awesome.

**Comment by Akayeshmantha** [comment]
@membphis  @moonming  do we have to set the env variables in travis for this issue ?
