### ISSUE TITLE
request help: How to test the log_utils?

### ISSUE THREAD

**Issue by sshniro** [apache/incubator-apisix#1186]
The log utils class uses the `ngx` as a parameter when a route is invoked by a request. How can I write test cases for this scenario? How to mock the ngx variable?

![image](https://user-images.githubusercontent.com/13045528/75757502-c3073980-5d32-11ea-8eb0-4eb1ceb5d916.png)

**Comment by membphis** [comment]
You can take a look at this test case:

https://github.com/apache/incubator-apisix/blob/master/t/core/log.t#L31

If you want to add some mock function, you can do like this:

https://github.com/apache/incubator-apisix/blob/0ee3c4be0e4616dcf10e8c0f6a68a74795879fea/lua/apisix/plugins/prometheus.lua#L59

**Comment by sshniro** [comment]
Thanks, will try this out.

**Comment by membphis** [comment]
I think we can close this issue now
