### ISSUE TITLE
request help: How to implement thread sleep in Nginx Test

### ISSUE THREAD

**Issue by sshniro** [apache/incubator-apisix#1189]
### Issue description
I would like to extensively test the batch processor as the functionality is strongly coupled with timer functionalities. Is there an efficient way to write a sleep function inside the test cases instead of writing a while loop? I could not find any useful pointers in nginx test repo.

**Comment by membphis** [comment]
can you prove us a mini case? I can not sure I got your point completely.

**Comment by sshniro** [comment]
I would like to write a test case to test the inactive timeout. The following are the configurations.
- Inactive Timeout = 2 S
- Batch Max Size = 100

![image](https://user-images.githubusercontent.com/13045528/75857387-72f1ab00-5df6-11ea-9a34-93cfb62db54c.png)

I would like to push an entry to the buffer at 0s and wait till 2s and push another entry. In this manner, I can reach the line segment of the code block[extending buffer timer]. To achieve this I need to wait for 2s before pushing the next entry to the buffer in the test case.

I've tried this solution but unfortunately, it does not work as expected.
```lua
require "socket"

function sleep(sec)
    socket.select(nil, nil, sec)
end

sleep(2)
```

**Comment by moonming** [comment]
@sshniro you can try `ngx.sleep(2)`.

**Comment by sshniro** [comment]
Thanks!
