### ISSUE TITLE
improvement: print a warning message when running APISIX in `/root` directory

### ISSUE THREAD

**Issue by membphis** [apache/incubator-apisix#1196]
Improvement: Because Nginx's default worker process uses the nobody user, it does not have permission to read the / root directory.

So when a user tries to start apisix in the `/root` directory, an alert will be displayed: Running apisix under `/root` is only suitable for development environments, and it is dangerous to do so. It is recommended to run apisix in a directory other than `/root`.

**Comment by sshniro** [comment]
Hi, @membphis just to clarify this check should be done inside the `/bin/apisix file` rite? To check the directory's permission and print the statement?

**Comment by membphis** [comment]
Yes, you are absolutely right. We can check the APISIX working folder.

https://github.com/apache/incubator-apisix/blob/v1.1/bin/apisix#L45

**Comment by sshniro** [comment]
We can close this as it is resolved by #1236
