### ISSUE TITLE
bug: when I exec the step "make run ",the nginx is started but its log print error

### ISSUE THREAD

**Issue by wanzhenhan** [apache/incubator-apisix#1197]
### Issue description
nginx's error.log print:
2020/03/04 12:29:07 [error] 14661#0: *72 [lua] config_local.lua:34: read_file(): faild to read config file:/root/incubator-apisix-1.0/conf/config.yaml, error info:/root/incubator-apisix-1.0/conf/config.yaml: Permission denied, context: init_worker_by_lua*
2020/03/04 12:29:07 [error] 14661#0: *72 [lua] config_local.lua:34: read_file(): faild to read config file:/root/incubator-apisix-1.0/conf/config.yaml, error info:/root/incubator-apisix-1.0/conf/config.yaml: Permission denied, context: init_worker_by_lua*
2020/03/04 12:29:07 [error] 14661#0: init_worker_by_lua error: /usr/share/lua/5.1/apisix/lua/apisix/plugin.lua:97: attempt to index upvalue 'local_conf' (a nil value)
stack traceback:
        /usr/share/lua/5.1/apisix/lua/apisix/plugin.lua:97: in function 'load'
        /usr/share/lua/5.1/apisix/lua/apisix/plugin.lua:180: in function 'load'
        /usr/share/lua/5.1/apisix/lua/apisix/plugin.lua:370: in function 'init_worker'
        /usr/share/lua/5.1/apisix/lua/apisix.lua:80: in function 'http_init_worker'
        init_worker_by_lua:2: in main chunk

### Environment

* apisix version (cmd: `apisix version`):
* OS: apisix 1.0

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

### What's the expected result?
run

**Comment by membphis** [comment]
same problem with https://github.com/apache/incubator-apisix/issues/1196
