### ISSUE TITLE
request help: How to rewrite/modify response in APISIX

### ISSUE THREAD

**Issue by sshniro** [apache/incubator-apisix#1198]
### Issue description
I would like to remove some auth headers from the upstream response. Is this possible with APISIX?
Is the proxy rewrite plugin only limited for requests?

**Comment by membphis** [comment]
You can take a look at this plugin: https://github.com/apache/incubator-apisix/blob/master/doc/plugins/response-rewrite.md#name

We can make it more powerful if we need.

**Comment by sshniro** [comment]
Thanks, will try this.

**Comment by moonming** [comment]
@sshniro You can also send these questions to the dev mailing list:)
