### ISSUE TITLE
Missing global rules usage

### ISSUE THREAD

**Issue by ShiningRush** [apache/incubator-apisix#1200]
Our team need a global plugin to enable CORS of service, then i found `global_rules`, but i didnt see any docs about it.
I think i could append its  description to `doc/architecture-design.md`, and link `Global Rule` in homepage to it, do you agree?

**Comment by membphis** [comment]
You  are right, PR welcome.

**Comment by moonming** [comment]
@ShiningRush Apache APISIX not has the CROS plugin yet, welcome PR for CORS.

**Comment by ShiningRush** [comment]
> @ShiningRush Apache APISIX not has the CROS plugin yet, welcome PR for CORS.

ok, i will do it after i append test case for it.

**Comment by ShiningRush** [comment]
@moonming @membphis Why the global rules will not run header_filter and body filter? and there is no any notice or error raise when a plugin which using the one of them, it will cause user confused(such me, i have cost much time to debug why the cors plugin work well in unit tests but not in out project, because unit tests bind to plugin and the latter bind to global rule)

**Comment by membphis** [comment]
it is a bug of global rules, here is a related issue: https://github.com/apache/incubator-apisix/issues/1202

We are discussing how to fix this bug.
