### ISSUE TITLE
bug: prometheus and zipkin do not support global_rule

### ISSUE THREAD

**Issue by rhubard** [apache/incubator-apisix#1202]
### Issue description
The global_rule plugin is not executed during the log phase

### Environment

* apisix version (cmd: `apisix version`):
* OS:

### Minimal test code / Steps to reproduce the issue
1. global_rule add prometheus
2.requst "/apisix/prometheus/metrics"

### What's the actual result? (including assertion message & call stack if applicable)
only exist nginx_http_current_connections

### What's the expected result?
prometheus and zipkin work normally

**Comment by membphis** [comment]
We need to modify the Apache APISIX core to resolve this problem.

**Comment by spacewander** [comment]
If we run the log plugin in global rule, should we ensure the plugin can be run only one? Previously, the user might configure the same plugin both in the global rule and in the local rule.

**Comment by membphis** [comment]
> If we run the log plugin in global rule, should we ensure the plugin can be run only one? Previously, the user might configure the same plugin both in the global rule and in the local rule.

I think that global rules and normal rules run independently, and the implementation will be simpler.

For example global `limit-count` rule and normal `limit-count` rule, we need two limit objects to work at the same time.  

If you have different opinions, please leave a message to discuss.

In addition, not all plugins can be put into global rules (such as authentication plugins), we should add a scope field to the plugin.

**Comment by membphis** [comment]
Some plugins are not allowed to run multiple times, such as monitoring plugins.

A flag is required to indicate whether the plugin allows multiple runs.

**Comment by ShiningRush** [comment]
I also think global plugin and normal plugin should work together except user indicate the plugin can be execute once.

**Comment by spacewander** [comment]
@membphis @ShiningRush 
I will work on it in a few days.

**Comment by ShiningRush** [comment]
It seems just run log phase for global rules but did not run header_filter and body_filter phase, cors plugin will work on header_filter phase.Is there any risk for run global rule's header_filter phase?

**Comment by membphis** [comment]
@ShiningRush I have created a new issue: https://github.com/apache/incubator-apisix/issues/1338

PR welcome
