### ISSUE TITLE
request help:  grpc proxy is not running

### ISSUE THREAD

**Issue by wanzhenhan** [apache/incubator-apisix#1209]
### Issue description
APISiX can't proxy grpc
when grpc client transport first package like "PRI * HTTP/2.0", apisix print logs "client sent invalid request while reading client request line, client: 10.82.4.71, server: , request: "PRI * HTTP/2.0",and reply 400 bad request to client

### Environment
CENTOS 7
* apisix version (cmd: `apisix version`):
* OS:1.0

**Comment by nic-chen** [comment]
我们默认只支持9443端口代理 gRPC 。
使用9443端口或者其他ssl端口时，请确保客户端请求有带tsl相关参数。
这里是一个最简单的，跳过证书验证的 gRPC-go 示例：

We only support port 9443 proxy gRPC by default.
When using port 9443 or other ssl ports, please ensure that the client request has tsl parameters.
Here is the simplest gRPC-go example that skips certificate verification:

`
    var tlsConf tls.Config
    tlsConf.InsecureSkipVerify = true

    creds := credentials.NewTLS(&tlsConf)

    creds = &errSignalingCreds{
        TransportCredentials: creds,
    }

    conn, err := grpc.Dial(address, grpc.WithBlock(), grpc.WithTransportCredentials(creds))
`

**Comment by wanzhenhan** [comment]
apisix只支持 https端口，目前不支持 http端口，因为 其http的端口无法支持 HTTP2
但是：nginx早已支持HTTP2，我们只需要手动更改nginx配置，将监听的那个http端口加上 HTTP2的配置即可  (note:不要执行 make init)

**Comment by moonming** [comment]
> apisix只支持 https端口，目前不支持 http端口，因为 其http的端口无法支持 HTTP2
> 但是：nginx早已支持HTTP2，我们只需要手动更改nginx配置，将监听的那个http端口加上 HTTP2的配置即可 (note:不要执行 make init)

Apache APISIX enabled `http2` default: https://github.com/apache/incubator-apisix/blob/master/conf/config.yaml#L77
