### ISSUE TITLE
feature: Support echo plugin

### ISSUE THREAD

**Issue by agile6v** [apache/incubator-apisix#1225]
APISIX currently provides a simple example plugin, but it does not provide useful functionality. So we can provide a useful plugin to help users understand as fully as possible how to develop an APISIX plugin.

**Comment by Akayeshmantha** [comment]
Hi @agile6v @moonming  will be applying for GSoC 2020 this year. Would like to give it a try with apache APISIX. I did GSoC 2019 with openMRS. Is there a chat room which talks about the project idea.

**Comment by moonming** [comment]
@Akayeshmantha Cool, you can add your ideas to https://cwiki.apache.org/confluence/display/COMDEV/GSoC+2020+Ideas+list, and we can talk about in slack: https://the-asf.slack.com/
, and serach the `apisix` channel.

**Comment by agile6v** [comment]
This plugin could implement the corresponding functionality in the common phases such as `init`, `rewrite`, `access`, `balancer`, `header filer`, `body filter` and `log` . But the specific functionality are still being considered.

**Comment by Akayeshmantha** [comment]
Hi @membphis  @moonming  @agile6v I hope still this is a valid requirement.

So here we are thinking about extending the already existing example plugin if am right?.

**Comment by agile6v** [comment]
Hi @Akayeshmantha 

As far as i am concerned, this plugin is still necessary to help other people understand how to implement a plugin as fully as possible. 

Thanks.

**Comment by Akayeshmantha** [comment]
@agile6v so what is the path we are taking implmenting a new plugin or extending the existing plugin 🙂

**Comment by Akayeshmantha** [comment]
@membphis @moonming  would like to work on this

**Comment by agile6v** [comment]
> @agile6v so what is the path we are taking implmenting a new plugin or extending the existing plugin 🙂

Hi @Akayeshmantha Remember that you submitted a proposal at GSOC. How about we follow that plan? 

First we implement a simple echo function and then implement a function that modify the response body. For example, adding content before or after the response body.

Thanks.

**Comment by Akayeshmantha** [comment]
@agile6v  sure think that is a good way to start.

**Comment by membphis** [comment]
@agile6v 

Can you provide some use cases?
For example, what configuration options are there for this plugin, and the expected execution results?

**Comment by agile6v** [comment]
Hi @Akayeshmantha This [example](https://github.com/openresty/echo-nginx-module#echo_before_body) can be used as a reference. Not sure I've made it a clear. If you have any questions, welcome to discuss here. 

Thanks.

**Comment by Akayeshmantha** [comment]
Hi @agile6v  
So you mean we are going to install https://github.com/openresty/echo-nginx-module#installation echo nginx module and use them for the plugin ?

**Comment by agile6v** [comment]
> Hi @agile6v
> So you mean we are going to install https://github.com/openresty/echo-nginx-module#installation echo nginx module and use them for the plugin ?
> 
> Or are we going with nginx.logging()


@Akayeshmantha  We're going to implement an echo plugin, right? So we refer to its [features](https://github.com/openresty/echo-nginx-module#echo_before_body) to implement APISIX's echo plugin?

Thanks.

**Comment by moonming** [comment]
@agile6v you'd better show same specific examples

**Comment by Akayeshmantha** [comment]
Hi @agile6v so from what I get when it comes to the output_filter phase we should replicate what we have in https://github.com/openresty/echo-nginx-module/blob/master/src/ngx_http_echo_module.c#L412 ?

**Comment by agile6v** [comment]
Hi @Akayeshmantha 

We can refer to the implementation of the plugin [response-rewrite](https://github.com/apache/incubator-apisix/blob/master/apisix/plugins/response-rewrite.lua#L98).  It has the ability to override the response body.  In the echo plugin we implement the function like this:

```shell
function _M.body_filter(conf, ctx)
    conf.before_body + response.body + conf.after_body
end
```

FYI: https://github.com/openresty/lua-nginx-module#body_filter_by_lua

Hope I've described it clearly.

Thanks.

**Comment by Akayeshmantha** [comment]
@agile6v  I drafted a small sample can you look in the PR ?

**Comment by Akayeshmantha** [comment]
@agile6v  @membphis  @moonming  any idea about how it is now. Can we review it ?
