### ISSUE TITLE
optimization: use the correct parameters based on the version of luarocks

### ISSUE THREAD

**Issue by membphis** [apache/incubator-apisix#1227]
It may be wrong to determine the parameters based on the operating system type.

we need to delete the old logic:

https://github.com/apache/incubator-apisix/blob/master/Makefile#L50

**Comment by dabue** [comment]
I can do it.

**Comment by membphis** [comment]
> I can do it.

waiting your PR ^_^

**Comment by dabue** [comment]
I want to do this job.



88786912@qq.com
 
From: YuanSheng Wang
Date: 2020-03-09 21:45
To: apache/incubator-apisix
CC: Subscribed
Subject: [apache/incubator-apisix] optimization: use the correct parameters based on the version of luarocks (#1227)
It may be wrong to determine the parameters based on the operating system type.
we need to delete the old logic:
https://github.com/apache/incubator-apisix/blob/master/Makefile#L50
