### ISSUE TITLE
Getting Error unknown directive "lua_package_path" in /API_ASPIX/incubator-apisix/t/servroot/conf/nginx.conf

### ISSUE THREAD

**Issue by Akayeshmantha** [apache/incubator-apisix#1232]
when I run test cases  in ubuntu(18.04.2), there is an error message "nginx: [emerg] unknown directive "lua_package_path" in /home/API_ASPIX/incubator-apisix/t/servroot/conf/nginx.conf:28:" ?  @membphis  @moonming

**Comment by Akayeshmantha** [comment]
Lua module is also enabled it seems am not sure why this error pops up

```
 ayesh  ayesh-ThinkPad-T480s  ~  Documents  API_ASPIX  incubator-apisix  patch5  $  ls -la
total 236
drwxr-xr-x 22 ayesh  ayesh  4096 Mar 11 14:43 .
drwxr-xr-x 10 ayesh  ayesh  4096 Mar 11 14:44 ..
drwxr-xr-x  4 ayesh  ayesh  4096 Mar  5 14:47 benchmark
drwxr-xr-x  2 ayesh  ayesh  4096 Mar  7 18:13 bin
-rw-rw-r--  1 ayesh  ayesh    25 Mar 11 15:28 build.log
-rw-r--r--  1 ayesh  ayesh 15817 Mar  2 12:55 CHANGELOG_CN.md
-rw-r--r--  1 ayesh  ayesh 15967 Mar  2 12:55 CHANGELOG.md
drwx------  2 nobody ayesh  4096 Mar  2 16:15 client_body_temp
-rw-r--r--  1 ayesh  ayesh  6713 Mar  2 12:55 CODE_STYLE.md
drwxr-xr-x  3 ayesh  ayesh  4096 Mar 11 17:29 conf
-rw-rw-r--  1 ayesh  ayesh  6390 Mar  5 14:47 Contributing.md
drwx------  3 root   root   4096 Mar  2 17:15 default.etcd
drwxrwxr-x  4 ayesh  ayesh  4096 Mar  2 18:27 deps
-rw-r--r--  1 ayesh  ayesh   550 Mar  2 12:55 DISCLAIMER
drwxr-xr-x  4 ayesh  ayesh  4096 Mar  7 18:13 doc
-rw-rw-r--  1 ayesh  ayesh  4502 Mar  5 14:47 FAQ_CN.md
-rw-rw-r--  1 ayesh  ayesh  6743 Mar  5 14:47 FAQ.md
drwx------  2 nobody ayesh  4096 Mar  2 16:15 fastcgi_temp
drwxr-xr-x  8 ayesh  ayesh  4096 Mar 11 17:46 .git
-rw-r--r--  1 ayesh  ayesh    22 Mar  2 12:55 .gitattributes
drwxr-xr-x  3 ayesh  ayesh  4096 Mar  2 12:55 .github
-rw-r--r--  1 ayesh  ayesh   528 Mar  2 12:55 .gitignore
-rw-r--r--  1 ayesh  ayesh   112 Mar  2 12:55 .gitmodules
drwxrwxr-x  2 ayesh  ayesh  4096 Mar 11 17:45 .idea
-rw-r--r--  1 ayesh  ayesh 11357 Mar  2 12:55 LICENSE
drwxr-xr-x  2 ayesh  ayesh  4096 Mar 11 14:38 logs
drwxr-xr-x  3 ayesh  ayesh  4096 Mar  7 18:11 lua

```

**Comment by membphis** [comment]
the `test::nginx` use nginx by default.

You can run the test cases in this way.

https://github.com/apache/incubator-apisix/blob/master/doc/how-to-build.md#4-test

`TEST_NGINX_BINARY=/usr/local/bin/openresty prove -Itest-nginx/lib -r t`

BYW, you can set openresty as default nginx, I use this way now.

![image](https://user-images.githubusercontent.com/6814606/76523119-d2a91f80-64a2-11ea-9538-056b313c7949.png)

**Comment by Yiyiyimu** [comment]
Hi @membphis !After following the [documentation](https://github.com/apache/incubator-apisix/blob/master/doc/how-to-build.md#4-test) you mentioned, I still got the same error. Do you have some other suggestions?

Also, I think the path of nginx should be `TEST_NGINX_BINARY=/usr/local/openresty/bin/openresty prove -Itest-nginx/lib -r t`. According to `export PATH=/usr/local/openresty/nginx/sbin:$PATH` to set the path, the openresty folder seems not under `/usr/local/bin`. I'm not sure if it's the change in v1.2/1.3
