### ISSUE TITLE
change: upgrade `lua-resty-ipmatcher` to version v0.6

### ISSUE THREAD

**Issue by membphis** [apache/incubator-apisix#1234]
the `lua-resty-ipmatcher` has released new version v0.6 , Apache APISIX need  to update too.

We can modify it here:

https://github.com/apache/incubator-apisix/blob/master/rockspec/apisix-master-0.rockspec#L50

**Comment by membphis** [comment]
As a learning reference, you can refer to this PR.

https://github.com/apache/incubator-apisix/pull/1019

**Comment by Akayeshmantha** [comment]
Am on it 🙂
