### ISSUE TITLE
invalid doc path of

### ISSUE THREAD

**Issue by hiproz** [apache/incubator-apisix#1235]
### Issue description
the doc path " etcd Clustering Guide" of incubator-apisix/README_CN.md  is invalid 
### Environment
web browser
* apisix version (cmd: `apisix version`):
* OS:

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

### What's the actual result? (including assertion message & call stack if applicable)
not found 404

### What's the expected result?
should been visited

**Comment by moonming** [comment]
@hiproz thx, welcome PR

**Comment by membphis** [comment]
the correct address should be: https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/clustering.md
