### ISSUE TITLE
request help: How to white-list consumers for the Keyauth plugin

### ISSUE THREAD

**Issue by sshniro** [apache/incubator-apisix#1243]
### Issue description
Is there a way to limit the users who are permitted to use a route via the key auth plugin? Currently, it allows all consumers to access a route, if the key auth is enabled.

**Comment by soulsoul** [comment]
so you can use some other plugin  on your business .  not just one keyauth plugin.

**Comment by sshniro** [comment]
I did not understand the last statement, are you suggesting to use a custom plugin instead of the keyauth plugin?

**Comment by membphis** [comment]
The current mechanism does not support this limitation.

**Comment by sshniro** [comment]
Thanks, Is it okay to extend the plugin to restrict to specific consumers? It can enhance the security and flexibility of the key-auth plugin?

**Comment by membphis** [comment]
Can you provide an example of how to solve this problem?
If a Keyauth plugin is used by a non-whitelisted consumer, will the current request be rejected?

**Comment by soulsoul** [comment]
@sshniro  yes.  the key-auth plugin only support basic authentication,  for enhance the security , we can use some other plugin to provide auxiliary capacity  on business. we maybe not make individual plugin too fat . right ?

**Comment by sshniro** [comment]
Yes, Agree @soulsoul 
I think this can be a separate Access Control Plugin.

This is the scenario I have and I assume this can be a common scenario as well.

We are proxying device data through REST and MQTT and we provide a token to the device. The problem with the current implementation is, if the device has a valid token/key then it can publish data to any routes. We need a way to control it.

@membphis This is how the implementation will look like this:

```bash

curl http://127.0.0.1:9080/apisix/admin/consumers  -X PUT -d '
{
    "username": "device1",
    "plugins": {
        "key-auth": {
            "key": "keytodeviceone"
        }
    }
}'

curl http://127.0.0.1:9080/apisix/admin/routes/1 ' -X PUT -d '
{
    "uri": "/device1publishroute",
    "id": 1,
    "plugins": {
        "key-auth": {},
        "acl-plugin": ['device1', 'device2']
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "39.97.63.215:80": 1
        }
    }
}'
```
The ACL plugins should be executed after the keyauth plugin.

**Comment by membphis** [comment]
> @membphis This is how the implementation will look like this:

It looks good to me. @moonming What do you think?

**Comment by sshniro** [comment]
Hi @moonming , @membphis I found a similar request by another user as well! #1062  
But has a bigger scope of grouping consumers, and also extending it to jwt auth plugin as well.

I will be developing this plugin independently for our project's security requirements. Do let me know if this is a useful addition to APISIX as well. If so I can contribute the codebase to APISIX as well.

**Comment by membphis** [comment]
@sshniro Yes, it is a useful feature for APISIX. Welcome PR ^_^
