### ISSUE TITLE
bug: plugin basic-auth needs required field

### ISSUE THREAD

**Issue by juzhiyuan** [apache/incubator-apisix#1244]
### Issue description
Plugin `basic-auth` doesn't have `required` field currently.

### Environment

* apisix version (cmd: `apisix version`):
* OS:

### Minimal test code / Steps to reproduce the issue
None

### What's the actual result? (including assertion message & call stack if applicable)
No `required` field.

### What's the expected result?
It should have at least one required field such as username or password in my opinion.

**Comment by membphis** [comment]
For all of the authorization plugin:

When it was used with `consumer`, it is necessary to provide specific authentication information.

When it was used with `route / service`, we don't need any parameters, just enable or disable this plugin.

So I think the current way is right.

How about this `schema` definition? Is it better?

```lua
oneof = {
    -- no parameter
    required = {}, 
    -- two parameters
    required = {"username", "passwd"}
}
```
