### ISSUE TITLE
bug: Plugin udp-logger returns status code 500

### ISSUE THREAD

**Issue by juzhiyuan** [apache/incubator-apisix#1246]
### Issue description
Plugin `udp-logger` returns status code 500.

### Environment

* apisix version (cmd: `apisix version`): 1.1
* OS:

### Minimal test code / Steps to reproduce the issue
None

### What's the actual result? (including assertion message & call stack if applicable)
Plugin `udp-logger` returns status code 500 when accessing it by admin api.

### What's the expected result?
I'm not sure what happened.

**Comment by sshniro** [comment]
Hi @juzhiyuan can I know in which scenario does this occur ?

**Comment by juzhiyuan** [comment]
When accessing `http://HOST/admin/schema/plugins/key-auth`

**Comment by membphis** [comment]
I added a test case right now, it works fine. I think we have fixed this bug in master branch.

Anyway, we need a test case to cover this case.
