### ISSUE TITLE
APISIX occasionally returns 500 for httpbin.org

### ISSUE THREAD

**Issue by sshniro** [apache/incubator-apisix#1250]
### Issue description
For testing, I use [httpbin.org](https://httpbin.org/) as an upstream address to echo the parameters. But I'm starting to get 500 for consequent hits for the same address. And occasionally it returns 200 again, the behavior is unpredictable.

Does anyone know why is this happening? Is this something related to caching or timeouts?

I tested httpbin.org without proxying via APISIX with a 1-second loop and the response is always 200.

The following is the screenshot when I access `httpbin` via apisix with 1-second interval.

![image](https://user-images.githubusercontent.com/13045528/76594533-b389ac80-64f9-11ea-87d6-57b656a2259f.png)

The following is the screenshot when I access `httpbin` without any proxy with 1-second interval.

![image](https://user-images.githubusercontent.com/13045528/76594580-d3b96b80-64f9-11ea-8943-b385b196c684.png)

The following is my configuration.

```bash
curl "http://127.0.0.1:9080/apisix/admin/upstreams/50" -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "type": "roundrobin",
    "nodes": {
        "httpbin.org:443": 1
    }
}'
```

```bash
curl http://127.0.0.1:9080/apisix/admin/routes/5 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/samplePrefix/get",
    "plugins": {
        "proxy-rewrite": {
          "scheme": "https",
          "regex_uri": ["^/samplePrefix/get(.*)", "/get$1"]
        }
    },
    "upstream_id": 50
}'
```

```bash
curl -i -X GET http://127.0.0.1:9080/samplePrefix/get?param1=foo&param2=bar
```

```bash
curl -i -X GET https://httpbing.org
```

**Comment by membphis** [comment]
@sshniro please provide your error log when you got 500 responses code, I need to confirm it.

I guess you are using an older version of Apache APISIX. I have fixed this error for a few days.

You can make a try with the latest version of APISIX.

**Comment by sshniro** [comment]
@membphis , I'm using the master branch, There are no helpful messages printed when I get 500, This is what I get during startup.

![image](https://user-images.githubusercontent.com/13045528/76677651-21ed6e00-65d1-11ea-9445-e680402c4ff7.png)

![image](https://user-images.githubusercontent.com/13045528/76677654-2b76d600-65d1-11ea-824f-d17764a4a3e6.png)

**Comment by sshniro** [comment]
@membphis  This is reproducible with the latest master branch, What does RLLIMIT mean in this context?

**Comment by membphis** [comment]
> I'm using the master branch, There are no helpful messages printed when I get 500, This is what I get during startup.

If we can't find any associated error logs from the local file, then this 500 error response is from httpbin and it was not generated by APISIX.

Your Nginx worker does not have permissions, which limits the number of open files.

**Comment by membphis** [comment]
I tried your example, I got sucess

```shell
$ curl "http://127.0.0.1:9080/apisix/admin/upstreams/50" -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "type": "roundrobin",
    "nodes": {
        "httpbin.org:443": 1
    }
}'
{"node":{"value":{"nodes":{"httpbin.org:443":1},"hash_on":"vars","type":"roundrobin"},"createdIndex":2103,"key":"\/apisix\/upstreams\/50","modifiedIndex":2103},"action":"set"}

$ curl http://127.0.0.1:9080/apisix/admin/routes/5 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/samplePrefix/get",
    "plugins": {
        "proxy-rewrite": {
          "scheme": "https",
          "regex_uri": ["^/samplePrefix/get(.*)", "/get$1"]
        }
    },
    "upstream_id": 50
}'
{"node":{"value":{"upstream_id":50,"plugins":{"proxy-rewrite":{"regex_uri":["^\/samplePrefix\/get(.*)","\/get$1"],"scheme":"https"}},"uri":"\/samplePrefix\/get","priority":0},"createdIndex":2104,"key":"\/apisix\/routes\/5","modifiedIndex":2104},"action":"set"}

$ curl -i -X GET http://127.0.0.1:9080/samplePrefix/get\?param1\=foo\&param2\=bar
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 367
Connection: keep-alive
Date: Sat, 14 Mar 2020 13:42:50 GMT
Server: APISIX web server
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

{
  "args": {
    "param1": "foo",
    "param2": "bar"
  },
  "headers": {
    "Accept": "*/*",
    "Host": "127.0.0.1",
    "User-Agent": "curl/7.66.0",
    "X-Amzn-Trace-Id": "Root=1-5e6cdf59-6808716820e92f54dfa60584",
    "X-Forwarded-Host": "127.0.0.1"
  },
  "origin": "127.0.0.1, 223.73.235.21",
  "url": "https://127.0.0.1/get?param1=foo&param2=bar"
}
```

**Comment by sshniro** [comment]
Thanks, Yes it was working but gave 500 intermittently, I will try with another service and get back to you.

BTW, a suggestion why don't we host an echo service for APISIX itself?

I see some of the docs use this ip `http://39.97.63.215/`, I assume this IP belongs to the APISIX team, in that case, we can add an endpoint to echo the calls (+domain name), thus we can use it in all our docs.

**Comment by membphis** [comment]
> BTW, a suggestion why don't we host an echo service for APISIX itself?

https://docs.google.com/document/d/1BNMWjXB5_yFsuP8WcJFH-a2mF9PfaH8Md-wUXGFG4MY/edit#heading=h.ovyshqokq27

@Akayeshmantha is working on this, you can talk to him directly.

**Comment by membphis** [comment]
> I see some of the docs use this IP `http://39.97.63.215/`

we should remove it or use another address.

**Comment by sshniro** [comment]
Sure, will update!
