### ISSUE TITLE
feature: support request mirror

### ISSUE THREAD

**Issue by agile6v** [apache/incubator-apisix#1262]
Hi 

Is it necessary to provide a request mirror plugin?

The nginx configuration looks like:

```nginx

set $var_mirror_disable 1;

location / {
     mirror /mirror_location;
     proxy_pass  $upstream_scheme://apisix_backend$upstream_uri;
}

location /mirror_location {
    if ($var_mirror_disable) {
        return 200;
    }

    proxy_pass $mirror_address;
}
```

The variable `var_mirror_disable` and `mirror_address` can be configured in the mirror plugin.

The admin api looks like this:
```
{
    "plugins": {
       "mirror": {
           "address": "127.0.0.1:8090"
       }
    },
    "upstream": {
       "nodes": {
           "127.0.0.1:1980": 1
       },
       "type": "roundrobin"
    },
    "uri": "/hello"
}'
```

In addition, it would be better if the mirror directive could support variable.

Thanks.

**Comment by membphis** [comment]
discuss mail: 

https://lists.apache.org/thread.html/ra5ea8a97f55b2b139b42b8c7b56fe26708fe3074fc34815afd52ea7d%40%3Cdev.apisix.apache.org%3E
