### ISSUE TITLE
feature: eureka integration

### ISSUE THREAD

**Issue by qiujiayu** [apache/incubator-apisix#1279]
This is an idea about integrating APISIX with eureka：

1. Added  discovery component, such as eureka;
2. Use the `upstream.service_name`  to associate the application name (`spring.application.name` in spring boot)
3. In `apisix.balancer`, according to the `upstream.service_name`, first find the application nodes in the discovery;

If you want to register APISIX with the registry, it will be more complicated. Do you have any requirements for this?

**Comment by membphis** [comment]
related issue: https://github.com/apache/incubator-apisix/issues/804

**Comment by qiujiayu** [comment]
现在是为了方便，使用了upstream_id 关联 注册中心的服务名。是不是增加一个service_name 可能会更好（route 和 service 都要加）？

Now, for convenience, `upstream_id` is used to associate the service name of the registry. Would it be better to add a `service_name` (both route and service)?

**Comment by soulsoul** [comment]
accrording to your description， you want to fetch the meta info from eureka ，and then get backend nodes info,  and balancer by APISIX.  so we should exchange the meta info  to the APISIX upstream nodes info . and choose the LB mechanism to route . is it right ?  
so we should think about that if we need cache the meta info from eureka.  and how to update ? 
the config item maybe need  server url of Eureka 、the application name ( spring.application.name in spring boot ) etc.

**Comment by qiujiayu** [comment]
You understand very well.

Use `ngx_timer_every` to fetch meta info rom eureka  regularly.

For more details, see the PR #1281
