### ISSUE TITLE
hard to extend the `nodes` of upstream

### ISSUE THREAD

**Issue by qiujiayu** [apache/incubator-apisix#1282]
recommended that `nodes` of upstream be changed from 

```
nodes = {
	"39.97.63.215:80": 1
}
```
 to 

```
nodes = [{
	ip = ,
	port = ,
	weight = ,
	metadata = {

	}
}]
```.

For easy extension and integration with the spring cloud.

**Comment by membphis** [comment]
@Miss-you please take a look at this

**Comment by moonming** [comment]
@qiujiayu why change to the latter format?

**Comment by qiujiayu** [comment]
> @qiujiayu why change to the latter format?
> `"39.97.63.215:80": 1` is easy and clear.

@moonming When using the registry, manage the metadata of nodes through the registry, Then through this metadata to achieve some of the enterprise personality requirements, such as: gray deployment.

**Comment by moonming** [comment]
please show a example. thx

Thanks,
Ming Wen
Twitter: _WenMing


qiujiayu <notifications@github.com> 于2020年3月17日周二 上午9:25写道：

**Comment by qiujiayu** [comment]
@moonming Sometimes we test online and want the test request to go to the test server, other requests are not.

**Comment by moonming** [comment]
nodes = {
	"39.97.63.215:80": 1
}
@qiujiayu I means the example for `metadata`

> @moonming Sometimes we test online and want the test request to go to the test server, other requests are not.

can you show a example how `metadata` for it, thx

**Comment by qiujiayu** [comment]
@moonming 

service A has two nodes:

```
nodes = [{
	ip = "192.168.1.100",
	port = 8080,
	weight = 1,
	metadata = {
              test_server = "true"
	}
},
{
	ip = "192.168.1.101",
	port = 8080,
	weight = 1,
	metadata = {
              test_server = "false"
	}
},
]
```

if request header has "test:true", then proxy to node: "192.168.1.100", else  proxy to "192.168.1.101".

**Comment by moonming** [comment]
We recommend do this job on the route in Apache APISIX, not the upstream node, for example:
```
curl -i http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/index.html",
    "vars": [
        ["arg_test", "true"]
    ],
    "upstream": {
        "nodes": {
            "192.168.1.100:80": 1
        }
    }
}'
```
and 
```
curl -i http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/index.html",
    "vars": [
        ["arg_test", "false"]
    ],
    "upstream": {
        "nodes": {
            "192.168.1.101:80": 1
        }
    }
}'
```

**Comment by qiujiayu** [comment]
> We recommend do this job on the route in Apache APISIX, not the upstream node, for example:
> 
> ```
> curl -i http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
> {
>     "uri": "/index.html",
>     "vars": [
>         ["arg_test", "true"]
>     ],
>     "upstream": {
>         "nodes": {
>             "192.168.1.100:80": 1
>         }
>     }
> }'
> ```
> 
> and
> 
> ```
> curl -i http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
> {
>     "uri": "/index.html",
>     "vars": [
>         ["arg_test", "false"]
>     ],
>     "upstream": {
>         "nodes": {
>             "192.168.1.101:80": 1
>         }
>     }
> }'
> ```
This example is good for static configuration. but for dynamic nodes from service discovery center.

**Comment by moonming** [comment]
@qiujiayu any update?

**Comment by qiujiayu** [comment]
Because these metadata is not only for the gateway, also apply to internal RPC. So be managed by registry

**Comment by qiujiayu** [comment]
implement in https://github.com/apache/incubator-apisix/pull/1440
