### ISSUE TITLE
bug: jwt plugin make the request http StatusCode= 500

### ISSUE THREAD

**Issue by lilien1010** [apache/incubator-apisix#1297]
### Issue description

```

2020/03/18 10:57:33 [error] 24#24: *9262 lua entry thread aborted: runtime error: /usr/local/apisix//deps/share/lua/5.1/resty/jwt.lua:820: attempt to concatenate local 'alg' (a nil value)
stack traceback:
coroutine 0:
        /usr/local/apisix//deps/share/lua/5.1/resty/jwt.lua: in function 'verify_jwt_obj'
        ...eps/share/lua/5.1/apisix/lua/apisix/plugins/jwt-auth.lua:154: in function 'phase_fun'
        /usr/local/apisix//deps/share/lua/5.1/apisix/lua/apisix.lua:129: in function 'run_plugin'
        /usr/local/apisix//deps/share/lua/5.1/apisix/lua/apisix.lua:342: in function 'fun_org'
        ...l/apisix//deps/share/lua/5.1/apisix/lua/apisix/debug.lua:126: in function 'http_access_phase'
        access_by_lua(nginx.conf:156):2: in main chunk, client: 119.139.198.202, server: , request: "POST /english_times/v1/homepage HTTP/1.1", host: "et.qtest.hellotalk.org"
```

**Comment by lilien1010** [comment]
mark first ,this is a issue in out production env, will offer more infomation later.

**Comment by liujianri** [comment]
这个问题 是因为在resty.jwt.lua 中取header中的alg时，是header.alg 这样取出来的，仔细看生成的jwt token 就能发现，生成jwt token 中的header 部分 header.alg 是nil的，注意是区分大小写的哦。
正确的应该是 :
`{
  "alg": "HS256",
  "typ": "JWT"
}`
错误的：
{
  "Alg": "HS256",
  "Typ": "JWT"
}

**Comment by chenqing24** [comment]
发生类似情况：
背景：基于apisix做了一个权限网关，用户登入时，会请求生成jwt token。
问题：一开始用都正常，在用测试账号反复登入时，出现异常，反馈码500
模拟请求：`curl --location --request GET 'http://gateway.itcjf.com/apisix/plugin/jwt/sign?key=cq39882`
error log：```
2020/03/18 17:37:32 [error] 2265479#2265479: *288045272 lua entry thread aborted: runtime error: /usr/share/lua/5.1/apisix/lua/apisix/consumer.lua:38: attempt to index local 'consumer' (a boolean value)
stack traceback:
coroutine 0:
/usr/share/lua/5.1/apisix/lua/apisix/consumer.lua: in function 'create_obj_fun'
/usr/share/lua/5.1/apisix/lua/apisix/core/lrucache.lua:64: in function 'global'
/usr/share/lua/5.1/apisix/lua/apisix/consumer.lua:64: in function 'plugin'
/usr/share/lua/5.1/apisix/lua/apisix/plugins/jwt-auth.lua:174: in function 'handler'
/usr/share/lua/5.1/apisix/lua/apisix/plugin.lua:213: in function 'handler'
/usr/share/lua/5.1/resty/radixtree.lua:627: in function 'dispatch'
.../lua/5.1/apisix/lua/apisix/http/router/radixtree_uri.lua:110: in function 'match'
/usr/share/lua/5.1/apisix/lua/apisix.lua:264: in function 'http_access_phase'
access_by_lua(nginx.conf:146):2: in main chunk, client: 10.10.150.6, server: , request: "GET /apisix/plugin/jwt/sign?key=cq39882 HTTP/1.1", host: "gateway.itcjf.com"
```
重启apisix后，故障消失。

**Comment by lilien1010** [comment]
@liujianri comment in english next time

**Comment by membphis** [comment]
@chenqing24 your bug has been fixed, please use the lastest Apache APISIX (master branch)

**Comment by lilien1010** [comment]
@membphis  this issue will be close，since it's the Backend capital issue
