### ISSUE TITLE
Is there a way to skip unit tests with prove.

### ISSUE THREAD

**Issue by Akayeshmantha** [apache/incubator-apisix#1308]
### Issue description

Is there any way to skip unit tests when running locally with the prove package.?

**Comment by moonming** [comment]
you want to skip all test cases in `/t`?  Or only skip one test case file?

**Comment by Akayeshmantha** [comment]
All test cases except one 😶 which am working on

**Comment by moonming** [comment]
you can run like this: `prove t/admin/ssl.t`

**Comment by Akayeshmantha** [comment]
Thanks @moonming
