### ISSUE TITLE
request help: can i modify apisix nginx conf directly

### ISSUE THREAD

**Issue by xxm404** [apache/incubator-apisix#1328]
### Issue description
This is our deploy modal
```
client -> apisix -> nginx -> php-fpm
```
At this modal, we need run two nginx(1. apisix 2, our nginx), we just want run only one nginx, can i modify apisix nginx conf to realize it ?

### Environment

* apisix version (cmd: `apisix version`): 1.1
* OS: ubuntu 14.04

**Comment by moonming** [comment]
You cannot modify `nginx.conf` directly, tt is an automatically generated file and should remain read-only.
However, you can modify `bin/apisix` to add your custom nginx configures.

**Comment by xxm404** [comment]
> You cannot modify `nginx.conf` directly, tt is an automatically generated file and should remain read-only.
> However, you can modify `bin/apisix` to add your custom nginx configures.

Great thank you
