### ISSUE TITLE
apisix in Stand-alone mode Health check does not take effect

### ISSUE THREAD

**Issue by isNextJuly** [apache/incubator-apisix#1329]
part of apisix.yaml：
  -
    uri: /hello
    upstream:
        nodes:
            "127.0.0.1:8080": 1
        type: roundrobin
        retries: 2
        checks:
            active:
                http_path: "/status"
                host: "localhost"
                healthy:
                    interval: 2
                    successes: 1
                unhealthy:
                    interval: 1
                    http_failures: 2
                req_headers:
                    - "User-Agent": "curl/7.29.0"
            passive:
                healthy:
                    http_statuses:
                        - 200
                        - 201
                    successes: 3
                unhealthy:
                    http_statuses:
                        - 500
                    http_failures: 3

error.log  info

2020/03/23 08:22:23 [error] 15#15: *9812913 failed to run balancer_by_lua*: /usr/local/apisix/lua/apisix/balancer.lua:77: attempt to concatenate field 'key' (a nil value)
stack traceback:
	/usr/local/apisix/lua/apisix/balancer.lua:77: in function 'create_obj_fun'
	/usr/local/apisix/lua/apisix/core/lrucache.lua:64: in function 'lrucache_checker'
	/usr/local/apisix/lua/apisix/balancer.lua:118: in function 'fetch_healthchecker'
	/usr/local/apisix/lua/apisix/balancer.lua:232: in function 'pick_server'
	/usr/local/apisix/lua/apisix/balancer.lua:297: in function 'load_balancer'
	/usr/local/apisix/lua/apisix.lua:462: in function 'http_balancer_phase'
	balancer_by_lua:2: in main chunk while connecting to upstream, client:

**Comment by isNextJuly** [comment]
use docker image   test-api-gateway

**Comment by membphis** [comment]
@isNextJuly please make a try with the latest master branch, we have fixed this bug.
