### ISSUE TITLE
Cron Job to clear travis ci cache daily .

### ISSUE THREAD

**Issue by Akayeshmantha** [apache/incubator-apisix#1336]
With the no of builds taking place from time to time, Travis ci gets slow. Will it be a good solution to remove cache daily with a cron job in Travis ?

**Comment by membphis** [comment]
These caches are mainly used to speed up environment installation. If we remove it, it will cause Travis to create the environment more slowly.

I recommend replacing Travis with Github Action later. Travis' number of concurrency is really too small.

**Comment by Akayeshmantha** [comment]
Sure 🙂
