### ISSUE TITLE
feature: support to run `header_filter` and `body_filter` phase for global rules

### ISSUE THREAD

**Issue by membphis** [apache/incubator-apisix#1338]
original comments: https://github.com/apache/incubator-apisix/issues/1202#issuecomment-603600053

**Comment by Akayeshmantha** [comment]
Hi @membphis  do we have any plugins we are running currently on the headerfiter phase or body filter phase ?

**Comment by membphis** [comment]
of course, we have plugin are using header filter phase and body filter phase.

eg: plugin `response-rewrite` .

**Comment by Akayeshmantha** [comment]
I would like to work on this issue @membphis
