### ISSUE TITLE
bug: 在安装文档里centos里面 没有讲解安装etcd服务的过程，直接启动了etcd服务

### ISSUE THREAD

**Issue by csluoqi** [apache/incubator-apisix#1340]
### Environment

* apisix version (cmd: `apisix version`):
* OS:

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

### What's the actual result? (including assertion message & call stack if applicable)

在安装文档里centos里面 没有讲解安装etcd服务的过程，直接启动了etcd服务

### What's the expected result?
正确安装etcd服务

**Comment by membphis** [comment]
@csluoqi please use English in the public channel

**Comment by moonming** [comment]
@csluoqi you can reopen this issue when you modify to English, thx
