### ISSUE TITLE
bug: 这里启动方式是通过源码安装apisix后，在源码目录里执行的命令。如果是通过yum命令安装的则不适合

### ISSUE THREAD

**Issue by csluoqi** [apache/incubator-apisix#1341]
### Environment

* apisix version (cmd: `apisix version`):
* OS:

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

### What's the actual result? (including assertion message & call stack if applicable)

![image](https://user-images.githubusercontent.com/13494828/77607427-417f8180-6f55-11ea-862d-4e8880b38711.png)

### What's the expected result?
添加说明，如果是通过源码安装的可以通过这样的命令启动关闭apisix

**Comment by soulsoul** [comment]
use English please！ @csluoqi

**Comment by moonming** [comment]
@csluoqi Please use English in the public channel.
you can reopen this issue when you modify to English, thx
