### ISSUE TITLE
request help: `Provisional headers are shown` in dashboard

### ISSUE THREAD

**Issue by ZanderMo** [apache/incubator-apisix#1350]
### Issue description
在插件里return 200,{msg:"somthing"},前端报 Provisional headers are shown
咋整？

### Environment

* apisix version (cmd: `apisix version`):1.1
* OS:

**Comment by ZanderMo** [comment]
跨域问题造成的，但是上游的已经解决了跨域问题，过了插件后就又跨域了，怎么解决啊

**Comment by membphis** [comment]
please use English in public channel
