### ISSUE TITLE
request help: What's the use of doc / apisix-plugin-design.graffle?

### ISSUE THREAD

**Issue by Miss-you** [apache/incubator-apisix#1352]
### Issue description

I looked at the documentation in the project and searched for this keyword. There was no related introduction and no place to use it.

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by Miss-you** [comment]
@membphis

**Comment by membphis** [comment]
I create the image by tool `OmniGraffle`, that is the source file.

![image](https://user-images.githubusercontent.com/6814606/77764659-f611c400-7077-11ea-8c41-aef8f798b8ce.png)

**Comment by dabue** [comment]
Each plug-in should have  the check_schema method to avoid  wrong input  and  impact functions in specific phase by implementing the method such as rewrite.

lua/apisix.lua describes how to load plug-ins.



88786912@qq.com
 
From: 88786912@qq.com
Date: 2020-03-28 07:55
To: apache/incubator-apisix; incubator-apisix
CC: Subscribed
Subject: Re: Re: [apache/incubator-apisix] request help: What's the use of doc / apisix-plugin-design.graffle? (#1352)
got it, that's good.



88786912@qq.com
 
From: YuanSheng Wang
Date: 2020-03-27 22:12
To: apache/incubator-apisix
CC: Subscribed
Subject: Re: [apache/incubator-apisix] request help: What's the use of doc / apisix-plugin-design.graffle? (#1352)
I create the image by tool OmniGraffle, that is the source file.
