### ISSUE TITLE
change: use local DNS resolver by default

### ISSUE THREAD

**Issue by membphis** [apache/incubator-apisix#1378]
discuss email: https://lists.apache.org/thread.html/r98384d8c6a2fe4013c1d96430d51e500c4158a7531b79e67b0daa8ab%40%3Cdev.apisix.apache.org%3E

**Comment by membphis** [comment]
https://github.com/apache/incubator-apisix/blob/master/conf/config.yaml#L83-L87

This configuration information is not required by default.

**Comment by dabue** [comment]
I'll update it.



88786912@qq.com
 
From: YuanSheng Wang
Date: 2020-03-31 21:30
To: apache/incubator-apisix
CC: Subscribed
Subject: Re: [apache/incubator-apisix] change: Should Apache APISIX use local DNS resolver by default (#1378)
https://github.com/apache/incubator-apisix/blob/master/conf/config.yaml#L83-L87
This configuration information is not required by default.
