### ISSUE TITLE
request help: document not valid

### ISSUE THREAD

**Issue by marshalys** [apache/incubator-apisix#1390]
### Issue description
I follow this document to setup apisix: https://github.com/apache/incubator-apisix/blob/master/doc/how-to-build.md#5-update-admin-api-token-to-protect-apache-apisix
I install success. But I found that  set `admin_key ` has no effect. May be  `admin_key ` is not valid in 1.1

### Environment

* apisix version (cmd: `apisix version`): 1.1
* OS: ubuntu 18.04

**Comment by membphis** [comment]
you need to use the doc v1.1:

https://github.com/apache/incubator-apisix/blob/v1.1/doc/how-to-build.md

**Comment by marshalys** [comment]
Thank you!
