### ISSUE TITLE
doc(k8s): add a link to `doc/README.md`

### ISSUE THREAD

**Issue by membphis** [apache/incubator-apisix#1395]
https://github.com/apache/incubator-apisix/blob/master/doc/README.md

And we need more comments: https://github.com/apache/incubator-apisix/pull/1218/files#r400574549

**Comment by scaat** [comment]
1. Add a link to README.md
2. Add some brief introduction to the doc(k8s)
Is that right？ @membphis

**Comment by membphis** [comment]
yes, you are right ^_^

**Comment by scaat** [comment]
ok，I have made some additions. @membphis
