### ISSUE TITLE
bug: failed to load plugin install by docker

### ISSUE THREAD

**Issue by samunbest** [apache/incubator-apisix#1400]
### Issue description
2020/04/06 04:54:18 [error] 23#23: *1 [lua] plugin.lua:66: load_plugin(): failed to load plugin [proxy-cache] err: module 'apisix.plugins.proxy-cache' not found:
	no field package.preload['apisix.plugins.proxy-cache']
	no file '/usr/local/apisix//deps/share/lua/5.1/apisix/plugins/proxy-cache.lua'
	no file '/usr/share/lua/5.1/apisix/lua/apisix/plugins/proxy-cache.lua'
	no file '/usr/local/share/lua/5.1/apisix/lua/apisix/plugins/proxy-cache.lua'
	no file '/usr/local/apisix//deps/share/lua/5.1/apisix/lua/apisix/plugins/proxy-cache.lua'
	no file '/usr/local/apisix/lua/apisix/plugins/proxy-cache.lua'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/proxy-cache.ljbc'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/proxy-cache/init.ljbc'
	no file '/usr/local/openresty/lualib/apisix/plugins/proxy-cache.ljbc'
	no file '/usr/local/openresty/lualib/apisix/plugins/proxy-cache/init.ljbc'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/proxy-cache.lua'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/proxy-cache/init.lua'
	no file '/usr/local/openresty/lualib/apisix/plugins/proxy-cache.lua'
	no file '/usr/local/openresty/lualib/apisix/plugins/proxy-cache/init.lua'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/proxy-cache.ljbc'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/proxy-cache/init.ljbc'
	no file '/usr/local/openresty/lualib/apisix/plugins/proxy-cache.ljbc'
	no file '/usr/local/openresty/lualib/apisix/plugins/proxy-cache/init.ljbc'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/proxy-cache.lua'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/proxy-cache/init.lua'
	no file '/usr/local/openresty/lualib/apisix/plugins/proxy-cache.lua'
	no file '/usr/local/openresty/lualib/apisix/plugins/proxy-cache/init.lua'
	no file './apisix/plugins/proxy-cache.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/apisix/plugins/proxy-cache.lua'
	no file '/usr/local/share/lua/5.1/apisix/plugins/proxy-cache.lua'
	no file '/usr/local/share/lua/5.1/apisix/plugins/proxy-cache/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/proxy-cache.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/proxy-cache/init.lua'
	no file '/usr/local/apisix/lua/apisix/plugins/proxy-cache.lua'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/proxy-cache.ljbc'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/proxy-cache/init.ljbc'
	no file '/usr/local/openresty/lualib/apisix/plugins/proxy-cache.ljbc'
	no file '/usr/local/openresty/lualib/apisix/plugins/proxy-cache/init.ljbc'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/proxy-cache.lua'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/proxy-cache/init.lua'
	no file '/usr/local/openresty/lualib/apisix/plugins/proxy-cache.lua'
	no file '/usr/local/openresty/lualib/apisix/plugins/proxy-cache/init.lua'
	no file './apisix/plugins/proxy-cache.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/apisix/plugins/proxy-cache.lua'
	no file '/usr/local/share/lua/5.1/apisix/plugins/proxy-cache.lua'
	no file '/usr/local/share/lua/5.1/apisix/plugins/proxy-cache/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/proxy-cache.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/proxy-cache/init.lua'
	no file '/usr/local/apisix//deps/lib64/lua/5.1/apisix/plugins/proxy-cache.so'
	no file '/usr/local/apisix//deps/lib/lua/5.1/apisix/plugins/proxy-cache.so'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/proxy-cache.so'
	no file '/usr/local/openresty/lualib/apisix/plugins/proxy-cache.so'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/proxy-cache.so'
	no file '/usr/local/openresty/lualib/apisix/plugins/proxy-cache.so'
	no file './apisix/plugins/proxy-cache.so'
	no file '/usr/local/lib/lua/5.1/apisix/plugins/proxy-cache.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix/plugins/proxy-cache.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/usr/local/openresty/luajit/l

### Environment

* apisix version (cmd: `apisix version`): 1.1
* OS:
Debian
### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by samunbest** [comment]
the problem occurs even if  i fetch the latest version

**Comment by membphis** [comment]
Please provide your installation steps

**Comment by moonming** [comment]
@samunbest I think you need to update `config.yaml`. please check if `proxy-cache` plugin is in the configuration file

**Comment by samunbest** [comment]
> @samunbest I think you need to update `config.yaml`. please check if `proxy-cache` plugin is in the configuration file

here is one of the errors in the error log，there are many errors like this。

**Comment by samunbest** [comment]
> Please provide your installation 
 
i just followed the official guides
https://github.com/apache/incubator-apisix-docker

**Comment by moonming** [comment]
> > @samunbest I think you need to update `config.yaml`. please check if `proxy-cache` plugin is in the configuration file
> 
> here is one of the errors in the error log，there are many errors like this。

please try the latest version: https://github.com/apache/incubator-apisix/blob/master/conf/config.yaml

**Comment by membphis** [comment]
it seems that you are using the latest `config.yaml` file with APISIX version 1.1 .

I think you should use https://github.com/apache/incubator-apisix/blob/v1.1/conf/config.yaml

**Comment by samunbest** [comment]
> it seems that you are using the latest `config.yaml` file with APISIX version 1.1 .
> 
> 
> 
> I think you should use https://github.com/apache/incubator-apisix/blob/v1.1/conf/config.yaml

it works！thanks very much

**Comment by samunbest** [comment]
> > > @samunbest I think you need to update `config.yaml`. please check if `proxy-cache` plugin is in the configuration file
> 
> > 
> 
> > here is one of the errors in the error log，there are many errors like this。
> 
> 
> 
> please try the latest version: https://github.com/apache/incubator-apisix/blob/master/conf/config.yaml

 it works，thanks a lot
