### ISSUE TITLE
bug: Use Apache APISIX 1.1 version pressure test to find a performance problem

### ISSUE THREAD

**Issue by Miss-you** [apache/incubator-apisix#1403]
### Issue description

I took a stress test on Apache APISIX version 1.1 during the holiday and only ran a nginx worker process. The machine type is a physical machine, the operating system is tlinux2.2 0046, and the kernel version is 3.10.107

Pressure test method:
Directly request apisix. There is no rule in apisix itself, and the hit route matches the logic.
Pressure test command:

./wrk -c 10 -t 6 --la -d 30 http://apisix.com:9080/c

As a result, the CPU was overwhelmed by less than 2000qps.

![image](https://user-images.githubusercontent.com/3816205/78560056-ff551a80-7847-11ea-9b05-4f96cbd2e76f.png)

**Comment by membphis** [comment]
we have fixed this bug, please make a try with the master version.

commit: https://github.com/apache/incubator-apisix/commit/2870b798339a12364e5a7a3094f7a6eb8cb9df0d

**Comment by Miss-you** [comment]
Thanks, already solved
Because the table t has not been cleaned up, it causes more and more memory to be used, which affects the operating efficiency of apisix.
Furthermore, the way Lua is written is very different from that of golang or java. Local variables do not end their life cycle due to the exit of the function and need to be released by themselves.
