### ISSUE TITLE
[discuss] maybe apisix should look for an A record in dns query result instead of get random one

### ISSUE THREAD

**Issue by de1o** [apache/incubator-apisix#1404]
### Issue description
now in apisix.core.utils.dns_parse method, the code choose a random one from dns query result.
when the dns record is a CNAME record, dns query may get result like 
```
[{"cname":"cname.xxx.com","class":1,"ttl":600,"name":"server.xxx.com","section":1,"type":5},
{"address":"10.9.1.1","class":1,"ttl":600,"name":"cname.xxx.com","section":1,"type":1}]
```
in this case, user expect to get the A record of domain server.xxx.com, while apisix will return random result, which may cause upstream/routes get empty nodes.

### Environment

* apisix version (cmd: `apisix version`): v1.1
* OS: any

### Minimal test code / Steps to reproduce the issue
1.config a domain in upstream, the domain's dns record set to a CNAME record.
2.request the route configed with the domain

### What's the actual result? (including assertion message & call stack if applicable)
request will fail randomly depend on the code in dns_parse

### What's the expected result?
requests always work fine with CNAME record domains.
apisix should do a loop in dns query result to find a A record, or filter all the CNAME record then find a random A record?

**Comment by de1o** [comment]
I read the current master branch code, my issue has already been solved, dns_parse do a second dns query for the CNAME domain.
In my test case, the A record will return in the first DNS query(with the CNAME record as array), so may be do a loop find first can save a dns query?

**Comment by membphis** [comment]
The first one is not a good solution by default.

DNS returns multiple addresses, it is to let the client choose randomly, so that it can achieve "load balancing".

**Comment by de1o** [comment]
thanks, so we can still filter all A records in query result and then choose a random one(for saving another dns query?)

**Comment by membphis** [comment]
yes. we can close this issue now.
