### ISSUE TITLE
implement sys logger for apisix

### ISSUE THREAD

**Issue by Akayeshmantha** [apache/incubator-apisix#1406]

**Comment by membphis** [comment]
please provide more detail information

**Comment by moonming** [comment]
will implemented by https://github.com/detailyang/lua-resty-rfc5424 or https://github.com/cloudflare/lua-resty-logger-socket?

**Comment by Akayeshmantha** [comment]
Yeah @moonming  @membphis 

resty.logger.socket. Would it be ok to move forward with it ?

**Comment by Akayeshmantha** [comment]
But this library is not in luarocks will it be an issue

**Comment by membphis** [comment]
I have uploaded it to luarocks right now: https://luarocks.org/modules/membphis/lua-resty-logger-socket

@Akayeshmantha I think you can continue your job

**Comment by Akayeshmantha** [comment]
thanks @membphis
