### ISSUE TITLE
request help: Can supported to bind consumer to service or route?

### ISSUE THREAD

**Issue by bzp2010** [apache/incubator-apisix#1408]
### Issue description
At present, it seems that only by creating a consumer and adding the same plugin to route or service can route and service be authenticated.

Whether it should be allowed to bind consumers directly to a route or service to achieve exact matching of consumers instead of allowing all routes and services using the same authentication plug-in to be globally matched.
### Environment

* apisix version (cmd: `apisix version`): 1.1
* OS: CentOS 7.7

**Comment by membphis** [comment]
>  it should be allowed to bind consumers directly to a route or service

why do we need this feature?

**Comment by bzp2010** [comment]
It can help solve access control and control which routes and services a consumer can access.
In the current program, it seems that several routes and services with the same authentication plug-in can be accessed by the same consumer, which may cause unauthorized access.

> similar issues #1062 #1243 #385

**Comment by membphis** [comment]
you are right, that is a todo feature

**Comment by membphis** [comment]
we can use plugin `consumer-restriction` to support this.

https://github.com/apache/incubator-apisix/blob/master/doc/plugins/consumer-restriction.md
