### ISSUE TITLE
request help: How to add new consumer in stand-alone mode?

### ISSUE THREAD

**Issue by eiyouwang** [apache/incubator-apisix#1447]
### Issue description
Since we cannot using Admin API when using the stand alone mode, how can we add a new consumer or bind a consumer to the route? 
Can we add the consumer and binding relationship in the yaml file like the route/service/upstream?

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by moonming** [comment]
@membphis please have a look

**Comment by membphis** [comment]
The structure is the same, you can refer to how to add a service object.
