### ISSUE TITLE
bug: lua: /usr/bin/apisix:535: module 'apisix.core.profile' not found:

### ISSUE THREAD

**Issue by cyxinda** [apache/incubator-apisix#1449]
### Issue description
When I install the apisix of the version 1.2 or the version master,the bug 'lua: /usr/bin/apisix:535: module 'apisix.core.profile' not found:' happens.

### Environment
* My lua version is :
`[root@v175 incubator-apisix-master]# lua -v
Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio
`
* apisix version (cmd: `apisix version`):
1.2 or master
* OS:centos 7.5
### Minimal test code / Steps to reproduce the issue
1.First I run the command 'make deps' in the $APISIX_ROOT.
2.Then I run the commond 'make install' to copy the directory of logs and conf to the directory of '/usr/local/apisix/'.
3.I copy the directory of deps and dashboard to the directory of /usr/local/apisix/.
4.Finally ,I run the command 'apisix start',And the bug happens.

### What's the actual result? (including assertion message & call stack if applicable)
[root@v175 apisix]# apisix start
lua: /usr/bin/apisix:535: module 'apisix.core.profile' not found:
        no field package.preload['apisix.core.profile']
        no file '/usr/local/apisix/deps/share/lua/5.1/apisix/core/profile.lua'
        no file '/usr/local/share/lua/5.3/apisix/core/profile.lua'
        no file '/usr/local/share/lua/5.3/apisix/core/profile/init.lua'
        no file '/usr/local/lib/lua/5.3/apisix/core/profile.lua'
        no file '/usr/local/lib/lua/5.3/apisix/core/profile/init.lua'
        no file './apisix/core/profile.lua'
        no file './apisix/core/profile/init.lua'
        no file '/usr/local/apisix/deps/lib64/lua/5.1/apisix/core/profile.so'
        no file '/usr/local/apisix/deps/lib/lua/5.1/apisix/core/profile.so'
        no file '/usr/local/lib/lua/5.3/apisix/core/profile.so'
        no file '/usr/local/lib/lua/5.3/loadall.so'
        no file './apisix/core/profile.so'
        no file '/usr/local/apisix/deps/lib64/lua/5.1/apisix.so'
        no file '/usr/local/apisix/deps/lib/lua/5.1/apisix.so'
        no file '/usr/local/lib/lua/5.3/apisix.so'
        no file '/usr/local/lib/lua/5.3/loadall.so'
        no file './apisix.so'
stack traceback:
        [C]: in function 'require'
        /usr/bin/apisix:535: in upvalue 'read_yaml_conf'
        /usr/bin/apisix:644: in upvalue 'init'
        /usr/bin/apisix:809: in field '?'
        /usr/bin/apisix:854: in main chunk
        [C]: in ?

### What's the expected result?
no message occur,and the process of apisix running .

**Comment by membphis** [comment]
the `2` step is wrong. 

The Apache APISIX can not be installed by this way. `make install` is a wrong way.

If you want to install APISIX to your local machine, you need to install it by luarocks.

```shell
1.First I run the command 'make deps' in the $APISIX_ROOT.
2.Then I run the commond 'make install' to copy the directory of logs and conf to the directory of '/usr/local/apisix/'.
```

**Comment by moonming** [comment]
@membphis I think we can change the name of `make install`

**Comment by cyxinda** [comment]
> the `2` step is wrong.
> 
> The Apache APISIX can not be installed by this way. `make install` is a wrong way.
> 
> If you want to install APISIX to your local machine, you need to install it by luarocks.
> 
> ```shell
> 1.First I run the command 'make deps' in the $APISIX_ROOT.
> 2.Then I run the commond 'make install' to copy the directory of logs and conf to the directory of '/usr/local/apisix/'.
> ```

There are three ways to install apisix at least in the guidance document,include 'source code','luarocks',' yum' and so on. Why the way of source code is wrong ? And the way  by yum is also wrong .
`
[root@v175 install]# wget http://www.apache.org/dist/incubator/apisix/1.2/apache-apisix-1.2-incubating-src.tar.gz
--2020-04-15 15:51:25--  http://www.apache.org/dist/incubator/apisix/1.2/apache-apisix-1.2-incubating-src.tar.gz
Resolving www.apache.org (www.apache.org)... 95.216.24.32, 40.79.78.1, 2a01:4f9:2a:185f::2
Connecting to www.apache.org (www.apache.org)|95.216.24.32|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://downloads.apache.org/incubator/apisix/1.2/apache-apisix-1.2-incubating-src.tar.gz [following]
--2020-04-15 15:51:26--  https://downloads.apache.org/incubator/apisix/1.2/apache-apisix-1.2-incubating-src.tar.gz
Resolving downloads.apache.org (downloads.apache.org)... 88.99.95.219, 2a01:4f8:10a:201a::2
Connecting to downloads.apache.org (downloads.apache.org)|88.99.95.219|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-04-15 15:51:33 ERROR 404: Not Found.
`

**Comment by cyxinda** [comment]
> the `2` step is wrong.
> 
> The Apache APISIX can not be installed by this way. `make install` is a wrong way.
> 
> If you want to install APISIX to your local machine, you need to install it by luarocks.
> 
> ```shell
> 1.First I run the command 'make deps' in the $APISIX_ROOT.
> 2.Then I run the commond 'make install' to copy the directory of logs and conf to the directory of '/usr/local/apisix/'.
> ```

There are three ways to install apisix at least in the guidance document,include 'source code','luarocks',' yum' and so on. Why the way of source code is wrong ? And the way  by yum is also wrong .
`
[root@v175 install]# wget http://www.apache.org/dist/incubator/apisix/1.2/apache-apisix-1.2-incubating-src.tar.gz
--2020-04-15 15:51:25--  http://www.apache.org/dist/incubator/apisix/1.2/apache-apisix-1.2-incubating-src.tar.gz
Resolving www.apache.org (www.apache.org)... 95.216.24.32, 40.79.78.1, 2a01:4f9:2a:185f::2
Connecting to www.apache.org (www.apache.org)|95.216.24.32|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://downloads.apache.org/incubator/apisix/1.2/apache-apisix-1.2-incubating-src.tar.gz [following]
--2020-04-15 15:51:26--  https://downloads.apache.org/incubator/apisix/1.2/apache-apisix-1.2-incubating-src.tar.gz
Resolving downloads.apache.org (downloads.apache.org)... 88.99.95.219, 2a01:4f8:10a:201a::2
Connecting to downloads.apache.org (downloads.apache.org)|88.99.95.219|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-04-15 15:51:33 ERROR 404: Not Found.
`

**Comment by membphis** [comment]
> @membphis I think we can change the name of `make install`

Determine whether it is loaded by Luarocks.

If no Luarocks environment variable is found, we can display some warning messages.

**Comment by cyxinda** [comment]
After I reinstalled all the  independencies of the software ,the apisix of version1.2 has been installed successfully.
呜呜呜..........
