### ISSUE TITLE
request help: How to set user rights management？

### ISSUE THREAD

**Issue by FunnySunshine520** [apache/incubator-apisix#1453]
### Issue description
If I had five interfaces：foo/a, foo/b, foo/c, foo/d, foo/e;
And there are two consumers: userA, userB.

userA can only access interface foo/a, foo/b, foo/c
userB can only access interface foo/c, foo/d, foo/e

I want userA and userB to use the same URL access foo/e，then userA does not have permission and userB may access normally。

### question
Can I build the effect I want through the existing plugins？

**Comment by iGeeky** [comment]
You can try this plugin [wolf-rbac](https://github.com/apache/incubator-apisix/blob/master/doc/plugins/wolf-rbac.md). Its main function is user authentication and interface authorization management, the corresponding function is provided by [wolf](https://github.com/iGeeky/wolf). wolf-rbac plugin for wolf client.

**Comment by moonming** [comment]
how about https://github.com/apache/incubator-apisix/pull/1437?
