### ISSUE TITLE
bug: delete global_rules  will 500 status if the id is nil

### ISSUE THREAD

**Issue by OnlyPiglet** [apache/incubator-apisix#1459]
### Issue description
when I try to delete global_rules without id ,the sysytem will occur 500

### Environment

* apisix version (cmd: `apisix version`): v1.1
* OS: centos 7.0

### Minimal test code / Steps to reproduce the issue
1.  method:delete path http://host:9080/apisix/admin/global_rules/
2.
3.

### What's the actual result? (including assertion message & call stack if applicable)

500 openresty

### What's the expected result?

with a good response and friendly handler

**Comment by moonming** [comment]
@membphis please take a look

**Comment by OnlyPiglet** [comment]
fixed by https://github.com/apache/incubator-apisix/issues/1473 thanks a lot
