### ISSUE TITLE
 How to match the root directory？

### ISSUE THREAD

**Issue by xuliangyong** [apache/incubator-apisix#1465]
### Issue description
I want match，  
Then jump to different routes according to the conditions
as follows：

```
location = / { 
    if (true) { 
        route /pathA 
    }else {
        route /pathB 
    }
} 
```

Is it okay to write like this？
-
    uri: /
    plugins:
        xxxxx: {}

If not okay, what should I write

### Environment

* apisix version  1.1
* OS: centos7

**Comment by membphis** [comment]
the current way is right.

**Comment by xuliangyong** [comment]
thanks！

**Comment by xuliangyong** [comment]
2020/04/16 19:32:40 [error] 18219#18219: *1634757 [lua] balancer.lua:299: load_balancer(): failed to pick server: missing upstream configuration while connecting to upstream, client: 172.22.142.141, server: , request: "GET / HTTP/1.1", host: "1001.sszt.yun300.cn"

**Comment by membphis** [comment]
that is a mini test case, and I confirm it can work fine.

Please check that you have set "#END" in the correct way.

```
=== TEST 4: uri: "/"
--- yaml_config eval: $::yaml_config
--- apisix_yaml
routes:
  -
    uri: /
    plugins:
        fault-injection:
            abort:
                http_status: 200
                body: "hello world"

#END
--- request
GET /
--- response_body eval
qr/hello world/
--- error_log
use config_center: yaml
--- no_error_log
[error]
```

**Comment by membphis** [comment]
BTW, we dont have the code of plugin `sszt-anth`. you can make a try with plugin `fault-injection`.

**Comment by xuliangyong** [comment]
![image](https://user-images.githubusercontent.com/26759441/79454292-87dc7380-801d-11ea-837a-1942e50af253.png)

**error info**
2020/04/16 20:03:27 [error] 15684#15684: *2275265 [lua] config_yaml.lua:166: failed to check item data of [routes] err:property "upstream" validation failed: property "nodes" is required ,val: {"uri":"\/","upstream":{"hash_on":"vars","fault-injection":{"abort":{"body":"hello world","http_status":200}}}}, context: ngx.timer
2020/04/16 20:03:27 [error] 15688#15688: *2275273 [lua] config_yaml.lua:166: failed to check item data of [routes] err:property "upstream" validation failed: property "nodes" is required ,val: {"uri":"\/","upstream":{"hash_on":"vars","fault-injection":{"abort":{"body":"hello world","http_status":200}}}}, context: ngx.timer
2020/04/16 20:03:27 [error] 15682#15682: *2275244 [lua] config_yaml.lua:166: failed to check item data of [routes] err:property "upstream" validation failed: property "nodes" is required ,val: {"uri":"\/","upstream":{"hash_on":"vars","fault-injection":{"abort":{"body":"hello world","http_status":200}}}}, context: ngx.timer
