### ISSUE TITLE
bug: apisix 0.7 0.8 0.9 installation failed due to `lua-resty-healthcheck-iresty` version invalid.

### ISSUE THREAD

**Issue by shuaijinchao** [apache/incubator-apisix#1470]
### Issue description
APISIX 0.7、0.8 and 0.9 depend `lua-resty-healthcheck-iresty` 1.0.1 version, Luarocks installation prompts that the version is invalid and causes the installation to fail.
This problem will occur in any system installed via luarocks.
Solution: Install `lua-resty-healthcheck-iresty` version 2.0 via luockock. The most perfect way is to add 1.0.1 version tags in the `lua-resty-healthcheck-iresty` warehouse.

**Comment by moonming** [comment]
@membphis please take a look, I can not find the commit id of version 1.0.1

**Comment by membphis** [comment]
the `lua-resty-healthcheck-iresty` 1.0.1 version used `devel` branch which is unstable.

so I created a tag `v1.0.1` and released a new version `1.0.1-2`. the older version APISIX(eg v0.9) can be installed normally, I test it and work fine at my local machine.

https://luarocks.org/manifests/membphis/lua-resty-healthcheck-iresty-1.0.1-2.rockspec
