### ISSUE TITLE
request help: 大概什么时候会出新的release版本，我看也快两个月过去了

### ISSUE THREAD

**Issue by fanandactuaility** [apache/incubator-apisix#1476]
大概什么时候会出新的release版本，我看也快两个月过去了

**Comment by totemofwolf** [comment]
On the way, 1.2 rc1 has launched already.

**Comment by moonming** [comment]
@fanandactuaility Please use English in the public channel, thx
the 1.2 already released

**Comment by fanandactuaility** [comment]
Thank you for your answer.
