### ISSUE TITLE
bug: 添加了插件，保存时提示找不到

### ISSUE THREAD

**Issue by 342379784** [apache/incubator-apisix#1481]
### Issue description
自己写了个插件名为zyyt-auth，按照文档修改了zyyt-auth.lua文件中的plugin_name,priority属性，在config/config.yaml也加上了配置，但是设置插件的时候提示”unkown [zyyt-auth]“。查找代码后发现错误是在api/lua/apisix/admin/plugins.lua文件45.70行报出来的。他们都是通过加载require("apisix.plugin")得到的。这个指向哪里呢，我应该在哪里配置才能不报错

### Environment
使用npm安装包安装
* apisix version (cmd: `apisix version`):1.1
* OS:
centos7  
### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by membphis** [comment]
If you are a developer, it is recommended that you use the master branch for development.

And you can provide a minimal use case so that everyone can help you determine the problem.

**Comment by moonming** [comment]
@342379784 Please use English in the public channel, thx

**Comment by moonming** [comment]
did you add this file to `lua/apisix/plugins` directory?

**Comment by 342379784** [comment]
yes,i promise。wait，I send picture



---原始邮件---
发件人: "Wen Ming"<notifications@github.com&gt;
发送时间: 2020年4月20日(周一) 晚上10:19
收件人: "apache/incubator-apisix"<incubator-apisix@noreply.github.com&gt;;
抄送: "朱英俊"<342379784@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [apache/incubator-apisix] bug: 添加了插件，保存时提示找不到 (#1481)




 
did you add this file to lua/apisix/plugins directory?

**Comment by 342379784** [comment]
this file is my plugin




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Wen Ming"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 晚上10:19
收件人:&nbsp;"apache/incubator-apisix"<incubator-apisix@noreply.github.com&gt;;
抄送:&nbsp;"想个ID真费劲"<342379784@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-apisix] bug: 添加了插件，保存时提示找不到 (#1481)





 
did you add this file to lua/apisix/plugins directory?

**Comment by membphis** [comment]
do you reload your APISIX service? if you still have problem, please let we know

**Comment by 342379784** [comment]
I&nbsp;Resolved， thanks。I try restart ，no solve. so I try kill this port and restart，success.&nbsp;

---原始邮件---
发件人: "YuanSheng Wang"<notifications@github.com&gt;
发送时间: 2020年6月20日(周六) 下午5:07
收件人: "apache/incubator-apisix"<incubator-apisix@noreply.github.com&gt;;
抄送: "朱英俊"<342379784@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [apache/incubator-apisix] bug: 添加了插件，保存时提示找不到 (#1481)




 
do you reload your APISIX service? if you still have problem, please let we know
