### ISSUE TITLE
request help: fail to match upstream by route

### ISSUE THREAD

**Issue by dxvgef** [apache/incubator-apisix#1489]
### Issue description

我有个http server可以通过`http://192.168.10.200:16666/echo`正常请求，并且和apisix在同一台机器上，然后做如下配置：

### 创建upstream
```
desc：test
ip：127.0.0.1
port：16666
```
![image](https://user-images.githubusercontent.com/5192264/79947619-d4ec9980-84a4-11ea-9c47-4fb431e4fbb5.png)

### 创建service
```
desc: test
upstream: test
```
![image](https://user-images.githubusercontent.com/5192264/79947752-17ae7180-84a5-11ea-9a5d-9ee40004a6cc.png)

### 创建router
```
URIs：/test/*
upstream：test
service：test
```
![image](https://user-images.githubusercontent.com/5192264/79947797-2eed5f00-84a5-11ea-86cf-f18236b2617c.png)

现在我访问`http://192.168.10.200:9080/test/echo`，提示404，而且是upstream提示出来的，这是什么情况啊？

### Environment

* apisix version (cmd: `apisix version`): 1.2
* OS: centos 7
* apisix dashboard: 1.0

**Comment by membphis** [comment]
please use English in public channel if possible

**Comment by iGeeky** [comment]
测试用例看起来是没啥问题的. 直接测试是/echo能正常访问. 经过gateway是通过/test/echo访问的, 404完全正常. 
你路由中的URIs可以直接写 /* 试试.

**Comment by dxvgef** [comment]
I changed gateway uri to `/*`, now i can be request normally through `http://192.168.10.200:9080/echo`, but I want the request gateway url `/test/*` to match upstream url `/*`, how to set routing rules?

**Comment by membphis** [comment]
I think you need to rewrite the `uri`, take a look at this plugin:

https://github.com/apache/incubator-apisix/blob/master/doc/plugins/response-rewrite-cn.md

**Comment by dxvgef** [comment]
Thx !
