### ISSUE TITLE
request help: How to add node to upstream using admin api?

### ISSUE THREAD

**Issue by dxvgef** [apache/incubator-apisix#1491]
### Issue description
I have an upstream, it has some nodes, I want to add a new node to this upstream, which admin api should I use?

### Environment

* apisix version (cmd: `apisix version`): 1.2
* OS:

**Comment by dxvgef** [comment]
I see that admin API with PATCH method can update the node attribute value, but it is an update operation for nodes, how to do an additional operation on it?

**Comment by moonming** [comment]
Apache APISIX only supports `PUT` now, `PATCH` is TODO.

**Comment by membphis** [comment]
Apache APISIX has supported `PATCH` for upstream nodes now.
Welcome to make a try.
