### ISSUE TITLE
request help: IPv6 dual-stack

### ISSUE THREAD

**Issue by Miss-you** [apache/incubator-apisix#1493]
### Issue description

Hi, I wonder if Apache APISIX currently supports IPv6 dual-stack.

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by spacewander** [comment]
APISIX can be configured to serve IPv6 client and talk to IPv6 upstream. There are several IPv6 relative tests. Therefore I think APISIX can serve both IPv4 and IPv6 in the same way.

**Comment by Miss-you** [comment]
I think the ability of APISIX IPV6 dual stack is based on Nginx, and it is also guaranteed by automated test cases, so it should support IPV6 dual stack.
I now create a virtual machine to verify this problem

**Comment by Miss-you** [comment]
I verified that Apache APISIX supports IPV6 dual stack by default
Server screenshot
![image](https://user-images.githubusercontent.com/3816205/80344106-a0f4e800-8899-11ea-91a4-d56d434ec668.png)

Client screenshot
![image](https://user-images.githubusercontent.com/3816205/80344116-a4886f00-8899-11ea-80e5-4850decacdfc.png)

However, it is open to question whether the Node node in Upstream supports IPv6 addresses
