### ISSUE TITLE
request help: the skywalking would be integrated to apisix?

### ISSUE THREAD

**Issue by cyxinda** [apache/incubator-apisix#1497]
### Issue description
the skywalking would be integrated to apisix as soon as possible ?

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by moonming** [comment]
yes, i am working on this feature.

**Comment by cyxinda** [comment]
> yes, i am working on this feature.

May I ask what time this feature will be finished?

**Comment by moonming** [comment]
I will try to finish this week, sorry for delay.

Thanks,
Ming Wen
Twitter: _WenMing


月夜枫 <notifications@github.com> 于2020年4月29日周三 上午10:24写道：

**Comment by membphis** [comment]
Apache APISIX has supported to work with Skywalking.
