### ISSUE TITLE
bug: 1.1 configuration not working under docker version: apisix:1.2-centos

### ISSUE THREAD

**Issue by wangyjx** [apache/incubator-apisix#1499]
### Issue description
After upgrade to docker image to 1.2-centos, it doesn't work with old (1.1) config
docker logs:
nginx: [emerg] invalid parameter: valid= in /usr/local/apisix/conf/nginx.conf:53

### Environment

* apisix version (cmd: `apisix version`): apisix:1.2-centos
* OS: Centos 7.6

### Minimal test code / Steps to reproduce the issue
1.  using attached file [conf.zip](https://github.com/apache/incubator-apisix/files/4527457/conf.zip)  to launch docker instance
2. Can see the docker instance keeps restarting
3. using docker logs to print the message,  can see
nginx: [emerg] invalid parameter: valid= in /usr/local/apisix/conf/nginx.conf:53

**Comment by moonming** [comment]
`dns_resolver_valid` added in `config.yaml` from 1.2 release, so I think you should update `config.yaml` first.

**Comment by wangyjx** [comment]
After I add the below line in config.yaml under dns_resolver section

  dns_resolver_valid: 30          # valid time for dns result 30 seconds


Docker still not able to start correctly, the error message becomes

**_nginx: [emerg] invalid number of arguments in "resolver_timeout" directive in /usr/local/apisix/conf/nginx.conf:54_**

**Comment by GameBelial** [comment]
@wangyjx You should add **resolver_timeout** option.
```yaml
    dns_resolver_valid: 30          # valid time for dns result 30 seconds
    resolver_timeout: 5             # resolver timeout
```

look [here](https://gitbox.apache.org/repos/asf?p=incubator-apisix-docker.git;a=blob;f=example/apisix_conf/config.yaml;h=b355e32cea2f1ed3e61b089162db54bc03fd5327;hb=e213c3281b265c8a86c26fb4a98c2d6749dd8e07)

**Comment by membphis** [comment]
There is no answer from the author for a long time, please close it first.
