### ISSUE TITLE
request help:How to send PATCH requests?

### ISSUE THREAD

**Issue by Weimc-w** [apache/incubator-apisix#1505]
当发送patch请求时传递的参数是一个json对象，只会把apisix中存在参数对应的值改变，未传参的配置会被清空。需求是改变传递参数的值，未传参的配置不变。
![patchRequest](https://user-images.githubusercontent.com/64339767/80295303-6e1cf800-87a4-11ea-9b76-c06e77c1ee5f.png)

**Comment by ShiningRush** [comment]
According [admin api doc](https://github.com/apache/incubator-apisix/blob/master/doc/admin-api.md#service), You should specify property in your path.
You can have a try for
```shell
curl --location --request PATCH 'http://127.0.01:9080/apisix/admin/services/5/desc' \
--data-raw '"pathTest"'

curl --location --request PATCH 'http://127.0.01:9080/apisix/admin/services/5/upstream_id' \
--data-raw '"1"'
```

**Comment by Weimc-w** [comment]
> 
> 
> According [admin api doc](https://github.com/apache/incubator-apisix/blob/master/doc/admin-api.md#service), You should specify property in your path.
> You can have a try for
> 
> ```shell
> curl --location --request PATCH 'http://127.0.01:9080/apisix/admin/services/5/desc' \
> --data-raw '"pathTest"'
> 
> curl --location --request PATCH 'http://127.0.01:9080/apisix/admin/services/5/upstream_id' \
> --data-raw '"1"'
> ```

指定具体属性是可以使用的，但是这样会有个缺陷就是通过java项目配置的时候就需要传递一堆不同的参数来达到修改部分配置的需求。期望是通过java调用的时候能够传递进去一个实体类对象，然后将实体类中有赋值的配置改变，没赋值的配置保持不变

**Comment by moonming** [comment]
> > According [admin api doc](https://github.com/apache/incubator-apisix/blob/master/doc/admin-api.md#service), You should specify property in your path.
> > You can have a try for
> > ```shell
> > curl --location --request PATCH 'http://127.0.01:9080/apisix/admin/services/5/desc' \
> > --data-raw '"pathTest"'
> > 
> > curl --location --request PATCH 'http://127.0.01:9080/apisix/admin/services/5/upstream_id' \
> > --data-raw '"1"'
> > ```
> 
> 指定具体属性是可以使用的，但是这样会有个缺陷就是通过java项目配置的时候就需要传递一堆不同的参数来达到修改部分配置的需求。期望是通过java调用的时候能够传递进去一个实体类对象，然后将实体类中有赋值的配置改变，没赋值的配置保持不变

not support this feature yet, and welcome PR.

**Comment by membphis** [comment]
I think we can implement it with this way, here is the mail list: https://lists.apache.org/thread.html/99ad8c5fa9f9ff9779cdb226b1ec41fc29c1bef62876f3872680d70f%40%3Cdev.apisix.apache.org%3E

@nic-chen do you have time to take a look at this PR?
