### ISSUE TITLE
request help: install-dependencies.md need Chinese ver

### ISSUE THREAD

**Issue by Miss-you** [apache/incubator-apisix#1513]
### Issue description
https://github.com/apache/incubator-apisix/blob/master/doc/install-dependencies.md

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by CGerAJ** [comment]
What's wrong with you？
You can view git history for help.

**Comment by moonming** [comment]
@Miss-you do you mean we need to add Chinease doc for https://github.com/apache/incubator-apisix/blob/master/doc/install-dependencies.md?

**Comment by Miss-you** [comment]
Yes, I think the Chinese version of the APISIX dependent environment installation guide is necessary.
This document is called install-dependencies-cn.md
