### ISSUE TITLE
bug:  apisix/prometheus/metrics  will be affected by other global_rules

### ISSUE THREAD

**Issue by OnlyPiglet** [apache/incubator-apisix#1516]
### Issue description
apisix/prometheus/metrics  will be affected by other global_rules,this will  make the collection of prometheus failed

### Environment

* apisix version (cmd: `apisix version`): apisix v1.1
* OS: centos7

### What's the expected result?
we may need to make the standalone location of apisix/prometheus/metrics for isolation

**Comment by spacewander** [comment]
What global rule you use affects the `apisix/prometheus/metrics`? Maybe we can solve the problem without making `global rule` not global.

**Comment by OnlyPiglet** [comment]
something like basic-auth or other limit-count which will be make effect about the access of location

**Comment by OnlyPiglet** [comment]
> What global rule you use affects the `apisix/prometheus/metrics`? Maybe we can solve the problem without making `global rule` not global.
something like basic-auth or other limit-count which will be make effect about the access of location

**Comment by spacewander** [comment]
I think normally limit-count plugin will not limit Prometheus since it accesses the metrics per-minute.
As for basic-auth, Prometheus can be configured to use basic auth: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config.

IMHO, it is not a good idea to open a backdoor for some endpoints.
@moonming @membphis 
What about your opinion?

**Comment by OnlyPiglet** [comment]
> I think normally limit-count plugin will not limit Prometheus since it accesses the metrics per-minute.
> As for basic-auth, Prometheus can be configured to use basic auth: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config.
> 
> IMHO, it is not a good idea to open a backdoor for some endpoints.
> @moonming @membphis
> What about your opinion?

I just make some example there are more plugins besides  limit-count and basic_auth,I don't think it's a good idea to solve one by one,thanks a lot

**Comment by spacewander** [comment]
If you protect apisix with a Role-based access control plugin in global scope, and the global scope doesn't contain `/metrics`, the API will be your Achilles' heel.
If a plugin can not be applied globally, it should not be applied globally. It would be better than modifying the definition of 'global' to make a plugin globally available.

**Comment by OnlyPiglet** [comment]
> If you protect apisix with a Role-based access control plugin in global scope, and the global scope doesn't contain `/metrics`, the API will be your Achilles' heel.
> If a plugin can not be applied globally, it should not be applied globally. It would be better than modifying the definition of 'global' to make a plugin globally available.

maybe you are right,I will think twice about this choice
