### ISSUE TITLE
change: `Batch_Processor` -> `batch_processor` (name style)

### ISSUE THREAD

**Issue by membphis** [apache/incubator-apisix#1522]
https://github.com/apache/incubator-apisix/blob/614f6a756387c6cbc3c3d3aa7959537091871d01/apisix/utils/batch-processor.lua#L106

and we need to fix the other similar points.

**Comment by sshniro** [comment]
Will update this after the merge of this PR:
https://github.com/apache/incubator-apisix/pull/1525

**Comment by membphis** [comment]
@sshniro any news?

**Comment by sshniro** [comment]
Will fix this during this week, got the OS corrupted need to reconfigure.

**Comment by membphis** [comment]
many thx @sshniro
