### ISSUE TITLE
request help: can proxy-cache plugins work with content_by_lua 

### ISSUE THREAD

**Issue by espider** [apache/incubator-apisix#1537]
### Issue description

I want to write lua code with content_by_lua like ngx.say('xxx'); 
can proxy-cache plugins  work on this case? without any upstrem 
### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by spacewander** [comment]
No. The proxy handler is also in the content phase too. There is only handler allowed in the content phase.

**Comment by espider** [comment]
> No. The proxy handler is also in the content phase too. There is only one handler allowed in the content phase.

thanks.
