### ISSUE TITLE
The custom plug-in returns the result garbled

### ISSUE THREAD

**Issue by griffenliu** [apache/incubator-apisix#1559]
### code:
```
function _M.access(conf, ctx)
    ...
    log.warn(">>>>>>>>>>>>>>>>>>", data)
    local accept_type = ngx.req.get_headers()["Accept"]
    if str_contains(accept_type, "text/html") then
        return 200, data
    else
        return 200, decode(data)
    end
end
```
> The data comes from the cache

### log:
```
2020/05/09 10:55:59 [warn] 23640#0: *812 [lua] dfy-cache-plugin.lua:380: phase_fun(): >>>>>>>>>>>>>>>>>>{"data":"测试服务器8001"}
, client: 172.30.212.72, server: , request: "GET /read?_YCD_={%22read%22:%20[%2211111111111%22]} HTTP/1.1", host: "172.30.212.72:9080"
```

### result:
```
{"data":"æµ‹è¯•æœåŠ¡å™¨8001"}
```

I think the reason is that the encoding is not configured in nginx.conf. Can we add utf-8 encoding into it or specify the encoding through configuration?

**Comment by moonming** [comment]
> I think the reason is that the encoding is not configured in nginx.conf.

can you show a example? I don't konw how to add utf-8 encoding in nginx.conf.

**Comment by griffenliu** [comment]
http {
    include       mime.types;
    default_type  text/html;
    **charset utf8;**
}

**Comment by moonming** [comment]
got it. welcome pr

SuperWalle <notifications@github.com> 于 2020年5月11日周一 下午3:15写道：

**Comment by xxm404** [comment]
Can I modify APISIX Nginx template can solve this problem

**Comment by moonming** [comment]
sure, you can modify `bin/apisix` to fix it. And please add test cases for
it.

Thanks,
Ming Wen
Twitter: _WenMing


xxm404 <notifications@github.com> 于2020年5月12日周二 下午5:55写道：

**Comment by xxm404** [comment]
ok please assign this issue to me.

**Comment by xxm404** [comment]
Add `charset utf-8;` to APISIX Nginx template
![image](https://user-images.githubusercontent.com/46340314/81796472-0efb0980-9540-11ea-9077-606635222bbc.png)
Modify example-plugin to test
![image](https://user-images.githubusercontent.com/46340314/81797084-e4f61700-9540-11ea-97c4-d41f705983dc.png)
restart apisix and execute `curl -i 127.0.0.1:9080/api/bench/testSimple` It still garbled
![image](https://user-images.githubusercontent.com/46340314/81797185-06570300-9541-11ea-9e4a-b2307d1fc38f.png)

**Comment by xxm404** [comment]
Hi @griffenliu can you give me a minimal reproducible example, I can not reproducible this problem
In my test, the response normally

my test code
```
function _M.access(conf, ctx)
    -- core.log.warn("plugin access phase, conf : ", core.json.encode(conf))
    -- return 200, core.json.decode(data)
    local redis = redis_new()
    local ok, err = redis:connect('127.0.0.1', 6379)
    if not ok then
        return false, err
    end
    local data = redis:get('data')
    core.log.warn(">>>>>>>>>>>>>>>", data)
    return 200, core.json.decode(data)
end
```
log
```
2020/05/14 13:02:55 [warn] 17681#17681: *332 [lua] example-plugin.lua:70: phase_fun(): >>>>>>>>>>>>>>>{"data":"测试服务器8001"}, client: 127.0.0.1, server: , request: "GET /api/bench/testSimple HTTP/1.1", host: "127.0.0.1:9080"
```
response
```
HTTP/1.1 200 OK
Date: Thu, 14 May 2020 13:04:23 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
Server: APISIX web server

{"data":"测试服务器8001"}
```

**Comment by griffenliu** [comment]
sorry, I'm late. There is no problem with your example, which is the same as mine. The encoding was normal when I used curl to test, but it was garbled when I used the browser.

  Using the browser response results below, you can see the difference between a correct response and an error response: 
```
＃ this is garbled response
Connection: keep-alive
Content-Type: text/plain
Date: Mon, 18 May 2020 09:53:34 GMT
Server: APISIX web server
Transfer-Encoding: chunked
```
```
# this is normal response,  Content-Type with encoding: charset=utf8.
Connection: keep-alive
Content-Type: text/plain; charset=utf8
Date: Mon, 18 May 2020 09:55:06 GMT
Server: APISIX web server
Transfer-Encoding: chunked
```

**Comment by griffenliu** [comment]
> Hi @griffenliu can you give me a minimal reproducible example, I can not reproduce this problem
> In my test, the response normally
> 
> my test code
> 
> ```
> function _M.access(conf, ctx)
>     -- core.log.warn("plugin access phase, conf : ", core.json.encode(conf))
>     -- return 200, core.json.decode(data)
>     local redis = redis_new()
>     local ok, err = redis:connect('127.0.0.1', 6379)
>     if not ok then
>         return false, err
>     end
>     local data = redis:get('data')
>     core.log.warn(">>>>>>>>>>>>>>>", data)
>     return 200, core.json.decode(data)
> end
> ```
> 
> log
> 
> ```
> 2020/05/14 13:02:55 [warn] 17681#17681: *332 [lua] example-plugin.lua:70: phase_fun(): >>>>>>>>>>>>>>>{"data":"测试服务器8001"}, client: 127.0.0.1, server: , request: "GET /api/bench/testSimple HTTP/1.1", host: "127.0.0.1:9080"
> ```
> 
> response
> 
> ```
> HTTP/1.1 200 OK
> Date: Thu, 14 May 2020 13:04:23 GMT
> Content-Type: text/plain
> Transfer-Encoding: chunked
> Connection: keep-alive
> Server: APISIX web server
> 
> {"data":"测试服务器8001"}
> ```
Thanks for helping me solve my problem :)
