### ISSUE TITLE
bug: etcd cluster,multiply host support with error logs

### ISSUE THREAD

**Issue by wwd5613** [apache/incubator-apisix#1560]
### Issue description

etcd cluster configure,set host with multipy host (more then 1),like : 

```
etcd:
  host:
    - "http://172.28.72.12:2379"
    - "http://172.28.72.13:2379"
    - "http://172.28.72.14:2379"
```

in runtime, error log output at regular time. as
![image](https://user-images.githubusercontent.com/2143396/81463927-09c05680-91f0-11ea-96e0-8db2d7a0556b.png)

**Comment by totemofwolf** [comment]
Please supply the etcd version and cluster config，a detailed reproduction method is welcome ;)

**Comment by presoulgo** [comment]
遇到相同问题，
**![etcd.png](https://i.loli.net/2020/05/14/jPH6ZqQpDgz5eJh.png)**

**Comment by moonming** [comment]
@membphis please take a look

**Comment by membphis** [comment]
those logs that contain `timeout` are fine. you can ignore them.

I have created an issue at `lua-resty-etcd`:
https://github.com/api7/lua-resty-etcd/issues/60

**Comment by membphis** [comment]
fixed: https://github.com/apache/incubator-apisix/commit/7d78a7ee466a382825687045a7c109c131a8c26c#diff-bf46fe686e25c7dc3c68232139b802e1
