### ISSUE TITLE
doc: http logger (Chinese)

### ISSUE THREAD

**Issue by sshniro** [apache/incubator-apisix#1562]
### Issue description
The English version is available here.
https://github.com/apache/incubator-apisix/blob/master/doc/plugins/http-logger.md

**Comment by hiproz** [comment]
i can try this

**Comment by sshniro** [comment]
If possible please also remove the `,` at the end of the `uri` :)

```bash
"plugins": {
            "http-logger": {
                 "uri": "127.0.0.1:80/postendpoint?param=1",
            }
       },
```

**Comment by scaat** [comment]
I have added Chinese documents，and remove the `,`.

**Comment by hiproz** [comment]
good job @scaat ,this issue can be closed after the confirm @membphis
