### ISSUE TITLE
the buffer for access log is too large

### ISSUE THREAD

**Issue by spacewander** [apache/incubator-apisix#1567]
Currently we configure the buffer of the access log like this:

```
    access_log {* http.access_log *} main buffer=32768 flush=3;
```

According to Nginx's doc:
> The buffer size must not exceed the size of an atomic write to a disk file

http://nginx.org/en/docs/http/ngx_http_log_module.html

And for Linux, the default atomic write size is `PIPE_BUF` (4096), see `man 7 pipe`.

Therefore, the default size is too large to be safe.

**Comment by Miss-you** [comment]
+1
A log buffer that is too small is not good, 4096 is more appropriate.

![image](https://user-images.githubusercontent.com/3816205/81525980-f268a100-9388-11ea-8bb0-8fcf8e8d01ac.png)

**Comment by Miss-you** [comment]
On the other hand, is `flush=1` better?
Since the log buffer is lowered, the flush time should also be lowered.

**Comment by Miss-you** [comment]
https://github.com/apache/incubator-apisix/pull/1570
