### ISSUE TITLE
bug: cannot open the white paper written in README.md

### ISSUE THREAD

**Issue by panhow** [apache/incubator-apisix#1580]
### Issue description
cannot open the white paper written in README.md
https://github.com/apache/incubator-apisix/blob/master/README.md#L42

**Comment by membphis** [comment]
many thanks for your report

**Comment by membphis** [comment]
I have uploaded the file and here is the new link. welcome PR to fix this bug completely.

Chinese new link: 

https://static.apiseven.com/2020/05/1589275281-企业用户如何选择微服务-API-网关.pdf

English new link:

https://static.apiseven.com/2020/05/1589275276-Choosing-the-Right-Microservice-API-Gateway-for-the-Enterprise-User.pdf

**Comment by hiproz** [comment]
i can try it

**Comment by hiproz** [comment]
i have give a pr of  this: #1582
