### ISSUE TITLE
bug: the httpc:request_uri of skywalking plugin in the file of client.lua can't do work.

### ISSUE THREAD

**Issue by cyxinda** [apache/incubator-apisix#1602]
@moonming 
### Issue description
When I used skywalking plugin , the function of httpc:request_uri  in the file of client.lua can't do work,which is in the line 39.
The code pic as follow:
![image](https://user-images.githubusercontent.com/7237898/82518363-cea81680-9b51-11ea-8358-b6b6739a70d4.png)

### Environment

* apisix version (cmd: `apisix version`): the combined version of apache:master and moonming:skywalking
* OS: centos7.5
* the skywalking server version is 7.0

### Minimal test code / Steps to reproduce the issue
1.I add some code to print the log as follow:
![image](https://user-images.githubusercontent.com/7237898/82518628-5ee65b80-9b52-11ea-9094-c9f860875599.png)
the log is :
![image](https://user-images.githubusercontent.com/7237898/82518719-8e956380-9b52-11ea-9991-3cee9fc0b873.png)
![image](https://user-images.githubusercontent.com/7237898/82518748-9ce37f80-9b52-11ea-9830-2303ee726cac.png)

2. I capture the package using the command `tcpdump -tttt -s0 -X -vv tcp port 12800 -w result.log ` 
the result is as follow:
![image](https://user-images.githubusercontent.com/7237898/82521082-46793f80-9b58-11ea-9938-2f5901717af9.png)
3. In the same apisix server machine ,I use the tool of  curl to connect to the same skywalking server,with the same params as the 1 step,it works.
` curl -L -X POST 'http://10.110.149.175:12800/v2/service/register' -H 'User-Agent: lua-resty-http/0.14 (Lua) ngx_lua/10015' -H 'Content-Length: 63' -H 'Host: 10.110.149.175:12800' -d '{"services":[{"type":"normal","serviceName":"UUID_SERVICE_1"}]}'
`
![image](https://user-images.githubusercontent.com/7237898/82519061-5b070900-9b53-11ea-9945-b394de799dc2.png)
4.Again,I try the test example with postman in my windows machine,It also works .
![image](https://user-images.githubusercontent.com/7237898/82519159-9a355a00-9b53-11ea-9b04-ca01e4eb3e8f.png)

### What's the actual result? (including assertion message & call stack if applicable)
the result variables of res  is nil ,the err is nil ,too .

### What's the expected result?
as the skywalking api ,the result should be like:
`[
    {
        "key": "UUID_SERVICE_1",
        "value": 2
    }
]
`

**Comment by moonming** [comment]
@cyxinda Is this bug fixed?
