### ISSUE TITLE
request help: dashboard page return 403

### ISSUE THREAD

**Issue by cindyliu-tec** [apache/incubator-apisix#1613]
### Issue description
I install apisix via docker image, follow the document steps, its quite smoothly, but when i try to view dashboard, it returns 403. 
![image](https://user-images.githubusercontent.com/56294517/82857938-0265b080-9f45-11ea-98c3-4f722280b4eb.png)

then i try to modify config.yaml file allow_admin param，but it still does'nt work. I'm wondering what's the problem, please help me.

![image](https://user-images.githubusercontent.com/56294517/82858064-62f4ed80-9f45-11ea-864a-3c813784727c.png)

### Environment

* apisix version (cmd: `apisix version`):
* OS:macOS、docker

**Comment by cindyliu-tec** [comment]
An other problem, I also try to install via source code, is hard to install luarocks dependencies in china, i have never succeed even one time, it get stuck there, it's there any solution?
![image](https://user-images.githubusercontent.com/56294517/82859028-25459400-9f48-11ea-8671-613738d81d84.png)

**Comment by juzhiyuan** [comment]
> ### Issue description
> I install apisix via docker image, follow the document steps, its quite smoothly, but when i try to view dashboard, it returns 403.
> ![image](https://user-images.githubusercontent.com/56294517/82857938-0265b080-9f45-11ea-98c3-4f722280b4eb.png)
> 
> then i try to modify config.yaml file allow_admin param，but it still does'nt work. I'm wondering what's the problem, please help me.
> 
> ![image](https://user-images.githubusercontent.com/56294517/82858064-62f4ed80-9f45-11ea-864a-3c813784727c.png)
> 
> ### Environment
> * apisix version (cmd: `apisix version`):
> * OS:macOS、docker

hi @totemofwolf Could you please help him to deal with the 403 error?

**Comment by houshunwei** [comment]
> > ### Issue description
> > I install apisix via docker image, follow the document steps, its quite smoothly, but when i try to view dashboard, it returns 403.
> > ![image](https://user-images.githubusercontent.com/56294517/82857938-0265b080-9f45-11ea-98c3-4f722280b4eb.png)
> > then i try to modify config.yaml file allow_admin param，but it still does'nt work. I'm wondering what's the problem, please help me.
> > ![image](https://user-images.githubusercontent.com/56294517/82858064-62f4ed80-9f45-11ea-864a-3c813784727c.png)
> > ### Environment
> > 
> > * apisix version (cmd: `apisix version`):
> > * OS:macOS、docker
> 
> hi @totemofwolf Could you please help him to deal with the 403 error?

if you use docker-compose guide, you need add 
172.18.0.1/24
to allow_admin.
because  docker-compose create a new docker network with 172.18.xx.xx. your host machine will be the first IP: 172.18.0.1

**Comment by membphis** [comment]
@cindyliu-tec close this pr first. if you still have a problem, you can reopen it.
