### ISSUE TITLE
bugfix(prometheus): the `overhead` should use millisecond units, so it needs to be multiplied by 1000

### ISSUE THREAD

**Issue by membphis** [apache/incubator-apisix#1615]
The statistics should use millisecond units, so it needs to be multiplied by 1000.

https://github.com/apache/incubator-apisix/blob/master/apisix/plugins/prometheus/exporter.lua#L113

```lua
    overhead = overhead - tonumber(ctx.var.upstream_response_time)
    overhead = overhead * 1000
```

**Comment by dabue** [comment]
I wanna fix it.

**Comment by JanLi-air** [comment]
overhead already has 1000 multiplied, this should be 
`overhead = overhead - tonumber(ctx.var.upstream_response_time) * 1000`

**Comment by membphis** [comment]
@JanLi-air many thx, your way is right. I was wrong
