### ISSUE TITLE
bug: Document description does not match source code

### ISSUE THREAD

**Issue by xxm404** [apache/incubator-apisix#1627]
### Issue description
The limit-count plugin document description for `rejected_code` does not match source code 
In document the rejected_code are optional, in source code the rejected_code are required
Source code:
![image](https://user-images.githubusercontent.com/46340314/83240951-b2008400-a1cc-11ea-8d82-6628f4f89977.png)
Document:
![image](https://user-images.githubusercontent.com/46340314/83241023-cfcde900-a1cc-11ea-9d3d-c619894686bd.png)
I can create PR to fix it, should i modify the document or source code
### Environment

* apisix version (cmd: `apisix version`): 1.2
* OS: ununtu 14.04

### What's the expected result?
Document should match the source code

**Comment by membphis** [comment]
welcome PR

**Comment by xxm404** [comment]
Hi @membphis Should I modify the document to fix it or source code to fix it?

**Comment by membphis** [comment]
fix the document is better. Make it behave the same as the source code.
