### ISSUE TITLE
request help: 修改默认端口为80以及443后访问报错401

### ISSUE THREAD

**Issue by jevic** [apache/incubator-apisix#1633]
### Issue description
修改默认端口 9080 9443 为80 443 端口后;访问报错,不修改则正常;

### Environment

* apisix version (cmd: `apisix version`): 1.3
* OS: centos7.6
详细报错如下: 
![image](https://user-images.githubusercontent.com/15863939/83368915-1a2db080-a3ed-11ea-8876-f3172578f26f.png)

查看日志后发现报错为token 认证失败;(默认开启了token认证)
尝试将admin_key 注释掉之后才可以访问;
但是为什么改了端口后就无法认证通过了呢？

**Comment by ShiningRush** [comment]
Hi jevic, 
I did not reproduce your problem, if we set the admin key, apisix should always authenticate it no matter what port.
Can you post your config.yaml which cause error?

**Comment by jevic** [comment]
> Hi jevic,
> I did not reproduce your problem, if we set the admin key, apisix should always authenticate it no matter what port.
> Can you post your config.yaml which cause error?

I'll try redeploying; thank!
