### ISSUE TITLE
request help: how to use stream proxy?

### ISSUE THREAD

**Issue by TigerGxl** [apache/incubator-apisix#1641]
### Issue description
how to use stream proxy?
apisix privodes tcp/udp proxy, i want to try to proxy mysql or redis,but it's not work.
官方文档中简单描述了stream_routes的配置,参照文档启用了stream_proxy,并且在配置了stream_routes(这里不明白配置文件中stream_proxy的端口用处,重启后并没有监听端口,通过admin接口插入stream_routes的配置,后端为mysql和redis,不管代理端口是否和配置文件中stream_proxy的端口是否一致,都没有生效)
The following is my config and etcd data.

config.yaml:

stream_proxy: # TCP/UDP proxy
tcp: # TCP proxy address list
- 9100
udp: # UDP proxy address list
- 9200

etcd中/apisix/stream_routes/xxxx 配置
curl http://127.0.0.1:9180/apisix/admin/stream_routes -X POST -d '
{
    "server_addr": "172.17.41.126",
    "server_port": 2000,
    "upstream": {
        "nodes": {
            "127.0.0.1:3306": 1
        },
        "type": "roundrobin"
    }
}'

curl http://127.0.0.1:9180/apisix/admin/stream_routes -X POST -d '
{
    "server_addr": "172.17.41.126",
    "server_port": 9100,
    "upstream": {
        "nodes": {
            "127.0.0.1:6379": 1
        },
        "type": "roundrobin"
    }
}'

### Environment

* apisix version (cmd: `apisix version`): 1.1
* OS: centos7

**Comment by TigerGxl** [comment]
...1.1版本有问题,升了就好了

**Comment by huzhewei** [comment]
端口是不是必须与tcp:9100保持一致才可以生效? @TigerGxl
