### ISSUE TITLE
request help: How to validate request in APISIX 

### ISSUE THREAD

**Issue by sshniro** [apache/incubator-apisix#1643]
### Issue description
I would like to validate requests before sending to up-streams, for example:

```
header_data = {
  auth_header = {required, type = 'string'}
}
body_data = {
  payload_1 = {required, type = 'boolean'},
  payload_2 = {optional}
}
```

**Comment by moonming** [comment]
@membphis can json-schema do this job?

**Comment by membphis** [comment]
`json-schema` is powerful enough for this feature.

**Comment by sshniro** [comment]
Thanks, I have created a request validator plugin using the JSON schema validator. Please do have a look.
