### ISSUE TITLE
request help: `Key not found` error calling the Admin API

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/incubator-apisix#1662]
### Issue description
When following the build documentation [how-to-build](https://github.com/apache/incubator-apisix/blob/master/doc/how-to-build.md) and build APISIX from source, I come into error when calling the admin API with default settings. 

To call admin API, I do
`curl http://127.0.0.1:9080/apisix/admin/routes?api_key=edd1c9f034335f136f87ad84b625c8f1-i` from how-to-build and 
`curl "http://127.0.0.1:9080/apisix/admin/services/" -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'` from [getting-started](https://github.com/apache/incubator-apisix/blob/master/doc/getting-started.md).

The error would be the following seperately.
```
HTTP/1.1 404 Not Found
Date: Sun, 07 Jun 2020 03:15:25 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: *
Access-Control-Max-Age: 3600
Server: APISIX web server

{"cause":"\/apisix","index":3,"errorCode":100,"message":"Key not found"}
```
```
{"cause":"\/apisix","index":3,"errorCode":100,"message":"Key not found"}
```

Since the wrong-key error would be `401 Unauthorized`, I'm not sure which could cause this kind of error.

### Environment

* apisix version: v1.3
* OS: WSL2 / Ubuntu 18.04

**Comment by nic-chen** [comment]
It looks like apisix is ​​not connected to etcd, you could try to access etcd on the server where you install apisix. 

like:
`curl 127.0.0.1:2379/v2/keys`

Make sure to use the correct IP and port.

**Comment by nic-chen** [comment]
Btw, please check your gmail, I had send you a mail about Summer 2020. thanks.

**Comment by Yiyiyimu** [comment]
Thank you @nic-chen !

The IP and port are the same for my case, and the output of `curl 127.0.0.1:2379/v2/keys` is `{"action":"get","node":{"dir":true}}`. 

But the output of 
`curl http://127.0.0.1:2379/v2/keys/apisix/routes/?api_key=edd1c9f034335f136f87ad84b625c8f1 -i` 
still shows `key not found` error. It seems I still failed to connect to etcd.

Sorry for the late reply. I just send the email back.

**Comment by nic-chen** [comment]
> Thank you @nic-chen !
> 
> The IP and port are the same for my case, and the output of `curl 127.0.0.1:2379/v2/keys` is `{"action":"get","node":{"dir":true}}`.
> 
> But the output of
> `curl http://127.0.0.1:2379/v2/keys/apisix/routes/?api_key=edd1c9f034335f136f87ad84b625c8f1 -i`
> still shows `key not found` error. It seems I still failed to connect to etcd.
> 
> Sorry for the late reply. I just send the email back.

you could try re-init:
```
make stop 
make init
make run
```
and then call admin API again.

**Comment by Yiyiyimu** [comment]
@nic-chen It works! Thank you!
