### ISSUE TITLE
bug: The Zipkin plugin used with the IP-restriction plugin was wrong

### ISSUE THREAD

**Issue by zjyang997** [apache/incubator-apisix#1675]
### Issue description
The Zipkin plugin used with the IP-restriction plugin was wrong

### Environment

* apisix version (cmd: `apisix version`):
* OS: V1.3

### Minimal test code / Steps to reproduce the issue
1. both the ip-restriction plugin and the zipkin plugin are enabled in a route
2. an error will be reported when using the IP in the blacklist to access the interface in the route

### What's the actual result? (including assertion message & call stack if applicable)
[error] 5427#5427: *1062 failed to run header_filter_by_lua*: /usr/local/apisix/apisix/plugins/zipkin.lua:171: attempt to index field 'proxy_span' (a nil value)
stack traceback:
![image](https://user-images.githubusercontent.com/57751233/84114748-792f9d00-aa5f-11ea-88c1-760f9b834d35.png)

**Comment by moonming** [comment]
@zjyang997 Is there a reproduction step?

**Comment by zjyang997** [comment]
> @zjyang997 Is there a reproduction step?
issues has been rewritten

**Comment by membphis** [comment]
@moonming please confirm if this is a bug
