### ISSUE TITLE
bug: When the SkyWalking plug-in is enabled, apISIx reports an error, indicating a missing file. Where can I find the missing file resource?

### ISSUE THREAD

**Issue by zjyang997** [apache/incubator-apisix#1676]
### Issue description
When the SkyWalking plug-in is enabled, apISIx reports an error, indicating a missing file. Where can I find the missing file resource?

### Environment

* apisix version (cmd: `apisix version`):
* OS: V1.3

### Minimal test code / Steps to reproduce the issue
1.Introduce the Skywalking.Lua plug-in file
2.Introduce the skywalking folder and its files client.lua and tracer. Lua
3.apisix restart ==>log error

### What's the actual result? (including assertion message & call stack if applicable)
[error] 5498#5498: *2 [lua] plugin.lua:66: load_plugin(): failed to load plugin [skywalking] err: /usr/local/apisix/apisix/plugins/skywalking/client.lua:23: module 'skywalking.register' not found:
	no field package.preload['skywalking.register']
![image](https://user-images.githubusercontent.com/57751233/84115955-82216e00-aa61-11ea-83eb-053014c64e34.png)

**Comment by moonming** [comment]
you need install dependencies first https://github.com/apache/incubator-apisix/blob/master/rockspec/apisix-master-0.rockspec#L54
you can run `make deps` to fix it

**Comment by membphis** [comment]
we can close this issue
