### ISSUE TITLE
feature : OAuth Authorization plugin for Keycloak 

### ISSUE THREAD

**Issue by sshniro** [apache/incubator-apisix#1679]
### Issue description
[Keycloak](https://www.keycloak.org/) is an Identity Server from RedHad based on OAuth/OIDC. Keycloak provides a very powerful [policy engine](https://www.keycloak.org/docs/latest/authorization_services/index.html#_policy_overview) for Authorization. It can support Roles based, Attribute-based, and Dynamic authorization strategies. 

The following image shows how APISIX can be integrated with Keycloak Server.

![image](https://user-images.githubusercontent.com/13045528/84159205-180ec600-aa6d-11ea-941e-76a66ae35d0e.png)

The following is a [proposed schema](https://www.keycloak.org/docs/latest/authorization_services/index.html#_service_overview) for the authz-keycloak plugin:
```bash
curl http://127.0.0.1:9080/apisix/admin/routes/5  -X PUT -d '
{
    "uri": "/get",
    "host": "httpbin.org",
    "plugins": {
        "authz-keycloak": {
          "token_endpoint": "token_endpoint_url",
          "grant_type": "urn:ietf:params:oauth:grant-type:uma-ticket",
          "enforcement_policy": "Permissive OR Enforcing",
          "permissions": [{"resourse_name#scope_1_name"}, {{"resourse_name#scope_2_name"}}]
        }
    },
    "upstream_id": 50
}'
```
`Policy enforcing mode` will reject calls that do not have associated permissions and `Permissive enforcement policy` will allow the API call if no permission is tied with the resource/path.

It's not mandatory to provide the permissions but if not provided APISIX should call Keycloak twice to first identify the protected resource path and in the second call to evaluate the permissions.

I would like to contribute to this plugin and would like to hear the thoughts of the community.

**Comment by moonming** [comment]
LGTM
@chnliyong please take a look, thx

**Comment by chnliyong** [comment]
This looks like a subset of [PEP](https://www.keycloak.org/docs/latest/authorization_services/index.html#_enforcer_overview).

**Comment by chnliyong** [comment]
This looks like a subset of [PEP](https://www.keycloak.org/docs/latest/authorization_services/index.html#_enforcer_overview).

I fell little confused, what's the relationship of the `permissions` array  and the requested method+uri.

**Comment by sshniro** [comment]
Yes @chnliyong its a subset of PEP.

![image](https://user-images.githubusercontent.com/13045528/84575018-91c6ec80-adaa-11ea-94f6-662896c1aa1d.png)

In the official authorization adapter, you can define the scopes and paths for your endpoints and Keycloak internally makes these API calls to check if you have the permission to the required scope. Also, in the keycloak policy enforcer file you can opt-out to not to define the paths and the adapters does a lazy loading to fetch the matching paths and resources dynamically.

Therefore as the first implementation I propose to implement this by having the definitions of what is the resource and scope needed to access a route, and future enhancements would support lazy loading of paths and permissions.
