### ISSUE TITLE
change: use `config_util.iterate_values` to scan the items in etcd

### ISSUE THREAD

**Issue by membphis** [apache/incubator-apisix#1685]
https://github.com/apache/incubator-apisix/blob/master/apisix/http/router/radixtree_sni.lua#L42

change to this style:

https://github.com/apache/incubator-apisix/blob/master/apisix/init.lua#L270

**Comment by xxm404** [comment]
Hi @membphis is just replaced `ipairs` by `config_util.iterate_values` ?

**Comment by membphis** [comment]
yes
