### ISSUE TITLE
bug: 500 internal error after apisix reload

### ISSUE THREAD

**Issue by panhow** [apache/incubator-apisix#1688]
### Issue description
reload apisix while apisix proxy traffics, error logs shows:
```
stack traceback:
coroutine 0:
	/usr/local/apisix/lua/apisix.lua: in function 'http_access_phase'
	access_by_lua(apisix.conf:68):2: in main chunk, client: 11.10.10.3, server: , request: "GET /api/v1/healthy HTTP/1.0", host: "m.w.com"
2020/06/10 19:29:36 [error] 20161#0: *564604 lua entry thread aborted: runtime error: /usr/local/apisix/lua/apisix.lua:338: attempt to index local 'upstream' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/apisix/lua/apisix.lua: in function 'http_access_phase'
	access_by_lua(apisix.conf:68):2: in main chunk, client: 11.10.10.3, server: , request: "GET /api/v1/healthy HTTP/1.0", host: "m.w.com"
```

### Environment

* apisix version (cmd: `apisix version`): 1.3
* OS: centos

### Minimal test code / Steps to reproduce the issue
```shell
curl -XPUT 127.0.0.1:9080/apisix/admin/upstreams/00000000000000000011 -XPUT --data '{"enable_websocket":true,"nodes":{"10.100.2.66:31652":10,"10.100.2.68:30000":10},"hash_on":"vars","type":"roundrobin"}'
curl -XPUT 127.0.0.1:9080/apisix/admin/routes -XPOST --data '{"uri":"/testtestt","upstream_id":"00000000000000000011"}'
ab -n 1000000 -c 100 http://127.0.0.1:9080/testtestt
apisix reload
```

**Comment by moonming** [comment]
@panhow it's a TODO of Apache APISIX.
Apache APISIX will flush and fetch data again from etcd when reload, so there's going to be a very short period of time where the data is empty.

**Comment by membphis** [comment]
we can fix the `500` first

**Comment by Miss-you** [comment]
The reason is that the upstream object and the router object are loaded separately, and when APISIX is in the reloading, the route object requires to be loaded, but the upstream is not.

Therefore, there will be a short period of time when the router can match but the upstream information is nil, resulting in the return of the 500 error. Code.

**Comment by panhow** [comment]
it return not only 500 internal error, but also 404.the route object may not loaded also.
![image](https://user-images.githubusercontent.com/34205715/84471809-b04cbb00-acb8-11ea-8d4e-bd2f2b4e135b.png)


> The reason is that the upstream object and the router object are loaded separately, and when APISIX is in the reloading, the route object requires to be loaded, but the upstream is not.
> 
> Therefore, there will be a short period of time when the router can match but the upstream information is nil, resulting in the return of the 500 error code.

**Comment by membphis** [comment]
it has been fixed https://github.com/apache/incubator-apisix/blob/master/apisix/init.lua#L374-L378

then we can close this PR.
