### ISSUE TITLE
request help: how to custom apisix home directory

### ISSUE THREAD

**Issue by xxm404** [apache/incubator-apisix#1699]
### Issue description
apisix default home directory is /usr/local/apisix/,need sudo permission to install and run,how to custom apisix home directory?
### Environment

* apisix version (cmd: `apisix version`):1.3
* OS:linux

**Comment by moonming** [comment]
How did you install Apache APISIX?
you can add `--prefix` to custom home dir if you install using RPM

**Comment by xxm404** [comment]
Hi @moonming thanks for replying to my questions,I install APISIX by luarock,
`luarock install apisix --tree='/home/work/apisix'` it`s still error
![image](https://user-images.githubusercontent.com/46340314/84642465-180c3b80-af2f-11ea-981c-a07a19cd5bd4.png)

**Comment by membphis** [comment]
Do you want to customize the path in the production environment or the local development environment?

production environment: soft link is a good way. eg: /usr/local/apisix -> /home/work/apisix

**Comment by xxm404** [comment]
Hi @membphis thanks for replying, soft link solved my problem.
