### ISSUE TITLE
后台重定向后，地址端口没了

### ISSUE THREAD

**Issue by zhanghouwen** [apache/incubator-apisix#1702]
http://127.0.0.1:9080/A发送请求，后台重定向到B，浏览器地址变为了
http://127.0.0.1/B，端口没了，是怎么回事呢？

**Comment by membphis** [comment]
please provide how did you set the route, we need more information.
and some other information, eg: your apisix version

**Comment by membphis** [comment]
another one, please use English in public channel

**Comment by zhanghouwen** [comment]
Version 1.2 of ApisiX.
![图片](https://user-images.githubusercontent.com/51305974/84469574-f2bfc900-acb3-11ea-91d1-616541bb10ac.png)
