### ISSUE TITLE
request help: Support custom Nginx template

### ISSUE THREAD

**Issue by xxm404** [apache/incubator-apisix#1706]
### Issue description
we need to support user can custom Nginx template instead of modify source code

### Environment

* apisix version (cmd: `apisix version`):latest
* OS:linux

**Comment by membphis** [comment]
that is an old topic, Apache APISIX does not allow to support user define the configuration.

APISIX may be destroyed and APISIX may not work properly.

**Comment by moonming** [comment]
@xxm404 What configurations are you hoping to modify?
