### ISSUE TITLE
request help: add auth for etcd

### ISSUE THREAD

**Issue by moonming** [apache/incubator-apisix#1713]
https://github.com/api7/lua-resty-etcd/commit/7f95abff051308a75d251a98c4a50f8b095c0175 support etcd auth, do we need upgrade to etcd v3 first? @nic-chen

**Comment by membphis** [comment]
support etcd v3 is a big event. I hope we can start this step asap.

**Comment by shenal** [comment]
I can start working on this. But considering that V2-> V3 migration requires a data migration as well we might want to maintain these changes in a seperate branch. Any thoughts?

**Comment by membphis** [comment]
We are using `etcd v2` now.
If you want to do this job, you can only support auth for etcd v2.

support etcd v3, we discuss it here: https://github.com/apache/incubator-apisix/issues/1767

**Comment by membphis** [comment]
I think the hardest part of this work should be how to add test cases.
`test::nginx` is not very suitable for this case. @shenal

**Comment by shenal** [comment]
Ok thanks for the heads up
