### ISSUE TITLE
request help: plugin was unvalid

### ISSUE THREAD

**Issue by vimilai** [apache/incubator-apisix#1716]
### Issue description
我在用apisix的时候自定义编写了插件，但是插件不生效，烦请看下附件是我的配置cdd-radix.lua(在faq.zip) 是我的插件代码，请帮忙看下有什么问题,图在faq.zip里
环境 linux centos
安装方式 ： npm -ivh  apisix-1.3-0.el7.noarch.rpm     version1.3

**安装插件**
[faq.zip](https://github.com/apache/incubator-apisix/files/4779185/faq.zip)

1.在/usr/local/apisix/apisix/plugins 下面添加了 cdd-radix.lua 图一所示

2.在/usr/local/apisix/conf 下修改 config.yaml  图二所示添加- cdd-radix
**应用插件** 
curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/order-service",
    "plugins": {
        "cdd-radix": {
            "uri_prefix": "/order-service",
            "auth_uri": ["/order-service/refund/:refund/*"]
			}
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "192.168.124.1:11003": 1
        }
    }
}'
**返回 ：{"error_msg":"unknown plugin [cdd-radix]"}   另外apisix stop/reload/restart 都试了执行无效** 

### Environment

* apisix version (cmd: `apisix version`):1.3
* OS:centos7

**Comment by moonming** [comment]
@vimilai can you create a PR for this issue? We can see all the changes in this way. I don't see any problems from the issue description.

**Comment by vimilai** [comment]
sorry，I found  that the plugin start  has some error in error.log, So I  was rewrite the lua script,it's success,In additon ,the 'init()'  method was invalid? it's must be wrote 'init_worker()'?

**Comment by membphis** [comment]
> the 'init()' method was invalid?

please provide your case, you can create a PR for this case. I think we can close this issue first.
