### ISSUE TITLE
bug: limit-count plugin  threshold is not exceeded, but the request is limited

### ISSUE THREAD

**Issue by Donghui0** [apache/incubator-apisix#1737]
### Issue description
In my production environment, active limit-count plugin. config like this:
![image](https://user-images.githubusercontent.com/7134928/85103193-c9b1b200-b238-11ea-8230-202a5657b741.png)

But from the apisix nginx log, Only request once and be limited.
![image](https://user-images.githubusercontent.com/7134928/85104659-8b69c200-b23b-11ea-9fee-e83ed30caf5c.png)

### Environment

* apisix version (cmd: `apisix version`): 1.2
* OS: centos7.6

### What's the expected result?
If the number of requests is greater than the threshold, limit the current

**Comment by membphis** [comment]
@Donghui0 can you provide the route content with text model. I can not copy it directly.

Have you found a way to reproduce this bug?

**Comment by moonming** [comment]
@Donghui0 can not reproduced in my side.  
Can you provide reproduction steps?

**Comment by Donghui0** [comment]
In my production env,  total 117 routes.   basically, each route is configured with  limit-count plugin.
Whether there will be conflicts ?  
Or the current limit rule becomes a global limit rule for all routers ?

**Comment by Donghui0** [comment]
If a large number of routes use this plugin, do we need to increase PLUGIN_ITEMS_COUNT in lrucache.lua  ?

**Comment by moonming** [comment]
you can increase the size of shared dict: https://github.com/apache/incubator-apisix/blob/master/bin/apisix#L178, which is LRU.

**Comment by moonming** [comment]
> conflicts

No, it will not conflict

**Comment by moonming** [comment]
@Donghui0 fixed？
