### ISSUE TITLE
request help: openid-connect plugin with hydra not working as expected

### ISSUE THREAD

**Issue by wangxiaolong100** [apache/incubator-apisix#1741]
### Issue description
openid-connect can not block not active access token.

hydra introspect endpoint return

```
HTTP/1.1 200 OK
Content-Type: application/json
Date: Sat, 20 Jun 2020 03:05:56 GMT
Content-Length: 17

{"active":false}
```

plugin use respons body as X-Userinfo, but body actual mean access token is not active.

### Environment

* apisix version (cmd: `apisix version`): 1.3
* OS: Docker

**Comment by membphis** [comment]
@moonming please take a look at this issue, you may know this

**Comment by sshniro** [comment]
Similar issue with Keycloak as well, Keycloak yields 200 for invalid tokens and Open ID connect interprets in the wrong manner.
![image](https://user-images.githubusercontent.com/13045528/85202757-0cdb5600-b309-11ea-86d5-c1538107aedb.png)

**Comment by moonming** [comment]
https://github.com/zmartzone/lua-resty-openidc/blob/b9fd68e20da0429a9c5c3061a4d1fdce6c799423/lib/resty/openidc.lua#L1635 we need to add error check when call `function openidc.introspect(opts)`
