### ISSUE TITLE
request help: APISIX need support custom nginx conf template.

### ISSUE THREAD

**Issue by xxm404** [apache/incubator-apisix#1751]
### Issue description
Many users need a custom Nginx config file, but now most config only support to modify APISIX source code to complete, maybe APISIX needs support to require the Nginx template file, the user can custom Nginx config by modifying the Nginx template file.

### Environment

* apisix version (cmd: `apisix version`):1.3
* OS:Linux

**Comment by membphis** [comment]
the duplicated issue, we can talk about this feature here: https://github.com/apache/incubator-apisix/issues/1620
