### ISSUE TITLE
bug: 使用proxy-rewrite 插件添加regex_uri js报错

### ISSUE THREAD

**Issue by qianglu1989** [apache/incubator-apisix#1778]
### Issue description
 使用proxy-rewrite 插件添加regex_uri js报错
![image](https://user-images.githubusercontent.com/8486184/86072940-5f5d0500-bab5-11ea-9f75-318f7d1da35b.png)

### Environment

* apisix version (cmd: `apisix version`): 1.3
* OS:  linux

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by membphis** [comment]
you should report to https://github.com/apache/incubator-apisix-dashboard/issues

**Comment by membphis** [comment]
BTW, pls use English in public channel.
