### ISSUE TITLE
bug: The test case does not take into account tengine

### ISSUE THREAD

**Issue by wingsjj** [apache/incubator-apisix#1789]
### Issue description
When I tried to migrate CI from Travis to GitHub action, I found that this test case does not pass when using Tengine.
https://github.com/wingsjj/incubator-apisix/runs/824980221?check_suite_focus=true#step:6:130

### Environment

* apisix version (cmd: `apisix version`): 1.4
* OS: Ubuntu 18.04

### Minimal test code / Steps to reproduce the issue
1.https://github.com/wingsjj/incubator-apisix/runs/824980221?check_suite_focus=true#step:6:130
2.https://github.com/apache/incubator-apisix/blob/master/t/node/remote-addr-ipv6.t#L117

### What's the actual result? (including assertion message & call stack if applicable)
> Failed test 'TEST 4: IPv6 /hello - response_body - response is expected (repeated req 0, req 0)'
> at /home/runner/work/incubator-apisix/incubator-apisix/test-nginx/lib/Test/Nginx/Socket.pm line 1589.
> @@ -3,7 +3,7 @@
> received: HTTP/1.1 200 OK
>  received: Content-Type: text/plain
>  received: Connection: close
> -received: Server: openresty
> +received: Server: Tengine
>  received: 
>  received: hello world
>  failed to receive a line: closed [] 

> Test Summary Report
> -------------------
> t/node/remote-addr-ipv6.t            (Wstat: 256 Tests: 15 Failed: 1)
>   Failed test:  11
>   Non-zero exit status: 1
> Files=119, Tests=3969, 959 wallclock secs ( 0.95 usr  0.18 sys + 130.74 cusr 27.03 csys = 158.90 CPU)
> Result: FAIL
> ##[error]Process completed with exit code 1.

### What's the expected result?
Test case passed successfully.

**Comment by membphis** [comment]
you can update the test case if you need

**Comment by wingsjj** [comment]
I updated it.
https://github.com/wingsjj/incubator-apisix/blob/master/t/node/remote-addr-ipv6.t#L117

And test case passed successfully.
https://github.com/wingsjj/incubator-apisix/actions/runs/153889200

**Comment by membphis** [comment]
@wingsjj that is cool. welcome PR ^_^
