### ISSUE TITLE
change: if the dashboard is empty, got `{"error_msg":"failed to match any routes"}`

### ISSUE THREAD

**Issue by membphis** [apache/incubator-apisix#1794]
I think we should return `404` with `404 Not Found`, that is a better way.

here is the doc about `try_files`: 

`try_files file ... =code;`

http://nginx.org/en/docs/http/ngx_http_core_module.html#try_files

**Comment by membphis** [comment]
we need to update them.

https://github.com/apache/incubator-apisix/blob/master/bin/apisix#L326
https://github.com/apache/incubator-apisix/blob/master/bin/apisix#L396

**Comment by xxm404** [comment]
Hi @membphis you can assign this issue to me.
