### ISSUE TITLE
request help: how to rewrite query parameters using proxy-rewrite

### ISSUE THREAD

**Issue by zTrix** [apache/incubator-apisix#1801]
### Issue description

'?' symbol would be encoded to 0x3f when using proxy-rewrite directive. 

https://github.com/apache/incubator-apisix/blob/794b1eb65e01e0e15d3dcd9cf1f0d74166e9b246/apisix/plugins/proxy-rewrite.lua#L156

Is there any way to rewrite url to append some more query parameter to the original path?

It would be highly appreciated if rewriting query parameter could be supported like in nginx: https://serverfault.com/questions/311487/nginx-rewrite-append-a-parameter-at-the-end-of-an-url

### Environment

* apisix version (cmd: 1.3):
* OS: Linux

**Comment by membphis** [comment]
this should be a bug, we should only encode `uri`.

here is the fake code, welcome PR ^_^

```lua
local path, arg = split_uri(uri)
path = uri_safe_encode(path)
return path .. arg
```

**Comment by xxm404** [comment]
Hi @moonming you can assign this issue to me.
