### ISSUE TITLE
request help: Health Checks can support customized PORT ?

### ISSUE THREAD

**Issue by souzens** [apache/incubator-apisix#1811]
sometimes http work and health check  listen on different ports  ,

like spring boot cloud 
http api request works on 8080,
but actuator health works on 8888 port

so  a router config like :

```"checks": {
            "active": {
                "http_path": "/actuator/health",
                "port": "8888",
                "host": "test",
                "healthy": {
                    "interval": 2,
                    "successes": 1
                },
                "unhealthy": {
                    "interval": 1,
                    "http_failures": 2
                }
            },
            "passive": {
                "healthy": {
                    "http_statuses": [200],
                    "successes": 3
                },
                "unhealthy": {
                    "http_statuses": [503,404],
                    "http_failures": 3,
                    "tcp_failures": 3
                }
            }
```

i did not find any health port define in https://github.com/apache/incubator-apisix/blob/master/apisix/schema_def.lua#L81

is it  supported now ?

_Originally posted by @souzens in https://github.com/apache/incubator-apisix/issues/1809#issuecomment-654671064_

**Comment by membphis** [comment]
yes, we can support this feature. it seems useful.

**Comment by membphis** [comment]
welcome PR

**Comment by shuaijinchao** [comment]
I will deal with this problem.
