### ISSUE TITLE
request help: route+rewrite+multi-upstream

### ISSUE THREAD

**Issue by jackwoods** [apache/incubator-apisix#1821]
### Issue description
Ask for help, I have a detailed requirement:
**routing:** /search/api, 
**upstreams:** 10.10.10.1:8888, 10.10.10.2:8888,
**rewrite:** ["^/search/api(.*)$","$1"],
What is the best practice to do this?
Many thanks in advance!

### Environment

* apisix 1.3
* OS: alpine

**Comment by membphis** [comment]
please make a try:

```shell
curl -i http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/search/api*",
    "plugins": {
        "proxy-rewrite": {
            "regex_uri": ["^/search/api(.*)$","$1"]
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "10.10.10.1:8888": 1,
            "10.10.10.2:8888": 1
        }
    }
}'
```

**Comment by jackwoods** [comment]
I have a question about the route id, we always need to specified it? 
In the admin panel, if I create a route, then the id will be auto-generated.

**Comment by jackwoods** [comment]
The other question is: when proxy pass to upstream, some times we need to change the header host to the upstream host, seems not easy to do it.

**Comment by jackwoods** [comment]
The final question is, to make the upstream reusable, I'd better create an independent upstream, then change it in the admin panel?

**Comment by membphis** [comment]
> I have a question about the route id, we always need to specified it?
> In the admin panel, if I create a route, then the id will be auto-generated.

you can use `POST` method, same as Dashboard.

**Comment by membphis** [comment]
> The final question is, to make the upstream reusable, I'd better create an independent upstream, then change it in the admin panel?

you are right.
