### ISSUE TITLE
test: add test case about failed to find upstream by id

### ISSUE THREAD

**Issue by membphis** [apache/incubator-apisix#1827]
need to add test case about failed to find upstream by id:

https://github.com/apache/incubator-apisix/pull/1824/files#diff-d982d52466e7c93c7b604358339b2a29R320

we need to confirm it works fine.

**Comment by membphis** [comment]
@wrl96 do you want to fix this issue?

**Comment by wrl96** [comment]
test case already in route-upstream.t
it can't pass the test case if it doesn't work fine.
https://github.com/apache/incubator-apisix/pull/1824/checks?sha=fe1c4f1450c0e911e857a6c6c0a1ef2836755bc2

**Comment by membphis** [comment]
![image](https://user-images.githubusercontent.com/6814606/87147410-2dcb1180-c2df-11ea-925c-e163646da406.png)

I do not think we have added test cases for those codes.

**Comment by membphis** [comment]
we have covered this case. close this issue first
