### ISSUE TITLE
request help: Mac os can't start apisix 

### ISSUE THREAD

**Issue by nanwenbo** [apache/incubator-apisix#1831]
start apisix 

./bin/apisix start
nginx: [warn] could not build optimal variables_hash, you should increase either variables_hash_max_size: 1024 or variables_hash_bucket_size: 64; ignoring variables_hash_bucket_size

how can I fix it?

### Environment

* apisix version (cmd: `apisix version`):1.4
* OS:macos Mojave  10.14.6 (18G103)

**Comment by moonming** [comment]
This bug has been around since OpenResty version 1.17 and is myabe a issue of OpenResty or Nginx under mac

**Comment by moonming** [comment]
BTW,  is APISIX still can wroks well? I think warn level will not block start.

**Comment by membphis** [comment]
I think you make a try with older openresty

**Comment by nanwenbo** [comment]
> BTW, is APISIX still can wroks well? I think warn level will not block start.

apisix  is not work, i reinstall openresty 1.15.8.3  ,apisix is working now.

**Comment by membphis** [comment]
ok, we can close this issue
