### ISSUE TITLE
bug: should not save the runtime data of plugin into etcd

### ISSUE THREAD

**Issue by nic-chen** [apache/incubator-apisix#1836]
### Issue description

admin api will pollute and save plugin_conf into etcd when calling plugin's function check_schema.
e.g.  [https://github.com/apache/incubator-apisix/blob/master/apisix/plugins/proxy-rewrite.lua#L111](https://github.com/apache/incubator-apisix/blob/master/apisix/plugins/proxy-rewrite.lua#L111)

### Environment

* apisix version (cmd: `apisix version`): 1.4
* OS: centos7

### Minimal test code / Steps to reproduce the issue
1. add a route with plugin proxy_write
2. view the route just added

### What's the actual result? (including assertion message & call stack if applicable)

the runtime data of the plugin has be saved into etcd.

### What's the expected result?

the runtime data of the plugin should't be saved into etcd.

**Comment by membphis** [comment]
only `Admin API` has this bug.

**Comment by wrl96** [comment]
I think we should remove apisix.admin.plugins.check_schema, just check schema in sync_data

**Comment by membphis** [comment]
@wrl96 Your way is dangerous, we don't allow dirty data to be stored in etcd.

**Comment by membphis** [comment]
I will fix this bug
