### ISSUE TITLE
CI: allow osx system failure in Github Action

### ISSUE THREAD

**Issue by membphis** [apache/incubator-apisix#1837]
![image](https://user-images.githubusercontent.com/6814606/87292230-184e2580-c533-11ea-94d6-46425c770ea9.png)

@apache/apisix-committers what do you think about this change?

**Comment by membphis** [comment]
Whether in Travis or GitHub Action, the test case results in the OSX system are unstable :(

**Comment by sshniro** [comment]
+1

**Comment by membphis** [comment]
failed again:

![image](https://user-images.githubusercontent.com/6814606/87742051-88e99080-c818-11ea-8a96-5e7823cbd008.png)

**Comment by membphis** [comment]
fixed https://github.com/apache/incubator-apisix/pull/1860
