### ISSUE TITLE
request help: Local Test for Master Barnch Failed 26% Cases

### ISSUE THREAD

**Issue by mtx2d** [apache/incubator-apisix#1844]
### Issue description
I ran test locally against master branch, however too many tests failed.
I would expect master branch to have no test failure. 

```
Test Summary Report
-------------------
t/plugin/authz-keycloak.t            (Wstat: 2048 Tests: 24 Failed: 8)
  Failed tests:  13-15, 17-18, 22-24
  Non-zero exit status: 8
t/plugin/grpc-transcode.t            (Wstat: 4864 Tests: 48 Failed: 19)
  Failed tests:  7-15, 30-35, 39-41, 45
  Non-zero exit status: 19
t/plugin/limit-count-redis.t         (Wstat: 0 Tests: 69 Failed: 31)
  Failed tests:  10-15, 17, 19, 22-25, 29, 31, 34, 36-41
                43, 45, 48-51, 55, 57, 62-63
  Parse errors: No plan found in TAP output
t/discovery/eureka.t                 (Wstat: 0 Tests: 22 Failed: 10)
  Failed tests:  1-2, 8-10, 13-14, 20-22
  Parse errors: No plan found in TAP output
t/router/radixtree-sni.t             (Wstat: 2304 Tests: 80 Failed: 9)
  Failed tests:  9, 20, 28, 36, 42, 50, 58, 66, 72
  Non-zero exit status: 9
t/plugin/http-logger.t               (Wstat: 1024 Tests: 47 Failed: 4)
  Failed tests:  21, 27, 33, 41
  Non-zero exit status: 4
t/router/multi-ssl-certs.t           (Wstat: 768 Tests: 31 Failed: 3)
  Failed tests:  9, 18, 27
  Non-zero exit status: 3
Files=120, Tests=4022, 425 wallclock secs ( 1.37 usr  0.23 sys + 76.17 cusr 35.19 csys = 112.96 CPU)
Result: FAIL
Makefile:179: recipe for target 'test' failed
make: *** [test] Error 1
```

### Environment

* apisix version (cmd: `apisix version`): `1.4`
* OS: `Linux 2d-pc 5.3.0-62-generic #56~18.04.1-Ubuntu` 

This is the step I followed to setup the test env: 
```bash
# get source
$ git clone git@github.com:apache/incubator-apisix.git
$ cd incubator-apisix

# prepare runtime and start apisix process
$ etcd --enable-v2=true &
$ make init # create config files
$ make deps
$ make run

# install required test-nginx repo to sibling file path
$ git clone https://github.com/openresty/test-nginx.git ../test-nginx
# invoke the test in incurbator-apisix using `prove`
$ TEST_NGINX_BINARY=`which openresty` \
prove  -I./ -I../test-nginx/lib -I../test-nginx/inc -r ./t 
```
More details can be found here: https://mqiu.me/post/apisix-test-setup/

## What Do I Need Help With
How could master branch **fail 26%** of all tests, what should I do to **make my test setup correct**?

**Comment by moonming** [comment]
May I ask which specific test cases failed?
 Some tests rely on external services, such as grpc test, cluster rate limiting test, etc.

**Comment by mtx2d** [comment]
> May I ask which specific test cases failed?
> Some tests rely on external services, such as grpc test, cluster rate limiting test, etc.

Sure this is the full list: https://gist.github.com/mtx2d/b64a79afabf0186c979a24ca448bb7dc

**Comment by moonming** [comment]
Apache APISIX's CI need to install Lots of dependencies:
https://github.com/apache/incubator-apisix/blob/master/.travis/linux_openresty_runner.sh#L36

Most of these failed test cases are dependency problems

**Comment by mtx2d** [comment]
> Apache APISIX's CI need to install Lots of dependencies:
> https://github.com/apache/incubator-apisix/blob/master/.travis/linux_openresty_runner.sh#L36
> 
> Most of these failed test cases are dependency problems

Got it, I was still trying to figure out the correct workflow. 
Seems to me the right thing to do is to let CI handle all the tests.

**Comment by mtx2d** [comment]
I will close this. The recommended way to test is to file a PR and trigger CI to run full set of tests.
