### ISSUE TITLE
bug: Missing the CODE_STYLE.md file

### ISSUE THREAD

**Issue by yongboy** [apache/incubator-apisix#1846]
### Summary

I can't find the `CODE_STYLE.md` file in the project path：

```markdown
* [Code Style](../CODE_STYLE.md)
```

:((

**Comment by moonming** [comment]
The original code style was OpenResty and did not meet the branding requirements of Apache APISIX.
Feel free to modify the [original file](https://github.com/apache/incubator-apisix/blob/v1.2/CODE_STYLE.md) and submit a PR

**Comment by Miss-you** [comment]
I think it would be more appropriate to use this document as a code style guide.
https://github.com/luarocks/lua-style-guide

**Comment by Miss-you** [comment]
https://github.com/apache/incubator-apisix/pull/1848
