### ISSUE TITLE
request help: How to grayscale update the api configuration

### ISSUE THREAD

**Issue by Beckjiang** [apache/incubator-apisix#1850]
### Issue description
Does it now support grayscale update API configuration?

If it's not supported, what are the ideas to implement it?

**Comment by membphis** [comment]
please take a look at this document: https://github.com/apache/incubator-apisix/blob/master/FAQ.md#how-to-support-gray-release-via-apisix

if it is not powerful enough for you, please send us the way you want.

**Comment by Beckjiang** [comment]
looks good!

but in our system, there are no obvious parameters to distinguish requests. Is it possible to just configure the ratio to divide the requests to the new configuration?

**Comment by membphis** [comment]
you can take a look at this example, https://github.com/api7/lua-resty-radixtree#synopsis

I think it can help you.

**Comment by Beckjiang** [comment]
perfect. thx :)
