### ISSUE TITLE
bug: The recommended value for worker_shutdown_timeout is 240 seconds.

### ISSUE THREAD

**Issue by Miss-you** [apache/incubator-apisix#1853]
### Issue description

current
```
  worker_shutdown_timeout: 3s     # timeout for a graceful shutdown of worker processes
```
https://github.com/apache/incubator-apisix/blob/master/conf/config.yaml#L104

recommendation
```
  worker_shutdown_timeout: 240s     # timeout for a graceful shutdown of worker processes
```

reasons:
1. 3 seconds is too short, once a graceful restart will quickly disconnect the long connection
2. The default value for nginx ingress is 240 seconds.

![image](https://user-images.githubusercontent.com/3816205/87633173-76664d00-c76d-11ea-872e-000b5dbf87eb.png)

### Environment

* apisix version (cmd: `apisix version`):
* OS:

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by moonming** [comment]
@Miss-you agreed , welcome PR

**Comment by shuaijinchao** [comment]
the problem has been fixed, I will close this issue.
