### ISSUE TITLE
request help: How to separate apisix and user customize code?

### ISSUE THREAD

**Issue by UnderTreeTech** [apache/incubator-apisix#1865]
How to deploy apisix and user customize code separately in prod env? If we can deploy them in different ways, then apisix is transparent to user's logic code, we can upgrade apisix or logic code at any time.

**Comment by membphis** [comment]
> How to deploy apisix and user customize code separately in prod env

We always advise users that only the plug-in code is customized.

When you do upgrade, you can always use the latest APISIX core.
