### ISSUE TITLE
bug: failed to get `host` in health check configuration.

### ISSUE THREAD

**Issue by shuaijinchao** [apache/incubator-apisix#1869]
## code location
https://github.com/apache/incubator-apisix/blob/master/apisix/balancer.lua#L64
https://github.com/apache/incubator-apisix/blob/master/apisix/balancer.lua#L95
https://github.com/apache/incubator-apisix/blob/master/apisix/balancer.lua#L198
https://github.com/apache/incubator-apisix/blob/master/apisix/balancer.lua#L201
https://github.com/apache/incubator-apisix/blob/master/apisix/balancer.lua#L206
##
refer to the health check configuration:
https://github.com/apache/incubator-apisix/blob/master/doc/health-check.md
`host` should be from `checks.active.host` instead of `checks.host`

**Comment by membphis** [comment]
you are right, welcome PR to fix it

**Comment by shuaijinchao** [comment]
> you are right, welcome PR to fix it

OK
