### ISSUE TITLE
bug: ` make install ` did not install lua deps to apisix install dir

### ISSUE THREAD

**Issue by afghanistanyn** [apache/incubator-apisix#1895]
### Issue description
# apisix 
lua: /usr/bin/apisix:83: module 'tinyyaml' not found:
	no field package.preload['tinyyaml']
	no file '/usr/local/apisix/deps/share/lua/5.1/tinyyaml.lua'
	no file './tinyyaml.lua'
	no file '/usr/share/lua/5.1/tinyyaml.lua'
	no file '/usr/share/lua/5.1/tinyyaml/init.lua'
	no file '/usr/lib64/lua/5.1/tinyyaml.lua'
	no file '/usr/lib64/lua/5.1/tinyyaml/init.lua'
	no file '/usr/local/apisix/deps/lib64/lua/5.1/tinyyaml.so'
	no file '/usr/local/apisix/deps/lib/lua/5.1/tinyyaml.so'
	no file './tinyyaml.so'
	no file '/usr/lib64/lua/5.1/tinyyaml.so'
	no file '/usr/lib64/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/bin/apisix:83: in main chunk
	[C]: ?

### Environment

* apisix version : 1.4
* OS: CentOS Linux release 7.5.1804 (Core)
* luarocks: 3.3.1 
* openresty: openresty/1.17.8.2

### What's the expected result?

![图片](https://user-images.githubusercontent.com/5069076/88365750-945d2e80-cdb9-11ea-8a06-152f2400f8aa.png)

when i add `cp -r deps /usr/local/apisix/ ` into Makefile and run make install again , it works!

**Comment by moonming** [comment]
`make install` is a deprecated cmd.
