### ISSUE TITLE
Allow or Reject API calls based on arbitrary code execution

### ISSUE THREAD

**Issue by sshniro** [apache/incubator-apisix#1897]
Hello, I need to allow or reject API calls via performing a regex check on the request body. Is there a mechanism available in APISIX to do this? or should this be a custom plugin?

POST Data
```json
body:{
  "topic_name": "prefix_a"
}
```

APISIX Code
```lua
-- decode body
-- run regex on topic name
-- allow if it conforms to the regex pattern
```

**Comment by moonming** [comment]
it looks like a feature of WAF.
You can create a new plugin to parse post body, there's no mechanism in place to do this yet.

**Comment by sshniro** [comment]
Thanks, I was also going through the serverless plugin, is there a way this plugin can be modified to read the body and reject the calls @moonming ?

**Comment by moonming** [comment]
sure, it's a good way.

Thanks,
Ming Wen
Twitter: _WenMing


Nirojan Selvanathan <notifications@github.com> 于2020年7月24日周五 下午5:31写道：

**Comment by sshniro** [comment]
Thanks.
