### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Yangzcy423911** [apache/incubator-apisix#1898]
### Environment

* apisix version (cmd: `apisix version`):
* OS: 1.4

### Minimal test code / Steps to reproduce the issue
When creating a route, the route is created successfully. If the route is modified through the web page, an error is reported

### What's the actual result? (including assertion message & call stack if applicable)

![image](https://user-images.githubusercontent.com/26598793/88376088-566b0500-cdcf-11ea-9d8b-ff6ec40b8f0f.png)

![image](https://user-images.githubusercontent.com/26598793/88376244-93cf9280-cdcf-11ea-8c53-3c7e13fd8a1d.png)

### What's the expected result?
![image](https://user-images.githubusercontent.com/26598793/88375851-ea889c80-cdce-11ea-846d-fe85cb39c98c.png)

**Comment by moonming** [comment]
@gxthrj please take a look

**Comment by gxthrj** [comment]
ok, get it

**Comment by gxthrj** [comment]
@juzhiyuan please have a look, when `redirect` key should not be exist when disable redirection

**Comment by juzhiyuan** [comment]
1. Please make sure you are using the latest codes from master branch by `git pull`
2. It seems you are under development mode from your snapshot, if you are using the latest codes, then IT would be a bug on FE, we may need to check the transformer logic when update.

**Comment by Yangzcy423911** [comment]
Thank you for your answer
 At present, the latest master branch has been used. This problem has been solved, and a stable version of the front end is expected

**Comment by juzhiyuan** [comment]
OK, it looks like the problem has been resolved, feel free to reopen it if you find the related issue.
