### ISSUE TITLE
request help: what's the difference between conf and lru cache

### ISSUE THREAD

**Issue by UnderTreeTech** [apache/incubator-apisix#1899]
In most plugins, apisix use lru cache to store hot data. At the same time, in every plugin user can get config data through parameter conf. That make me confused, if conf can provide plugin global data, why apisix still choose lru to store global data? @membphis @moonming

**Comment by membphis** [comment]
The `conf` is the user's original configuration in etcd. We need to avoid modifying it. 
Keep to use it in a "read-only" way is safer.

**Comment by UnderTreeTech** [comment]
> The `conf` is the user's original configuration in etcd. We need to avoid modifying it. 
> Keep to use it in a "read-only" way is safer.

If my customize plugin only read the conf, can I use the conf directly? I think is more convenient.@membphis

**Comment by membphis** [comment]
of course, you can do in this way.

and we can close this issue.
