### ISSUE TITLE
bug: redirect plugin redirects all the time when https

### ISSUE THREAD

**Issue by ACanOfGas** [apache/incubator-apisix#1934]
### Issue description
redirect plugin redirects all the time when https
### Environment

* apisix version (cmd: `apisix version`): 1.4
* OS:centos8

### Minimal test code / Steps to reproduce the issue
1.api config redirects plugins
2.Triggers an http access and redirect to https
3.Subsequent https accesses are still being redirected

### What's the actual result? (including assertion message & call stack if applicable)

Subsequent https accesses are still being redirected
### What's the expected result?
https normal access

rediretc plugin modify conf.uri and  conf.ret_code, result in Subsequent access conf.uri and  conf.ret_code always not nil

**Comment by membphis** [comment]
please show us the how did you set the `redirect` plugin, we need to confirm.

**Comment by ACanOfGas** [comment]
{
    "redirect":{
        "http_to_https":true,
        "ret_code" : 302
    }
}

**Comment by ACanOfGas** [comment]
> please show us the how did you set the `redirect` plugin, we need to confirm.

{
    "redirect":{
        "http_to_https":true,
        "ret_code" : 302
    }
}

**Comment by membphis** [comment]
What is the way to enable this feature?

![image](https://user-images.githubusercontent.com/6814606/88996212-44351d80-d31f-11ea-8f23-6c710d22c9b1.png)

**Comment by membphis** [comment]
this should be a bug, will fix it as soon as possible.

**Comment by membphis** [comment]
@ACanOfGas please make a try with the master branch, we have fixed this issue.
