### ISSUE TITLE
分享本地docker开发环境Dockerfile

### ISSUE THREAD

**Issue by spjiang** [apache/incubator-apisix#1940]
FROM openresty/openresty:alpine-fat AS production-stage

ADD ./rockspec/apisix-master-0.rockspec /rockspec/apisix-master-0.rockspec
ADD ./apisix.zip /opt/api-gateway-core.zip
RUN set -x \
	&& /bin/sed -i 's,http://dl-cdn.alpinelinux.org,https://mirrors.aliyun.com,g' /etc/apk/repositories \
	&& apk add --no-cache --virtual .builddeps \
	automake \
	autoconf \
	libtool \
	pkgconfig \
	cmake \
	git \
	&& luarocks install /rockspec/apisix-master-0.rockspec --tree=/usr/local/apisix/deps \
	&& cp -v /usr/local/apisix/deps/lib/luarocks/rocks-5.1/apisix/master-0/bin/apisix /usr/bin/ \
	&& bin='#! /usr/local/openresty/luajit/bin/luajit\npackage.path = "/usr/local/apisix/?.lua;" .. package.path' \
	&& sed -i "1s@.*@$bin@" /usr/bin/apisix \
	&& mv /usr/local/apisix/deps/share/lua/5.1/apisix /usr/local/apisix \
	&& apk del .builddeps build-base make unzip

FROM alpine:3.11 AS last-stage

# add runtime for Apache APISIX
RUN set -x \
	&& /bin/sed -i 's,http://dl-cdn.alpinelinux.org,https://mirrors.aliyun.com,g' /etc/apk/repositories \
	&& apk add --no-cache bash libstdc++ curl

WORKDIR /usr/local/apisix

COPY --from=production-stage /usr/local/openresty/ /usr/local/openresty/
COPY --from=production-stage /usr/local/apisix/ /usr/local/apisix/
COPY --from=production-stage /usr/bin/apisix /usr/bin/apisix

ENV PATH=$PATH:/usr/local/openresty/luajit/bin:/usr/local/openresty/nginx/sbin:/usr/local/openresty/bin

EXPOSE 9080 9443

CMD ["sh", "-c", "/usr/bin/apisix init && /usr/bin/apisix init_etcd && /usr/local/openresty/bin/openresty -p /usr/local/apisix -g 'daemon off;'"]

STOPSIGNAL SIGQUIT

**Comment by membphis** [comment]
many thx for sharing your Dockerfile.

and we'd better use English in a public channel ^_^

**Comment by membphis** [comment]
if you have no issue, then we can close this issue first.

**Comment by moonming** [comment]
Apache APISIX has docker repo:https://github.com/apache/incubator-apisix-docker, welcome to contribute.
