### ISSUE TITLE
Support Centos6

### ISSUE THREAD

**Issue by whiteCcinn** [apache/incubator-apisix#218]
## Support Centos6

We hope to support centos6 and apisix to pass the official test in centos6

**Comment by wasabihu** [comment]
支持，我们这边的机器也有不少是Centos6 的

**Comment by moonming** [comment]
welcome PR:)
now `libr3` cannot compiled in ceontos 6:https://github.com/iresty/apisix/blob/master/doc/install-dependencies.md#centos-6

**Comment by moonming** [comment]
we removed lib3 and rapidjson from APISIX, so I think we can close this issue.

**Comment by membphis** [comment]
The current APISIX has supported CentOS 6 already.
