### ISSUE TITLE
Roadmap of Version 1.0

### ISSUE THREAD

**Issue by moonming** [apache/incubator-apisix#226]
APISIX 1.0 is an LTS(Long-term support) version, if you have any suggestions, please leave a message here.
- support YAML configure model, which is the best in k8s
- OAuth 2.0
- JWT: already done
- WebSocket
- GeoIP
- WAF plugin
- anti-cc plugin

**Comment by daiyoung** [comment]
既生瑜何生亮呢，You are making  a new Kong Api gateway, but I will also follow it.

**Comment by membphis** [comment]
old issue
