### ISSUE TITLE
discuss: work with consul

### ISSUE THREAD

**Issue by membphis** [apache/incubator-apisix#239]
https://www.consul.io/intro/vs/zookeeper.html

**Comment by soulsoul** [comment]
i think we should keep the data center open，design the unified interface，we can allow the 3rd product to access into。not only support  etcd, bust also like redis, zk,consul etc.

**Comment by vkill** [comment]
Maybe we should refer to [prometheus](https://prometheus.io/docs/prometheus/latest/storage/#remote-storage-integrations) .

Should user provide write url (http://127.0.0.1/9001/write) and read url(http://127.0.0.1/9001/read) and basic auth or key auth .

About etcd watch api, we can use Long Polling to replace it.

**Comment by wind-clothes** [comment]
I think we need to strip out related components and then open up scalability, such as synchronization components and storage components。

**Comment by moonming** [comment]
> I think we need to strip out related components and then open up scalability, such as synchronization components and storage components。

I have doubt about the need for such high flexibility, and what obvious benefits does this bring?

**Comment by membphis** [comment]
Apache APISIX can work with Consul DNS.
