### ISSUE TITLE
doc: generate a single document site, making reading documents easier

### ISSUE THREAD

**Issue by membphis** [apache/incubator-apisix#251]
![image](https://user-images.githubusercontent.com/6814606/61203469-087fe380-a71d-11e9-9dc8-15ef5dd184b3.png)

we can generated the site by the markdown in apisix.

Do you have any good suggestions?

**Comment by membphis** [comment]
ref question: https://github.com/Tencent/rapidjson/issues/1539

**Comment by soulsoul** [comment]
why not choose gitbook？

**Comment by membphis** [comment]
The GreatWall is very powerful, gitbook is not easy to open :(

**Comment by moonming** [comment]
added https://github.com/iresty/docs for that

**Comment by hiproz** [comment]
we can use the https://readthedocs.org/  free service , it can pull docs from our git repo,  so we can use our subdomain whith domain rename

**Comment by membphis** [comment]
yes, it seems very good `readthedocs.org`

**Comment by membphis** [comment]
resolved by PR https://github.com/apache/incubator-apisix/pull/1724
