### ISSUE TITLE
discuss:  Upstream server supports HTTPS protocol 

### ISSUE THREAD

**Issue by onlonely** [apache/incubator-apisix#298]
从源码中可以发现,目前上游服务器upstream是只支持http协议的

实际使用的时候可能还存在https协议的上游服务器..
更加麻烦的是https上游服务器可能必须校验证书.

所以这里讨论下到底要不要支持https协议的上游分发.或者多少人需求...

Upstream server only supports HTTP protocol now.

There may also be upstream servers of HTTPS protocol in actual use, and the upstream server of HTTPS may have to proofread the certificate.

So here we will discuss whether to support upstream with HTTPS protocol.

**Comment by membphis** [comment]
supported by this plugin: https://github.com/apache/incubator-apisix/blob/master/doc/plugins/proxy-rewrite.md#attributes
