### ISSUE TITLE
feature: support to use domain as upstream node

### ISSUE THREAD

**Issue by membphis** [apache/incubator-apisix#347]
the upstream node only supports IP address plus port now. We need to support to use domain, apisix will parse domain to IP address by DNS automaticly.

**Comment by Jacky2** [comment]
这当然是最好的，在k8s环境下这将起到很大的作用，因为可以使用k8s service name 去访问应用；
或者说在复杂的前端需要大量不同的后端服务时，容器化时使各环境镜像统一起来有很大的作用

This is of course the best, which will play a great role in the k8s environment, because you can use k8s service name to access applications;

In other words, when a complex front-end requires a large number of different back-end services, it is very useful to integrate the various environment mirrors when it is containerized.

**Comment by shenal** [comment]
@membphis  Is this still an open issue?

**Comment by membphis** [comment]
the APISIX has supported domain in the upstream node. we can close this issue.

**Comment by shenal** [comment]
@membphis  I still don't think this is working in the latest master code
Steps to recreate

1.  Start a simple python server with `python -m SimpleHTTPServer 3000`
2. Create an entry in `/etc/hosts` as `127.0.0.0 python.local`
3 Create an upstream with python:3000 as the node
4. Create a route with the upstream and invoke the route
Observation: Getting the following error
`2020/06/21 21:14:57 [error] 14988#14988: *1941 [lua] init.lua:188: parse_domain(): failed to parse domain for python.local, error:server returned error code: 3: name error, client: ::1, server: , request: "GET /get HTTP/1.1", host: "nginx"
2020/06/21 21:14:57 [error] 14988#14988: *1941 [lua] init.lua:342: http_access_phase(): failed to parse domain in upstream: server returned error code: 3: name error, client: ::1, server: , request: "GET /get HTTP/1.1", host: "nginx"
`

**Comment by membphis** [comment]
@shenal support `/etc/hosts` or DNS server is very different.

The Nginx only support DNS server. 
It never supports `/etc/hosts`.

Apache APISIX can support the use of DNS servers to resolve domains in upstream nodes.

**Comment by moonming** [comment]
Apache APISIX supports DNS resolver: https://github.com/apache/incubator-apisix/blob/master/conf/config.yaml#L85
