### ISSUE TITLE
doc: how to write a plugin step by step?

### ISSUE THREAD

**Issue by moonming** [apache/incubator-apisix#441]
0. If you have dependencies on external libraries, **check the license first** and add the license to the [COPYRIGHT](https://github.com/iresty/apisix/blob/master/COPYRIGHT) file.
1. Determine the name and priority of the plugin, and add to `conf/config.yaml`;
2. Write schema descriptions and check functions;
3. Determine which phase to run, generally `access` or `rewrite`;
4. Write the logic of the plugin in the corresponding phase;
5. Write test cases.

**Comment by Beckjiang** [comment]
At present, we have two needs:

1. Mapping the request parameters of the frontend interface and the backend interface;
2. Assemble the data of two or more backend interfaces and return it as one interface.

The first parameter mapping requirement, the development of plugins should be no problem, but want to know whether there are ready-made plugins can support it?

The second requirement, which I am considering now, is also the intention to develop a plugin to intervene in the body_filter phase to make additional requests and data processing.

Regarding the above two points, I wonder if there are any better suggestions?

目前我们有两个需求：

1. 对前端接口与后端接口的请求参数做映射；
2. 将两个或者两个以上后端接口的数据组装起来，作为一个接口的数据返回

第一个参数映射的需求，开发插件应该没问题，但想了解下有没现成的插件能够支持的呢？
第二个需求，我现在是这么考虑的，同样也是打算开发一个插件，介入body_filter阶段，去做额外的请求，与数据处理。

关于以上两点需求，请问有没有一些建议呢? @moonming

**Comment by moonming** [comment]
1.  There is no GraphQL plugin yet, I think it's very useful, and PR is welcomed.
2. I think use `lua-resty-http` to invoke backend services in the `rewrite` phase will be better, and code is more flexible and more readable.

**Comment by soulsoul** [comment]
add a  new issues about the requirement #603

**Comment by membphis** [comment]
fixed already
