### ISSUE TITLE
feature：the dashboard can support controlling cluster nodes？

### ISSUE THREAD

**Issue by soulsoul** [apache/incubator-apisix#459]
the dashboard  need to deploy independently , replaces the existing built-in.

**Comment by membphis** [comment]
do it enough for you? apisix supports to enable/disable admin api by yaml config now.

https://github.com/iresty/apisix/blob/master/conf/config.yaml#L5

**Comment by soulsoul** [comment]
i want that apisix node can register the config center ，then the admin dashboard can manage the  registered node and show its status ，and the route 、service config must be assigned to which apisix node 。we need apisix cluster。

**Comment by membphis** [comment]
Do you want to manage multiple clusters in one admin dashboard? We plan to support this feature in the commercial version. The apisix node configuration in a cluster is the same.

![image](https://user-images.githubusercontent.com/6814606/64185856-6a98d180-cea0-11e9-9f5d-793af9986635.png)

**Comment by soulsoul** [comment]
so it is！  then  the apisix nodes become resource pool , the manager can assige some nodes to app1, assige  another nodes to app2 , it is convenient for managers.

**Comment by agile6v** [comment]
I am also comfirming whether apisix supports to view the node status of cluster. 
Does apisix plan to support it in the community？

@membphis

**Comment by moonming** [comment]
@agile6v yes, welcome PR

**Comment by membphis** [comment]
I think we use `Prometheus` to collect all of the statuses of the cluster nodes.
Apache APISIX support `Prometheus` is enough, we do not need to support more.

https://github.com/apache/incubator-apisix-dashboard/issues/270
