### ISSUE TITLE
how to reload the local yaml file

### ISSUE THREAD

**Issue by moonming** [apache/incubator-apisix#504]
Now we use the update time to decide whether to reload the local yaml file. 

I think it's safer and more available to update through the API. Welcome discuss

**Comment by membphis** [comment]
![image](https://user-images.githubusercontent.com/6814606/64664443-d58a6f80-d481-11e9-8225-1b8bb6553c41.png)

will do update when the file changed and read the `#END` flag.

**Comment by membphis** [comment]
I wrote a doc about `stand-alone` model:

https://github.com/iresty/apisix/blob/master/doc/stand-alone.md#stand-alone-mode
