### ISSUE TITLE
typo in test cases

### ISSUE THREAD

**Issue by membphis** [apache/incubator-apisix#508]
https://github.com/iresty/apisix/blob/master/t/admin/services.t#L146

![image](https://user-images.githubusercontent.com/6814606/64701875-2a5ad400-d4dc-11e9-959d-f166d9a81aca.png)

and we need to check other test cases if they have similar problem.

**Comment by soulsoul** [comment]
delete?

**Comment by membphis** [comment]
the title is `push service + delete` now.

it should be `post service + delete`.

**Comment by membphis** [comment]
Fixed already
