### ISSUE TITLE
Error: module 'apisix.core.yaml' not found

### ISSUE THREAD

**Issue by dmxj** [apache/incubator-apisix#515]
when do apisix start, there a error happen:
lua: /root/luarocks-3.2.0/./lua_modules/bin/apisix:56: module 'apisix.core.yaml' not found
![image](https://user-images.githubusercontent.com/6835981/64784256-4cb42680-d59c-11e9-9437-8b71b05346a0.png)

**Comment by dmxj** [comment]
> @dmxj how did you install the apisix? please provide more install step information.
> 
> what is your response after you run this command:
> 
> ```shell
> luarocks show apisix
> ```

@membphis Thank you for your reply.
```
luarocks show apisix
```
the command show result:
```
Error: cannot find package apisix
Use 'list' to find installed rocks.
```
It seems that the installation was unsuccessful.

This is my installation procedure.
**OS: ubuntu 16.04**
1. install lua
```
tar -zxvf lua-5.3.5.tar.gz && cd lua-5.3.5
make linux test && make linux install
```
2.install luajit
```
tar -zxvf LuaJIT-2.0.5.tar.gz && cd LuaJIT-2.0.5
make && sudo make install
```
3. install openresty
```
tar -zxvf openresty-1.15.8.2.tar.gz && cd openresty-1.15.8.2
./configure --prefix=/usr/local/openresty --with-luajit --with-stream --with-http_iconv_module --with-http_realip_module --with-ld-opt="-Wl,-rpath,/usr/local/lib" --with-http_stub_status_module --with-http_ssl_module --with-http_sub_module --without-http_redis2_module --with-http_iconv_module
make && make install
```
4. install luarocks
```
tar -zxvf luarocks-3.2.0.tar.gz && cd luarocks-3.2.0
./configure
make && make install
```
5. install apisix
```
luarocks install --lua-dir=/usr/local/openresty/luajit apisix
```
No errors occurred during the whole process. And directory `/usr/local/apisix` was created, but the executable file `apisix` appear in directory `/root/luarocks-3.2.0/./lua_modules/bin/`

**Comment by membphis** [comment]
@dmxj please confirm if you installed luajit at `/usr/local/openresty/luajit`

That is a default path if you installed OpenResty by official package. you compile luajit and luarocks by yourself, that is a hard way. 

Please take a look at: https://github.com/iresty/apisix/blob/master/doc/install-dependencies.md#ubuntu-1804

if you still need more help, please add my QQ: 272995614. ^_^

**Comment by moonming** [comment]
@dmxj @membphis is this issue fixed?

**Comment by membphis** [comment]
need @dmxj confirm, I do not know :(

**Comment by moonming** [comment]
consider resolved
