### ISSUE TITLE
change: allow user to customize the key in `chash`

### ISSUE THREAD

**Issue by a610569731** [apache/incubator-apisix#575]
# Issue description
场景需求根据userId 分发到对应后端
删除schema.lua     enum = {"remote_addr"}
修改key为arg_userId

case: use the request argument `userId` as key, `chash` to the specified upstream.

# Environment

* apisix version (cmd: `apisix version`):0.7
* OS:linux

# What's the actual result? (include assertion message & call stack if applicable)

# What's the expected result?

**Comment by membphis** [comment]
We can remove this restriction, PR is welcome.

**Comment by membphis** [comment]
fixed https://github.com/apache/incubator-apisix/blob/master/doc/admin-api.md#upstream
