### ISSUE TITLE
need two query parameters page & limit for fetchXXXList API.

### ISSUE THREAD

**Issue by moonming** [apache/incubator-apisix#578]
refer to: https://github.com/iresty/apisix_dashboard/issues/38

**Comment by juzhiyuan** [comment]
I will make some changes on Dashboard when API is ready, please notify me about the Ready status.

**Comment by chnliyong** [comment]
Currently, APISIX access etcd  with v2 API, there is no dedicated pagination API，
The `RangeRequest` in [v3 API](https://github.com/etcd-io/etcd/blob/master/Documentation/dev-guide/api_reference_v3.md) seems supporting pagination with `limit` field. The HTTP API is support ed by the [gRPC gateway](https://github.com/etcd-io/etcd/blob/master/Documentation/dev-guide/api_grpc_gateway.md)

**Comment by chnliyong** [comment]
The `v2` API use `storev2` store, while `v3` use `mvcc` store, which means we cannot use `v3` API to operate data previously added by `v2`, the `etcdctl` cli supply `migrate` subcommand for transform the store, we also need doc for upgrade doc.

**Comment by membphis** [comment]
Apache APISIX does not need to support this feature. 

We can implement this feature in `manager API`: https://github.com/apache/incubator-apisix-dashboard/issues/270
