### ISSUE TITLE
bug: the client suspended when APISIX benchmark for http KeepAlive using self-develop benchmark tool 

### ISSUE THREAD

**Issue by Miss-you** [apache/incubator-apisix#581]
# Issue description

压测apisix，使用自研压测工具压测http长连接，client会卡住

自研http压测工具presscall

# Environment

* apisix version (cmd: `apisix version`):0.7.0
* OS:tlinux2.2(类似于centos7)

# Minimal test code / Steps to reproduce the issue

1、修改压测工具配置conf.cfg，打开长连接功能
2、连接ip设置为apisix提供服务的ip+port
3、启动工具
4、工具发了1000个请求后就会卡住

# What's the actual result? (include assertion message & call stack if applicable)

# What's the expected result?

**Comment by membphis** [comment]
确定下是你的客户端会卡住是么？

在这个情况下，用其他压测工具对 apisix 服务发起请求测试，比如 wrk 或 ab 等，apisix 服务正常么？

Are you sure your client will stop?

In this case, use other benchmark testing tools to do a test, such as wrk or ab. Is the apisix work still in normal?

**Comment by moonming** [comment]
I suggest you use `wrk` or other [benchmark tools ](https://github.com/denji/awesome-http-benchmark), so you can distinguish the bug between benckmark tool and apisix.

**Comment by moonming** [comment]
@Miss-you any feedback?

**Comment by Miss-you** [comment]
周二的时候我已经采用wrk进行压测了，因为可以通过脚本自定义header和body内容，确实更为方便。
另一方面，我也怀疑是我这边client的问题，预计十一的时候放假自己定位下可能的原因
