### ISSUE TITLE
featrue: implement  Aggregate request function

### ISSUE THREAD

**Issue by soulsoul** [apache/incubator-apisix#603]
Assemble the data of two or more backend interfaces and return it as one interface.
The first parameter mapping requirement, the development of plugins should be no problem, but want to know whether there are ready-made plugins can support it?

将两个或者两个以上上游接口的数据组装起来，作为一个聚合请求接口的数据返回。

**Comment by moonming** [comment]
APISIX not have this kind of plugin yet, I think it's useful, welcome PR.

**Comment by Beckjiang** [comment]
> Assemble the data of two or more backend interfaces and return it as one interface.
> The first parameter mapping requirement, the development of plugins should be no problem, but want to know whether there are ready-made plugins can support it?
> 
> 将两个或者两个以上上游接口的数据组装起来，作为一个聚合请求接口的数据返回。

I have the same demand. How is your project progress now?

**Comment by membphis** [comment]
we can use cosocket + resty-http to implement this.

**Comment by Beckjiang** [comment]
About the request, it could be in two modes "pipeline" or "parallel".

The "pipeline" mode is easy to implement by `httpc:request_pipeline`. But what about the "parallel" mode? ngx.thread.spawn + resty-http?

**Comment by moonming** [comment]
why we need `parallel` mode? cosocket will not block request.

**Comment by Beckjiang** [comment]
I think It is a way to reduce the total response time.

A similar question.
https://groups.google.com/forum/#!msg/openresty/ro8DmOdvXe8/66S-W0yGCAAJ

**Comment by membphis** [comment]
`httpc:request_pipeline` is good enough.

**Comment by Beckjiang** [comment]
well. I will try it. thx.

**Comment by membphis** [comment]
fixed https://github.com/apache/incubator-apisix/pull/1388
