### ISSUE TITLE
doc: how to install APISIX on ARM64

### ISSUE THREAD

**Issue by membphis** [apache/incubator-apisix#622]

**Comment by moonming** [comment]
I wrote the Chinese versoin:https://mp.weixin.qq.com/s/ZulGGzQRbi23lTvEAbqr6w,  would anyone like to organize it in the document?

**Comment by moonming** [comment]
and we need the English version too.

**Comment by membphis** [comment]
By the way, we should specifically mention in the readme that APISIX already supports the ARM64 platform first.

**Comment by membphis** [comment]
fixed
