### ISSUE TITLE
bug:  SSL_do_handshake() failed (SSL: error:1417A179:SSL routines:tls_post_process_client_hello:cert cb error) while SSL handshaking, clien

### ISSUE THREAD

**Issue by a610569731** [apache/incubator-apisix#631]
# Issue description
苹果客户端可以访问
android java https 请求报错

# Environment
android
* apisix version (cmd: `apisix version`):0.8
* OS:centos7

# Minimal test code / Steps to reproduce the issue
android https 请求 微信小游戏 https 请求
```shell
# your steps
1.
2.
3.
```

# What's the actual result? (include assertion message & call stack if applicable)

# What's the expected result?

**Comment by moonming** [comment]
Can you show one reproduce example?

**Comment by moonming** [comment]
@a610569731 any update?

**Comment by membphis** [comment]
Too long, no reply

**Comment by Hmemories** [comment]
I also encountered this problem when used SSL. How can I solve it
![image](https://user-images.githubusercontent.com/30172398/99640601-14ec1d00-2a84-11eb-8f5c-541aaa090999.png)

**Comment by Hmemories** [comment]
![image](https://user-images.githubusercontent.com/30172398/99640669-2f25fb00-2a84-11eb-89ac-4c56fe179133.png)

**Comment by tokers** [comment]
Could you please provide the essential steps to reproduce this issue?
Thanks!


-- 
Zhang Chao
