### ISSUE TITLE
feature：proxy_pass  to http or https domain

### ISSUE THREAD

**Issue by tomzhan2019** [apache/incubator-apisix#633]
目前在apisix上，使用upstream配置node，域名加端口（也无法配置协议http或https），然后配置route，是无法正常转发到别到域名上，所以，能否帮忙实现这个功能。

**Comment by moonming** [comment]
can you show one example? I am not get your point.

**Comment by tomzhan2019** [comment]
比如我在apisix上配了一个router，host是www.a.com,所有到请求uri都是直接proxy_pass https://www.baidu.com

**Comment by nic-chen** [comment]
> 比如我在apisix上配了一个router，host是www.a.com,所有到请求uri都是直接proxy_pass https://www.baidu.com


请看这里：
https://github.com/iresty/apisix/blob/master/doc/plugins/proxy-rewrite-cn.md

**Comment by xym808** [comment]
Dashboard 不支持配置upstream 地址为域名（只支持ip），  api支持配置域名吗？

**Comment by membphis** [comment]
@xym808 Currently supporting domain names through the API

**Comment by moonming** [comment]
consider resolved.
