### ISSUE TITLE
bug: wrong value of ssl_ciphers

### ISSUE THREAD

**Issue by moonming** [apache/incubator-apisix#666]
wrong value of ssl_ciphers:
https://github.com/iresty/apisix/blob/master/conf/config.yaml#L40

we should refer to [mozilla](https://ssl-config.mozilla.org/) and [cloudflare](https://github.com/cloudflare/sslconfig/blob/master/conf)

**Comment by moonming** [comment]
and set to `Modern`, `Intermediate` and `Old` options is better, user don't need to know the details.

**Comment by membphis** [comment]
> and set to `Modern`, `Intermediate` and `Old` options is better, user don't need to know the details.
replied: https://github.com/iresty/apisix/pull/669#issuecomment-540861034
