### ISSUE TITLE
bug: apisix/dashboard don't support array type for the schema in plugins

### ISSUE THREAD

**Issue by dequanLi** [apache/incubator-apisix#679]
### Issue description
I use array type for schema of the plugn,but i can't edit it in apisix/dashboard
" ip-restriction" pugin has the same problem, it also used array type
`
whitelist = {
            type = "array",
            items = {type = "string", anyOf = core.schema.ip_def},
            minItems = 1
        },
        blacklist = {
            type = "array",
            items = {type = "string", anyOf = core.schema.ip_def},
            minItems = 1
        }
`
eg:

![image](https://user-images.githubusercontent.com/25575950/66695824-804bb300-ecf8-11e9-84fd-0d8bb684f925.png)

### Environment
0.8

* apisix version (cmd: `apisix version`):
* OS:

### Minimal test code / Steps to reproduce the issue

# your steps
step1:
![image](https://user-images.githubusercontent.com/25575950/66695861-eb958500-ecf8-11e9-98cd-afafb81c628e.png)
the link :  http://apisix.iresty.com/apisix/dashboard/#/schema/routes/list

step2:
edit the rule ,and add  a "ip-restriction" plugin , then you can reproduce the issue

**Comment by moonming** [comment]
`ip-restriction` is in the dashboard todo list, welcome PR.

**Comment by dequanLi** [comment]
> `ip-restriction` is in the dashboard todo list, welcome PR.

thinks

**Comment by juzhiyuan** [comment]
@moonming @dequanLi  How about this?

![image](https://user-images.githubusercontent.com/2106987/66699834-98352e00-ed1c-11e9-89f3-2ac256a503fc.png)

## Request

```javascript
{"uri":"i.i","plugins":{"ip-restriction":{"blacklist":["222"],"whitelist":["111"]}},"desc":"test"}
```

## Response

```javascript
{"error_msg":"failed to check the configuration of plugin ip-restriction err: invalid \"oneOf\" in docuement at pointer \"#\""}
```

just for sure, does `oneOf` mean the request will only POST either `whitelist` or `blacklist`?

**Comment by moonming** [comment]
> just for sure, does `oneOf` mean the request will only POST either `whitelist` or `blacklist`?

yes

**Comment by juzhiyuan** [comment]
The JSON format for current plugins

## grpc tracecode

    {
        "proto_id": "1",
        "service": "helloworld.Greeter",
        "method": "SayHello"
    }

## jwt-auth:

    {
        "key": "user-key",
        "secret": "my-secret-key"
    }

## key-auth

    {
        "key": "auth-one"
    }

## limit-count

    {
        "count": 2,
        "time_window": 60,
        "rejected_code": 503,
        "key": "remote_addr"
    }


## limit-conn

    {
        "conn": 100,
        "burst": 50,
        "default_conn_delay": 0.1,
        "rejected_code": 503,
        "key": "remote_addr"
    }

## limit-req

    {
        "rate": 4,
        "burst": 2,
        "rejected_code": 503,
        "key": "remote_addr"
    }

## openid-connect

    {
        "client_id": "kbyuFDidLLm280LIwVFiazOqjO3ty8KH",
        "client_secret": "XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX-STRINg",
        "discovery": "https://samples.auth0.com/.well-known/openid-configuration",
        "redirect_uri": "https://iresty.com",
        "ssl_verify": false,
        "timeout": 10,
        "scope": "apisix"
    }



## server_less

    {
        "functions" : ["do return true end"] 
    }

## zipkin

    {
        "endpoint": "http://127.0.0.1:1982/mock_zipkin",
        "sample_ratio": 1
    }

## limit-count-redis

    {
        "count": 2,
        "time_window": 60,
        "rejected_code": 503,
        "key": "remote_addr",
        "policy": "redis",
        "redis": {                      -- 是固定项，只不过用一层配置包裹了一下
            "host": "127.0.0.1",        -- 我稍后把他修改成平铺结构，去掉这个不必要的 table
            "port": 6379,
            "timeout": 1001
        }
    }
    
## IP 黑白名单

    whitelist = [           -- 二选一的数组
        "10.255.254.0/24",
        "192.168.0.0/16"
    ]

    blacklist = [
        "10.255.254.0/24",
        "192.168.0.0/16"
    ]

## proxy-rewrite

    {
        "uri": "/uri/plugin_proxy_rewrite",
        "host": "foo.com",
        "headers": {
            "X-Api-Engine1": "apisix",    -- key 不是固定的，行数也不固定
            "X-Api-Engine2": "apisix",    
            "X-Api-Engine3": "apisix"     
        }
    }

**Comment by juzhiyuan** [comment]
It will be like this.

![image](https://user-images.githubusercontent.com/2106987/67830251-e4ea7880-fb14-11e9-8917-217ada812518.png)

**Comment by membphis** [comment]
> It will be like this.
> 

How to add new ones? We need an 'add' button.

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/67840080-073dbf80-fb30-11e9-9703-cb1bd43f226f.png)

create succeed :) Dashboard will be updated today.

**Comment by membphis** [comment]
Cool, nice job!
