### ISSUE TITLE
request help: 

### ISSUE THREAD

**Issue by gary0121** [apache/incubator-apisix#689]
### Issue description
ESXI 6.7   运行 kubernetes  1.15.2版本集群，centos7 宿主机。apisix节点宿主机抛出异常：

Oct 12 10:28:32 test-k8s-node2 kernel: traps: openresty[14348] trap invalid opcode ip:7f7061899940 sp:7fff0a5d4f00 error:0 in rapidjson.so[7f7061869000+32000]
Oct 12 10:28:33 test-k8s-node2 kernel: traps: openresty[14352] trap invalid opcode ip:7f7061899940 sp:7fff0a5d4f00 error:0 in rapidjson.so[7f7061869000+32000]
Oct 12 10:28:33 test-k8s-node2 kernel: traps: openresty[14351] trap invalid opcode ip:7f7061899940 sp:7fff0a5d4f00 error:0 in rapidjson.so[7f7061869000+32000]

现象于这个问题类似： https://github.com/Kong/kong/issues/2846

### Environment

* apisix version (cmd: `apisix version`): 0.8
* OS: centos 7

**Comment by moonming** [comment]
Is your CPU supports sse4_2?
```
cat /proc/cpuinfo | grep -i sse | head -n1
```

**Comment by gary0121** [comment]
cat /proc/cpuinfo | grep -i sse | head -n1
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc eagerfpu pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm ssbd ibrs ibpb stibp fsgsbase tsc_adjust smep arat spec_ctrl intel_stibp flush_l1d arch_capabilities

**Comment by gary0121** [comment]
@moonming

**Comment by chnliyong** [comment]
Do you use your own built image or image from docker hub?

**Comment by membphis** [comment]
old issue, close first. @gary0121 if you still have problem, please let me know.
