### ISSUE TITLE
bug: invalid configuration: invalid "enum" in docuement at pointer "#/key when I set chash upstream

### ISSUE THREAD

**Issue by lilien1010** [apache/incubator-apisix#708]
### Issue description
![image](https://user-images.githubusercontent.com/3814966/67065010-3a329b80-f19f-11e9-9b7a-29d0d7f9b053.png)

### Environment

* apisix version (cmd: `apisix version`):0.8
* OS: Alpine

### Minimal test code / Steps to reproduce the issue

# your steps
1. open dashboard /apisix/dashboard/#/schema/upstream/create
2. create upstream
3. choose chash

### What's the actual result? (including assertion message & call stack if applicable)
error show ` invalid configuration: invalid "enum" in docuement at pointer "#/key`

### What's the expected result?
It show be able to set upstream

**Comment by juzhiyuan** [comment]
@membphis It seems the backend API has been changed.

**Comment by membphis** [comment]
relate PR is not merged yet: https://github.com/iresty/apisix/pull/719

**Comment by spacewander** [comment]
@lilien1010 @membphis 
Is there any PR to take over #719? That one is closed.

**Comment by membphis** [comment]
I think we can close this PR, @lilien1010 has fixed this issue already.
