### ISSUE TITLE
bug: yaml方式配置，还需要配置etcd

### ISSUE THREAD

**Issue by xsi640** [apache/incubator-apisix#716]
启动报错。
```
/usr/local/openresty/luajit/bin/luajit: /usr/bin/apisix:515: attempt to index local 'etcd_conf' (a nil value)
stack traceback:
	/usr/bin/apisix:515: in function </usr/bin/apisix:507>
	/usr/bin/apisix:585: in main chunk
	[C]: at 0x55af6913e2c0
```

**Comment by membphis** [comment]
welcome PR

**Comment by soulsoul** [comment]
the etcd is data center, someone want to just use apisix by a configuration file ,avoiding the dependent of etcd. is right ? want to just configure the service / upstream in a ymal file ?

**Comment by moonming** [comment]
> the etcd is data center, someone want to just use apisix by a configuration file ,avoiding the dependent of etcd. is right ? want to just configure the service / upstream in a ymal file ?

APISIX already support that.

**Comment by moonming** [comment]
the bug is here: https://github.com/iresty/apisix/blob/master/bin/apisix#L521
If user not use etcd as data center, we should not to read configures of etcd at all.
