### ISSUE TITLE
request help:  http redirect to https

### ISSUE THREAD

**Issue by nopost** [apache/incubator-apisix#731]
### Issue description

If it's not HTTPS, turn to HTTPS.

The code used in nginx is as follows

`
If ($server_port! ~ 443) {rewrite ^ (/. *) $HTTPS: / / $host $1 permanent;}
`
It is recommended that the port can also be customized
### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by nopost** [comment]
可以扩展成 rewrite 插件，不限于http转https . 返回的code值也不限于302！！

**Comment by moonming** [comment]
@nopost you'd better use English in the public channel, thx

**Comment by membphis** [comment]
we can implement a new plugin which named `rewrite`, here is an example:

```json
{
    "path": "/*",
    "vars": [
        ["scheme", "==", "http"],
    ],
    "plugins": {
        "rewrite": {
            "ret_code": 302,
            "uri": "https://$host/$uri"
        }
    }
}
```

**Comment by nopost** [comment]
> 
> 
> we can implement a new plugin which named `rewrite`, here is an example:
> 
> ```json
> {
>     "path": "/*",
>     "vars": [
>         ["scheme", "==", "http"],
>     ],
>     "plugins": {
>         "rewrite": {
>             "ret_code": 302,
>             "uri": "https://$host/$uri"
>         }
>     }
> }
> ```

very good！！You're awesome. It's totally beyond my imagination. Excellent!

**Comment by moonming** [comment]
> we can implement a new plugin which named `rewrite`, here is an example:
> 
> ```json
> {
>     "path": "/*",
>     "vars": [
>         ["scheme", "==", "http"],
>     ],
>     "plugins": {
>         "rewrite": {
>             "ret_code": 302,
>             "uri": "https://$host/$uri"
>         }
>     }
> }
> ```

`redirect` is better.

**Comment by nopost** [comment]
> 
> 
> > we can implement a new plugin which named `rewrite`, here is an example:
> > ```json
> > {
> >     "path": "/*",
> >     "vars": [
> >         ["scheme", "==", "http"],
> >     ],
> >     "plugins": {
> >         "rewrite": {
> >             "ret_code": 302,
> >             "uri": "https://$host/$uri"
> >         }
> >     }
> > }
> > ```
> 
> `redirect` is better.

 Yes. This is more accurate
