### ISSUE TITLE
支持nginx的proxy_pass路由转发功能

### ISSUE THREAD

**Issue by mattu79** [apache/incubator-apisix#733]
目前proxy_rewrite无法提供类似proxy_pass的路由转发功能
如下设置，

location /ctx/ {
   proxy_pass http://192.168.1.31/ctx1/
}
访问http://192.168.1.30/ctx/sub/sta1.html
就可以实际访问http://192.168.1.31/ctx1/sub/sta1.html上。

**Comment by shuaijinchao** [comment]
rewrite the upstream host address, please see: [upstream configuration document](https://github.com/iresty/apisix/blob/master/doc/architecture-design.md#upstream).

**Comment by moonming** [comment]
Keeping simple and easy to understand is the principle of APISIX. 
So I don't think we need to support these hard to understand rules, which can implement by other ways. 
please take a look at `proxy-rewrite` plugin: https://github.com/iresty/apisix/blob/master/doc/plugins/proxy-rewrite.md

**Comment by mattu79** [comment]
既然radixtree的前缀匹配支持多级子目录的匹配，那为何proxy_rewrite不能支持多级资源的路由转发呢。我认为这是一个很基础的路由功能。
我有一些传统http接口和静态资源需要代理出去，所以需要类似的功能。

**Comment by mattu79** [comment]
另外如果没有从upsteam上取得资源，能不能把该真实的upsteam_url错误打印出来，我在使用过程中都不容易联调请求到底转发到什么地址上了。

**Comment by membphis** [comment]
> 另外如果没有从upsteam上取得资源，能不能把该真实的upsteam_url错误打印出来，我在使用过程中都不容易联调请求到底转发到什么地址上了。

you can get `upstream_url` in the access log.

**Comment by mattu79** [comment]
默认的日志格式打印的是网关接收到的请求地址而非转向后的后端真实url。

**Comment by membphis** [comment]
you can use plugin `proxy-rewrite` to do this.

**Comment by shuaijinchao** [comment]
@jiagoumengxiang `proxy-rewrite` plugin document. please see: https://github.com/iresty/apisix/blob/master/doc/plugins/proxy-rewrite.md
