### ISSUE TITLE
I want to join the `iresty` organization.

### ISSUE THREAD

**Issue by Tinywan** [apache/incubator-apisix#734]
### Issue description

I want to join the `iresty` organization.

### pr lsit 

1. update apisix README.md [https://github.com/iresty/apisix/commit/151c899d45ea0ff28797a949c9f613ccc03dc3fb](https://github.com/iresty/apisix/commit/151c899d45ea0ff28797a949c9f613ccc03dc3fb)

2. add apisix_conf dir and update config.yaml [https://github.com/iresty/docker-apisix/pull/23](https://github.com/iresty/docker-apisix/pull/23)

3. add etcd config file and Run etcd server eg [https://github.com/iresty/docker-apisix/pull/24](https://github.com/iresty/docker-apisix/pull/24)
4. update docker-apisix README.md [https://github.com/iresty/docker-apisix/pull/28](https://github.com/iresty/docker-apisix/pull/28)

**Comment by Tinywan** [comment]
@moonming only docker, k8s unfamiliar

**Comment by moonming** [comment]
how about begin from issue and PR from docker-apisix repo?

**Comment by Tinywan** [comment]
@moonming have spare time, will do

**Comment by membphis** [comment]
I agree @Tinywan join `iResty` organization

**Comment by moonming** [comment]
It's not a vote thread. we need to discuss which part is suitable for
@Tinywan <https://github.com/Tinywan>.

Thanks,
Ming Wen
Twitter: _WenMing


YuanSheng Wang <notifications@github.com> 于2019年10月25日周五 上午10:36写道：

**Comment by membphis** [comment]
@moonming

**Comment by juzhiyuan** [comment]
@Tinywan Thanks for your contributions 👍 

@membphis @moonming We could hold issues like this, and make some more detailed community policies step by step :)

**Comment by moonming** [comment]
@juzhiyuan agreed
