### ISSUE TITLE
release check list for 0.9

### ISSUE THREAD

**Issue by moonming** [apache/incubator-apisix#748]
- [x] mark history releases as non-ASF release
- [x] all source code files contain ASF header
- [x] no binary file
- [x] DISCLAIMER exists
- [x] LICENCE and NOTICE file are good
- [x] incubating in name
- [x] signature and hashes correct

**Comment by juzhiyuan** [comment]
got it

**Comment by juzhiyuan** [comment]
@moonming After several searches and verifying, all ready for releasing work have been done except `incubating in name` & `signature and hashes check`. 👍 

Also, we may hold a vote before our release work as [Releases Policy](https://incubator.apache.org/policy/incubation.html#releases) says.

**Comment by moonming** [comment]
I think the license of dashboard is not clear enough: https://lists.apache.org/thread.html/f7fff113d56415b18a858207e4369dadc72fb896c5784932ded2bc75@%3Cdev.apisix.apache.org%3E

**Comment by justinmclean** [comment]
"we may hold a vote" I assume means you will hold a vote. A vote is a requirement and can't be skipped.

**Comment by juzhiyuan** [comment]
@moonming  The release of [Apache PLC4X](https://lists.apache.org/thread.html/7e9c475d07c0e12f813226aa123f54969ebb21a2277b32e9bd366d96@%3Cdev.plc4x.apache.org%3E) sample has one `RELEASE_NOTES` file, and I'd like to know if we need that file? (though it doesn't appear in the ASF release policy as I know)

**Comment by juzhiyuan** [comment]
> "we may hold a vote" I assume means you will hold a vote. A vote is a requirement and can't be skipped.

Sure, we MUST hold a vote before making a release.

**Comment by juzhiyuan** [comment]
> I think the license of the dashboard is not clear enough: https://lists.apache.org/thread.html/f7fff113d56415b18a858207e4369dadc72fb896c5784932ded2bc75@%3Cdev.apisix.apache.org%3E

@moonming  Ya, I noticed and was curious about it when I went through [the Disclaimers part](https://incubator.apache.org/guides/releasemanagement.html), but after I find the DISCLAIMER file is under Apache APISIX repo, I think you know which one is correct :(

**Comment by justinmclean** [comment]
A RELEASE_NOTES fieldworker is not required but is a very good idea to tell uses what is in the release or make them aware of any issues.
