### ISSUE TITLE
apisix和openresty对比几大优势。欢迎补充！

### ISSUE THREAD

**Issue by ygm521** [apache/incubator-apisix#753]
1, etcd 解决分布式配置存储一致性问题,解决了配置变更推送问题;
2, 路由和真实服务配置可以动态调整;
3, nginx配置变更需要reload，worker进程缓存失效问题;

**Comment by Tinywan** [comment]
This is not the same, can't compare

**Comment by Miss-you** [comment]
Openresty is a full-fledged web platform
APISIX is an high-performance API-Gateway

You can compare APISIX to other API-gateways, like tyk, kong, orange, and
so on.

ShaoBo Wan(无极) <notifications@github.com> 于2019年10月29日周二 下午1:32写道：

**Comment by membphis** [comment]
@ygm521 I think we can close this issue.

**Comment by ygm521** [comment]
希望院生补充补充吧，许多入门者都不清楚apisix和nginx有啥区别？ @moonming @membphis

**Comment by Tinywan** [comment]
@Miss-you  I agree

**Comment by idevz** [comment]
@ygm521 we'd better using English here, on account of we're in the apache-incubator now.

For your question, apisix is a Cloud Native Api GateWay, but Nginx or OpenResty are web Servers, 
Apisix now is based on Nginx and Luajit(ngx_lua), there’re totally different things.

I think maybe your experience of Nginx using made you're  confused. Such as using Nginx as a revers Proxy,
Or a simple web server.

As a Cloud Native Api GateWay ApiSix not only provider a proxy ability, but also the ability of Service governance for your Cloud Native Micro services.

If you want some Chinese communication, you can discuss those questions in QQ group(552030619).

**Comment by ygm521** [comment]
I am based on nginx to write related c language modules. As far as I know, 
1, apisix is nothing more than using the etcd storage configuration to implement dynamic configuration changes; 
2, instead of nginx's location{} matching
3, using a large number of worker process caches.

**Comment by idevz** [comment]
APISIX is not only implement dynamic configuration changes; 
I think The most import things which APISIX have done are:

1. Provider a high performance route to mange your business traffic.
2. Provider a flexible mechanism(plugins) to add your custom logic about your own business.
3. Based on the upon second point, APISIX bring us many good plugins out of the box, such as rate-limit, trace, server-less and so on.

All in one world APISIX is a API Gateway Not a Web Server.
