### ISSUE TITLE
bug: 三级泛解析路由规则无法匹配

### ISSUE THREAD

**Issue by yy8866** [apache/incubator-apisix#761]
### Environment

* apisix version (cmd: `apisix version`):master
* OS:docker

### Minimal test code / Steps to reproduce the issue
`
{"node":{"nodes":[
{"value":{"host":"lnp-admin.test.com","plugins":{},"uri":"\/*","service_id":"00000000000000000070","desc":"lap-admin-test"},"createdIndex":77,"key":"\/apisix\/routes\/00000000000000000077","modifiedIndex":77},
{"value":{"host":"apisix.test.com","plugins":{},"uri":"\/apisix\/*","service_id":"00000000000000000035","desc":"apisix.zhu"},"createdIndex":47,"key":"\/apisix\/routes\/00000000000000000038","modifiedIndex":47},
{"value":{"host":"lap.test.com","plugins":{},"uri":"\/*","service_id":"00000000000000000065","desc":"lap-test"},"createdIndex":74,"key":"\/apisix\/routes\/00000000000000000074","modifiedIndex":74},
{"value":{"host":"lnp.test.com","plugins":{},"uri":"\/*","service_id":"00000000000000000066","desc":"lnp-test"},"createdIndex":75,"key":"\/apisix\/routes\/00000000000000000075","modifiedIndex":75},
{"value":{"host":"lap-admin.test.com","plugins":{},"uri":"\/*","service_id":"00000000000000000071","desc":"lap-admin-test"},"createdIndex":76,"key":"\/apisix\/routes\/00000000000000000076","modifiedIndex":76},

## 下面2条是可以匹配到的
{"value":{"host":"yhs.demo.test.com","plugins":{},"uri":"\/*","service_id":"00000000000000000065","desc":"yhs-demo-test-com"},"createdIndex":80,"key":"\/apisix\/routes\/00000000000000000080","modifiedIndex":80},
{"value":{"host":"pma.demo.test.com","plugins":{},"uri":"\/*","service_id":"00000000000000000066","desc":"pma-demo-test-com"},"createdIndex":98,"key":"\/apisix\/routes\/00000000000000000097","modifiedIndex":98},
##

## 注意这里（匹配不上）:如果试用test2.demo.test.com去访问，匹配不到，直接用cdnserver那条路由了
{"value":{"host":"*.demo.test.com","plugins":{},"uri":"\/*","service_id":"00000000000000000066","desc":"*-demo-test-com"},"createdIndex":98,"key":"\/apisix\/routes\/00000000000000000098","modifiedIndex":99},

{"value":{"host":"apisix.test.com","plugins":{},"uri":"\/apisix\/*","service_id":"00000000000000000035","desc":"apisix-fu"},"createdIndex":48,"key":"\/apisix\/routes\/00000000000000000046","modifiedIndex":48},
{"value":{"host":"portainer.test.com","plugins":{},"uri":"\/*","service_id":"00000000000000000058","desc":"portainer-test"},"createdIndex":59,"key":"\/apisix\/routes\/00000000000000000059","modifiedIndex":59},

## 上面没又匹配到转到cdnserver##
{"value":{"plugins":{},"service_id":"00000000000000000092","desc":"cdnserver","uri":"\/*"},"createdIndex":93,"key":"\/apisix\/routes\/00000000000000000067","modifiedIndex":93}]
##
,"modifiedIndex":10,"createdIndex":10,"key":"\/apisix\/routes","dir":true},"action":"get"}

`

**Comment by yy8866** [comment]
## ps： 
router:
    http: 'radixtree_host_uri'

**Comment by yy8866** [comment]
理论上*.xxx.xxx.com的优先级是应该大于host为空的那条路由的。实际使用中上优先匹配了空host的那条路由

**Comment by yy8866** [comment]
> 
> 
> > 理论上*.xxx.xxx.com的优先级是应该大于host为空的那条路由的。实际使用中上优先匹配了空host的那条路由
> 
> Sorry, I didn't understand your example, and I didn't search for any route related to `xxx.xxx.com`.

理论上*.demo.test.com的优先级是应该大于host为空的那条路由的。
现在实际情况是优先匹配了空host的那条路由

——————————————————————
例如：访问   test1.demo.test.com 或者   test2.demo.test.com

## 理论应该匹配
{"value":{"host":"*.demo.test.com","plugins":{},"uri":"\/*","service_id":"00000000000000000066","desc":"*-demo-test-com"},"createdIndex":98,"key":"\/apisix\/routes\/00000000000000000098","modifiedIndex":99},
--------------------------------------------------------
## 目前实际匹配
{"value":{"plugins":{},"service_id":"00000000000000000092","desc":"cdnserver","uri":"/*"},"createdIndex":93,"key":"/apisix/routes/00000000000000000067","modifiedIndex":93}]

——————

**Comment by membphis** [comment]
Yes, it should be a bug, PR welcome.

**Comment by Zheaoli** [comment]
I'll take care of it

**Comment by moonming** [comment]
@Zheaoli thanks

**Comment by lilien1010** [comment]
this is bug from lua-resty-radixtree

```lua
local radix = require("resty.radixtree")
local rx = radix.new({
   {
        paths = {"/aa/*"},
        metadata = "metadata /aa",
    },
    {
        paths = {"/aa/*"},
        metadata = "metadata /aa1",
        hosts = {"*.bar.com"}
    }
})
ngx.say(rx:match("/aa/bb", {host = "qqq.bar.com"}))
```

this code will output `metadata /aa1` ,my suggestion is define two raw tree in  lua-resty-radixtree, one with host, one  without host, we search the radixtree  from tree with host first if match return,other wise search tree without host
@membphis

**Comment by membphis** [comment]
@lilien1010 Your solution is very fine. I love it.

**Comment by lilien1010** [comment]
@membphis  fixed in my PR in iresty repo 
https://github.com/iresty/lua-resty-radixtree/pull/27
