### ISSUE TITLE
关于网关自身api安全可见性的问题

### ISSUE THREAD

**Issue by mlboy** [apache/incubator-apisix#764]
### Issue description
建议增加以下关于 网关自身api 和面板 的安全开关，即 是公网可以访问，还是仅内网可以访问

### Environment

* apisix version (cmd: `apisix version`):
* OS:any

**Comment by membphis** [comment]
You can also specify a list of IPs that are allowed to be accessed here.

https://github.com/apache/incubator-apisix/blob/master/conf/config.yaml#L9

**Comment by moonming** [comment]
@mlboy  Please use English in the public channel, thx
