### ISSUE TITLE
bug: rewrite function of plugin does not run at rewrite phase

### ISSUE THREAD

**Issue by wangxiaochuang** [apache/incubator-apisix#771]
### Issue description

in access_phase, the plugin's rewrite executed if it exists

### Environment

* apisix version (cmd: `apisix version`):
* OS:

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by wangxiaochuang** [comment]
[here](https://github.com/apache/incubator-apisix/blob/master/lua/apisix.lua#L326)

**Comment by membphis** [comment]
This is an optimization method. Combine the different phases to make APISIX faster.

![image](https://user-images.githubusercontent.com/6814606/67997155-d1aee880-fc8d-11e9-847a-f5da5efce591.png)

**Comment by wangxiaochuang** [comment]
It runs in access phase for 'run_plugin("rewrite", plugins, api_ctx)'
