### ISSUE TITLE
bug: merge_service_route function's second return value will always be nil

### ISSUE THREAD

**Issue by wangxiaochuang** [apache/incubator-apisix#776]
### Issue description
in apisix.lua
![image](https://user-images.githubusercontent.com/12962576/67948368-87435280-fc20-11e9-9c7c-fb666a272d3d.png)
in plugin.lua
![image](https://user-images.githubusercontent.com/12962576/67948429-a6da7b00-fc20-11e9-80fe-e27ccb6a2e4d.png)
is something wrong ? @membphis 

### Environment

* apisix version (cmd: `apisix version`):
* OS:

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by moonming** [comment]
@wangxiaochuang you didn't find the correct function, you can search `merge_service_route` in plugin.lua again.

**Comment by wangxiaochuang** [comment]
yes, I know the right one; if it hasn't cached, "local function merge_service_route" executed; otherwise new_lru_fun in core/lrucache.lua will be executed

**Comment by wangxiaochuang** [comment]
I have debugged the code successfully

**Comment by moonming** [comment]
@wangxiaochuang so is it a bug?

**Comment by membphis** [comment]
We can now remove the 'changed' variable.  Welcome PR.

**Comment by wangxiaochuang** [comment]
I don't know what the role of this variable "changed" is. so I can not remove it

**Comment by wangxiaochuang** [comment]
> @wangxiaochuang so is it a bug?

If this variable is useful, then it must be a bug. @moonming

**Comment by membphis** [comment]
This variable is useless, we can drop it.

**Comment by wangxiaochuang** [comment]
ok, I will submit the PR to drop it

**Comment by membphis** [comment]
fixed already
