### ISSUE TITLE
request help: How to build an APISIX rpm?

### ISSUE THREAD

**Issue by Miss-you** [apache/incubator-apisix#800]
### Issue description

We can install the APISIX by rpm, but I can't find a document about how to build an APISIX rpm.

### Environment

* apisix version (cmd: `apisix version`): 0.8 or higher
* OS:CentOS7 or Tlinut2.2

**Comment by moonming** [comment]
there has rpm script from community: https://github.com/iresty/build-tools

**Comment by Miss-you** [comment]
Thanks a lot.
