### ISSUE TITLE
request help: Is there any plan that the APISIX supports the Consul?

### ISSUE THREAD

**Issue by Miss-you** [apache/incubator-apisix#802]
### Issue description
Consul is similar with etcd, and there are some company or individuals which use the consul instead of etcd.
Is there any plan that the APISIX supports the Consul?

### Environment

* apisix version (cmd: `apisix version`): 0.8 or higher
* OS: linux

**Comment by membphis** [comment]
PR welcome ^_^

**Comment by Miss-you** [comment]
PR on the way

**Comment by membphis** [comment]
@Miss-you any news?

**Comment by crazyliuzc** [comment]
any news?

**Comment by membphis** [comment]
support the DNS way of Consul.
