### ISSUE TITLE
request help: Which one has a higher priority, Eureka or Consul?

### ISSUE THREAD

**Issue by Miss-you** [apache/incubator-apisix#804]
### Issue description
If you want to integrate into the Spring Cloud community, you need to support the Spring Cloud service registry. Eureka and Consul both are the service registry of the Spring Cloud. which one is more polular? Which one has a higher priority?

### Environment

* apisix version (cmd: `apisix version`): 0.9 or higher
* OS: linux

**Comment by soulsoul** [comment]
eureka +1

**Comment by Miss-you** [comment]
I think we need more user to vote for this question.

**Comment by binlaniua** [comment]
eureka +1

**Comment by sshniro** [comment]
eureka +1

**Comment by tyhtgh** [comment]
eureka +1

**Comment by totemofwolf** [comment]
maybe `Nacos`(powered by Alibaba) is better. ;-)

http://console.nacos.io/nacos/index.html#/login

**Comment by membphis** [comment]
Nacos can be used as a configuration center or as service discovery.

**Comment by zhendongli** [comment]
Actually, eureka is not very good choice for service registry in very large scale production env.  And eureka 2.0 is not production ready yet. So I vote for Consul.

**Comment by crazyliuzc** [comment]
Consul+1

**Comment by membphis** [comment]
Consul Eureka, we both support them already
