### ISSUE TITLE
bug: should not remove the square brackets of [IPv6] address literal in core.utils.parse_addr

### ISSUE THREAD

**Issue by spacewander** [apache/incubator-apisix#816]
Currently I choice to remove the square brackets because `core.utils.parse_ipv6` doesn't work if the square brackets are kept.

However, the OpenResty APIs (tcpsock:connect, balancer.set_current_peer, etc.) require the square brackets in the IPv6 address even though they are used without the port part. Admittedly, it would be better to fix in the OpenResty APIs side, but these APIs are created and widely adopted long time ago...

Therefore, to make the IPv6 upstream work, we need to keep the square brackets too. My proposal is modifying `core.utils.parse_addr` not to remove the brackets, and changing `core.utils.parse_ipv6` to accept the brackets.

What about your opinion?

**Comment by membphis** [comment]
> My proposal is modifying `core.utils.parse_addr` not to remove the brackets, and changing `core.utils.parse_ipv6` to accept the brackets.

This is very good.
