### ISSUE TITLE
request help: Add document about how to compile the Openresty.

### ISSUE THREAD

**Issue by Miss-you** [apache/incubator-apisix#830]
### Issue description
There is no doc in "install-dependencies.md" about how to compile the Openresty

### Environment

* apisix version (cmd: `apisix version`): 0.8 or higher
* OS: tlinux1.2/tlinux2.2

**Comment by membphis** [comment]
http://openresty.org/en/linux-packages.html

We recommend using the official package.

**Comment by Miss-you** [comment]
https://github.com/apache/incubator-apisix/pull/831

**Comment by Miss-you** [comment]
Tencent engineers use a customized version that does not belong to any of the above releases.
