### ISSUE TITLE
bug: APISIX v0.8 doesn't support the Stand-alone mode, need fix the doc.

### ISSUE THREAD

**Issue by Miss-you** [apache/incubator-apisix#838]
### Issue description

APISIX v0.8 doesn't support the Stand-alone mode, need fix the doc.

init_etcd function does not have the line 'if yaml_conf.apisix.config_center ~= "etcd" then'

![image](https://user-images.githubusercontent.com/3816205/68597531-1af60800-04d8-11ea-923e-78e42b2bd353.png)

### Environment

* apisix version (cmd: `apisix version`):
* OS:

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by membphis** [comment]
This is a bug in version 0.8. If you have to use version 0.8, we can release a new version 0.8.1.

Anyway, I always advise you to use the latest version of APISIX.

**Comment by Miss-you** [comment]
I will use the latest version. Thank you.

**Comment by justinmclean** [comment]
Hi,
> Anyway, I always advise you to use the latest version of APISIX.
> 
The latest version of APISIX is 0.8, please do not point users to unreleased code.

Thanks,
Justin

**Comment by moonming** [comment]
> Hi,
> Anyway, I always advise you to use the latest version of APISIX.
> The latest version of APISIX is 0.8, please do not point users to unreleased code. Thanks, Justin

got it.

**Comment by membphis** [comment]
I got it too, thx @justinmclean
