### ISSUE TITLE
request help:  is apisix.http_content_phase() a helpful enhance?

### ISSUE THREAD

**Issue by Beckjiang** [apache/incubator-apisix#842]
### Issue description
I want to do some extension in the `content phase`. But now APISIX can not settle by developing plugins.

In the content phase, I think `proxy_pass` can be the default process way and I also hope I can configure my custom handler. Such as, I want to do multi requests and combine their responses by some rules.

How do you think about that?

**Comment by membphis** [comment]
> Such as, I want to do multi requests and combine their responses by some rules.

You can do this in the "Access" phase.

**Comment by Beckjiang** [comment]
> > Such as, I want to do multi requests and combine their responses by some rules.
> 
> Add a lower priority plugin, and do this in the "access" phase.

Well, I think I know what you mean. It could be not a necessary enhance.
