### ISSUE TITLE
bug: No need to install dependent libraries 'lua-devel'

### ISSUE THREAD

**Issue by Miss-you** [apache/incubator-apisix#843]
### Issue description

No need to install dependent libraries 'lua-devel'
We now replace lua-rapidjson with jsonschema and we no longer need this dependency.

Related document is doc/install-dependencies.md

### Environment

* apisix version (cmd: `apisix version`):0.9 or higher
* OS:all

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by moonming** [comment]
I think lua-pb is still need `lua-devel`

**Comment by membphis** [comment]
yes, we still need `lua-devel`.

**Comment by Miss-you** [comment]
I understand, thank you.
