### ISSUE TITLE
bug: proxy_rewrite plugin Chinese readme test case error

### ISSUE THREAD

**Issue by totemofwolf** [apache/incubator-apisix#849]
### Issue description

Duplicate "," makes 400 error when enable the proxy_rewrite plugin in readme Chinese version. 

### Environment

* apisix version (cmd: `apisix version`): 0.8.0
* OS: alpine docker

![mmexport1573699803207](https://user-images.githubusercontent.com/1818214/68822676-80aae580-06cc-11ea-86cd-b6c6c3404cc8.jpg)

**Comment by shuaijinchao** [comment]
OK, let me fix it. thx~ @totemofwolf
