### ISSUE TITLE
request help: how to allow APISIX config more Nginx-built-in directives?

### ISSUE THREAD

**Issue by lilien1010** [apache/incubator-apisix#854]
### Issue description

 recently I am transfer some of my old Application from pure nginx into
 APISIX, but I meet a some issue about Directives configuration,
 
for exmaple: in nginx.conf we have a config
 
` underscores_in_headers on `
 
which allow nginx take underscore in head , while some of our old
 application count on that feature.
 
   but after  we transfer it into APISIX in docker, we are not allowed to
 edit nginx.conf mannuly
 

### Environment

* apisix version: master
* OS: Centos

**Comment by moonming** [comment]
I think again and feel that supporting nginx instructions does more harm than good.
This will bring a lot of flexibility, but it will also affect the plug-in running effect of Apache APISIX, which will cause a lot of trouble for debugging.

**Comment by membphis** [comment]
> I think again and feel that supporting nginx directives does more harm than good.
> This will bring a lot of flexibility, but it will also affect the plug-in running effect of Apache APISIX, which will cause a lot of trouble for debugging.

Agree with the above mentioned.
