### ISSUE TITLE
request help: 

### ISSUE THREAD

**Issue by gxthrj** [apache/incubator-apisix#870]
### Issue description
feature: admin api 可以根据upstream名称(desc)查询到upstream信息；现在只能通过upstream key （upstream id）获取

### Environment

* apisix version (cmd: `apisix version`):
apisix dcoker 0.8
* OS: 
docker centos

**Comment by membphis** [comment]
the etcd only supports to fetch data by key.

**Comment by soulsoul** [comment]
maybe he wants to search upstream when the application config a lot of upstream info .
