### ISSUE TITLE
request help: Can the `proxy-rewrite` plugin use the `post` method?

### ISSUE THREAD

**Issue by duzhenxun** [apache/incubator-apisix#875]
### Issue description
第一次使用apisix，现在有一些接口想接入网关平台
比如原来的api接口
请求方式：POST 
正式环境：http://www.a.com
api地址：/user/getUserinfo
必传参数：xxxx    
在网关平台上应如何加呢？？

**Comment by membphis** [comment]
Can you give a complete example of input and output?
For example, what is the input to APISIX? And what happens to the output forwarded to the upstream?

你能给一个相对完整的输入和输出例子么？
比如发到 APISIX 的输入是什么，转发到上游的输出又有什么变化。

**Comment by membphis** [comment]
no response
