### ISSUE TITLE
request help: post方式添加routes后，它的id是createdIndex那个值 吗？

### ISSUE THREAD

**Issue by duzhenxun** [apache/incubator-apisix#876]
### Environment
一、添加routes
1，请求：
POST  /apisix/admin/routes
`{
    "uri": "/index.html",
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "39.97.63.215:80": 1
        }
    }
}`
2，响应
`{
    "node": {
        "value": {
            "uri": "/index.html",
            "upstream": {
                "nodes": {
                    "39.97.63.215:80": 1
                },
                "type": "roundrobin"
            }
        },
        "createdIndex": 220,
        "key": "/apisix/routes/00000000000000000220",
        "modifiedIndex": 220
    },
    "action": "create"
}`

这时route的id是否就是 220呢？？？

二、对route进行修改
1，请求：
PATCH /apisix/admin/routes/220
`{
    "uri": "/index.html",
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "39.97.63.215:81": 1
        }
    }
}`
2，响应：
`{
    "cause": "/apisix/routes/220",
    "index": 221,
    "errorCode": 100,
    "message": "Key not found"
}`

**Comment by membphis** [comment]
> 这时route的id是否就是 220呢？？？
