### ISSUE TITLE
bug: dashboard cannot be access via /apisix/dashboard behind LB

### ISSUE THREAD

**Issue by totemofwolf** [apache/incubator-apisix#882]
### Issue description
Access dashboard without '/' will redirect to the REAL server + port , and access dashboard with '/' works fine.

### Environment

* apisix version (cmd: `apisix version`):
bash-4.4# apisix version
0.9-rc1 (current master)

* OS:
alpine 3.7

### Minimal test code / Steps to reproduce the issue

![11574219812_ pic](https://user-images.githubusercontent.com/1818214/69214650-755f2a80-0ba2-11ea-8c7e-fb43aaa60e63.jpg)

### What's the actual result? (including assertion message & call stack if applicable)
request：

```
➜  src curl -I 'http://nsa.works/apisix/dashboard'
HTTP/1.1 301 Moved Permanently
Date: Wed, 20 Nov 2019 03:04:22 GMT
Content-Type: text/html
Content-Length: 239
Location: http://nsa.works:9080/apisix/dashboard/
Connection: keep-alive
Server: APISIX web server

➜  src curl -I 'http://nsa.works/apisix/dashboard/'
HTTP/1.1 200 OK
Date: Wed, 20 Nov 2019 03:04:50 GMT
Content-Type: text/html
Content-Length: 2975
Last-Modified: Mon, 18 Nov 2019 15:17:00 GMT
Connection: keep-alive
ETag: "5dd2b5ec-b9f"
Server: APISIX web server
Accept-Ranges: bytes

```

**Comment by totemofwolf** [comment]
➜  src curl -I 'http://nsa.works/apisix/dashboard'
会301跳转到：
Location: http://nsa.works:9080/apisix/dashboard/

而nsa.works是负载均衡器的IP（只开发80端口监听）

**Comment by moonming** [comment]
@totemofwolf Please use English in the public channel, thx

**Comment by chnliyong** [comment]
@totemofwolf The OpenResty current configuration like this
```nginx
        location = /apisix/dashboard {
            content_by_lua_block {
                ngx.exec("/apisix/dashboard/")
            }
        }

        location /apisix/dashboard {
            index index.html;

            alias dashboard/;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Real-PORT $remote_port;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            try_files $uri $uri/ /index.html;
        }
```
I thought we can simplify it like this
```nginx
        location /apisix/dashboard {
            alias dashboard/;
            try_files $uri $uri/index.html /index.html;
        }
```

**Comment by membphis** [comment]
Love the new code if it works fine. PR welcome
