### ISSUE TITLE
bug: after installation according to the document, adding upstream directly causes the worker to exit

### ISSUE THREAD

**Issue by binlaniua** [apache/incubator-apisix#883]
### Issue description
按照文档安装后, 添加upstream直接导致worker退出
![image](https://user-images.githubusercontent.com/5960462/69220072-1f44b400-0baf-11ea-92af-aeb4a03af27a.png)
![image](https://user-images.githubusercontent.com/5960462/69220120-397e9200-0baf-11ea-8787-a69f2e8ab3b4.png)

### Environment

* apisix version (cmd: `apisix version`): 0.8
* OS: CentOS Linux release 7.2.1511 (Core)

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

### What's the actual result? (including assertion message & call stack if applicable)
出错, 倒是work退出, /tmp/apisix-core下一堆core文件

### What's the expected result?
正常添加upstream

**Comment by moonming** [comment]
@binlaniua please try the master branch,  this may be a bug that has been fixed. thx

**Comment by membphis** [comment]
fixed already
