### ISSUE TITLE
bug: static files failed to load behind apisix http proxy

### ISSUE THREAD

**Issue by totemofwolf** [apache/incubator-apisix#888]
### Environment

* apisix version (cmd: `apisix version`): 0.9-rc1
* OS: alpine 3.7

### Minimal test code / Steps to reproduce the issue

apisix listens on 9080;
80 port is haproxy/nginx for internet traffic in;
3000 port is gitea service.

upstream:
![屏幕快照 2019-11-21 下午3 40 41](https://user-images.githubusercontent.com/1818214/69317170-51b8e480-0c75-11ea-882f-e78d30116364.png)

routes:
![屏幕快照 2019-11-21 下午3 40 50](https://user-images.githubusercontent.com/1818214/69317190-5b424c80-0c75-11ea-9387-6a3bc11fc2e0.png)

### What's the actual result? (including assertion message & call stack if applicable)

![屏幕快照 2019-11-21 下午3 40 14](https://user-images.githubusercontent.com/1818214/69317277-8e84db80-0c75-11ea-914f-7e46074e30e1.png)

![屏幕快照 2019-11-21 下午3 38 53](https://user-images.githubusercontent.com/1818214/69317084-2635fa00-0c75-11ea-9359-6d032c6f8fed.png)

**Comment by chnliyong** [comment]
What's your haproxy/nginx working layer, L4 or L7，if it works on L7，do you set the `Host` header to `Host :gitea.nsa.work`

**Comment by chnliyong** [comment]
Your route's config is *wrong*, path prefix match should use `/*` rather then `/`.

**Comment by totemofwolf** [comment]
> Your route's config is **wrong**, path prefix match should use `/*` rather than `/`.

It works.
