### ISSUE TITLE
Support virtual service and real service traffic statistics?

### ISSUE THREAD

**Issue by ygm521** [apache/incubator-apisix#889]
how did  I count the in traffic and out traffic of a virtual service? And to count the in traffic and out traffic of each real server?

**Comment by moonming** [comment]
how about add metrics in prometheus plugin?

**Comment by ygm521** [comment]
what is prometheus?

**Comment by moonming** [comment]
> what is prometheus?

https://github.com/apache/incubator-apisix/blob/master/doc/plugins/prometheus.md
