### ISSUE TITLE
bug: Error 500 occured when set upstream type to chash

### ISSUE THREAD

**Issue by totemofwolf** [apache/incubator-apisix#892]
### Environment

* apisix version (cmd: `apisix version`): 0.9-rc1 (current master)
* OS: alpine 3.7

### Minimal test code / Steps to reproduce the issue

![屏幕快照 2019-11-22 下午2 13 29](https://user-images.githubusercontent.com/1818214/69402510-fc430d00-0d32-11ea-9bef-bf771602f1ec.png)

### What's the actual result? (including assertion message & call stack if applicable)

![屏幕快照 2019-11-22 下午2 13 48](https://user-images.githubusercontent.com/1818214/69402515-02d18480-0d33-11ea-86ed-9a001b2e4576.png)

```
apisix_1  | 127.0.0.1 - - [22/Nov/2019:14:14:55 +0800] x.nsa.work "PUT /apisix/admin/upstreams/00000000000000000016 HTTP/1.1" 200 546 0.001 "http://x.nsa.work/apisix/dashboard/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" - - -
apisix_1  | 2019/11/22 14:14:58 [error] 42#42: *2160944 failed to run balancer_by_lua*: ...apisix/deps/share/lua/5.1/apisix/lua/apisix/balancer.lua:243: attempt to concatenate local 'err' (a nil value)
apisix_1  | stack traceback:
apisix_1  | 	...apisix/deps/share/lua/5.1/apisix/lua/apisix/balancer.lua:243: in function 'pick_server'
apisix_1  | 	...apisix/deps/share/lua/5.1/apisix/lua/apisix/balancer.lua:266: in function 'load_balancer'
apisix_1  | 	/usr/local/apisix/deps/share/lua/5.1/apisix/lua/apisix.lua:446: in function 'http_balancer_phase'
apisix_1  | 	balancer_by_lua:2: in main chunk while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "gitea.nsa.work"
apisix_1  | 127.0.0.1 - - [22/Nov/2019:14:14:58 +0800] gitea.nsa.work "GET / HTTP/1.1" 500 588 0.000 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36"  - 0.000
```

### What's the expected result?

Non 500 status response.

**Comment by juzhiyuan** [comment]
Hi @tom2nonames , which version of the dashboard are you using? Could you help clone this[1] repo and recompile it?

[1] https://github.com/apache/incubator-apisix-dashboard

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/69421310-b2225180-0d5b-11ea-88f8-ed5637845b05.png)

I just tried and it works, maybe you could clone the latest codes from `apisix-dashboard` repo.

**Comment by totemofwolf** [comment]
> ![image](https://user-images.githubusercontent.com/2106987/69421310-b2225180-0d5b-11ea-88f8-ed5637845b05.png)
> 
> I just tried and it works, maybe you could clone the latest codes from `apisix-dashboard` repo.

Use current master?

**Comment by juzhiyuan** [comment]
Yep
