### ISSUE TITLE
bug: mqtt proxy plugin can not work

### ISSUE THREAD

**Issue by zhijianfree** [apache/incubator-apisix#899]
### Issue description
from document, i run this command to open mqtt proxy :
`
curl http://127.0.0.1:9080/apisix/admin/stream_routes/1 -X PUT -d '
{
    "plugins": {
        "mqtt-proxy": {
            "protocol_name": "MQTT",
            "protocol_level": 4,
            "upstream": {
                "ip": "127.0.0.1",
                "port": 1883
            }
        }
    }
}'
`
and then i got answer:
`
  {"node":{"value":{"plugins":{"mqtt-proxy":{"protocol_level":4,"upstream":{"ip":"127.0.0.1","port":1883},"protocol_name":"MQTT"}}},"createdIndex":3299,"key":"\/apisix\/stream_routes\/1","modifiedIndex":3299},"action":"set"}
`
from the response , i think mqtt proxy is opening.
But when i used the client connect server by apisix , i got error exception.

pls see picture:

![image](https://user-images.githubusercontent.com/21210211/69523688-7bd51400-0f9f-11ea-89e1-7a5120ede550.png)

And i check the apisix log, see picture:
![image](https://user-images.githubusercontent.com/21210211/69526633-990ce100-0fa5-11ea-96ff-8aac17d37fd1.png)

### Environment

* apisix version (cmd: `apisix version`):
* OS: centos 7

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by zhijianfree** [comment]
if i connect server directly(client connect server (x.x.x.x:1883) ,not use apisix), client  connect successful.

pls see picture:
![image](https://user-images.githubusercontent.com/21210211/69523988-19304800-0fa0-11ea-9e49-f1c5620f7445.png)

**Comment by membphis** [comment]
@zhijianfree 

What is your "config.yaml"? Please confirm you send the data to right port.

And please provide an original MQTT request data, you can get it by tool `tcpdump`.

**Comment by zhijianfree** [comment]
you means when i want to proxy mqtt, i need open socket port? 

this is my config.yml:

**Comment by membphis** [comment]
@zhijianfree You need to enable `stream_proxy` and listen on a TCP port, I'll add more doc later. 

https://github.com/apache/incubator-apisix/blob/master/doc/plugins/mqtt-proxy.md

Here is an example:

```yaml
...
    ssl: 'radixtree_sni'          # radixtree_sni: match route by SNI(base on radixtree)
  stream_proxy:                 # TCP/UDP proxy
    tcp:                        # TCP proxy port list
      - 9100
...
```

**Comment by zhijianfree** [comment]
> @zhijianfree You need to enable `stream_proxy` and listen on a TCP port, I'll add more doc later.
> 
> https://github.com/apache/incubator-apisix/blob/master/doc/plugins/mqtt-proxy.md
> 
> Here is an example:
> 
> ```yaml
> ...
>     ssl: 'radixtree_sni'          # radixtree_sni: match route by SNI(base on radixtree)
>   stream_proxy:                 # TCP/UDP proxy
>     tcp:                        # TCP proxy port list
>       - 9100
> ...
> ```

ok, get it .  and it will be better to offer an example config.

**Comment by moonming** [comment]
we should throw error msg when use mqtt plugin without enable `stream_proxy`.

**Comment by membphis** [comment]
the nginx will response HTTP 400, it is an invalid HTTP request.

**Comment by moonming** [comment]
> the nginx will response HTTP 400, it is an invalid HTTP request.

I mean throw error meg when call admin API.

**Comment by zhijianfree** [comment]
after enable mqtt proxy, i connected the 9100 port. but i got error :

![image](https://user-images.githubusercontent.com/21210211/69956487-194dbc00-153b-11ea-98a5-e3b425f5f592.png)

i have enable debug model, but i got nothing from error.log. 
![image](https://user-images.githubusercontent.com/21210211/69956660-882b1500-153b-11ea-89e1-165fc1520d31.png)

**Comment by membphis** [comment]
@zhijianfree Can you provide raw data? which can be obtained through the tool "tcpdump".

**Comment by zhijianfree** [comment]
i dump the mqtt comman "CONNECT" 's data:

picture:
![image](https://user-images.githubusercontent.com/21210211/70034891-e3691000-15ec-11ea-8ac2-9938456be78e.png)

**the text data is here :**
> [root@VM_138_238_centos logs]# tcpdump -q -XX -vvv -nn port 9100
tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
16:47:10.085342 IP (tos 0x0, ttl 116, id 14223, offset 0, flags [DF], proto TCP (6), length 52)
    116.25.44.136.2052 > 10.104.138.238.9100: tcp 0
	0x0000:  5254 00c3 6836 feee ffff ffff 0800 4500  RT..h6........E.
	0x0010:  0034 378f 4000 7406 993d 7419 2c88 0a68  .47.@.t..=t.,..h
	0x0020:  8aee 0804 238c 7dc9 afa8 0000 0000 8002  ....#.}.........
	0x0030:  faf0 e561 0000 0204 0578 0103 0308 0101  ...a.....x......
	0x0040:  0402                                     ..
16:47:10.085363 IP (tos 0x0, ttl 64, id 11792, offset 0, flags [DF], proto TCP (6), length 40)
    10.104.138.238.9100 > 116.25.44.136.2052: tcp 0
	0x0000:  feee ffff ffff 5254 00c3 6836 0800 4500  ......RT..h6..E.
	0x0010:  0028 2e10 4000 4006 d6c8 0a68 8aee 7419  .(..@.@....h..t.
	0x0020:  2c88 238c 0804 0000 0000 7dc9 afa9 5014  ,.#.......}...P.
	0x0030:  0000 20d6 0000                           ......
16:47:10.594298 IP (tos 0x0, ttl 116, id 14225, offset 0, flags [DF], proto TCP (6), length 52)
    116.25.44.136.2053 > 10.104.138.238.9100: tcp 0
	0x0000:  5254 00c3 6836 feee ffff ffff 0800 4500  RT..h6........E.
	0x0010:  0034 3791 4000 7406 993b 7419 2c88 0a68  .47.@.t..;t.,..h
	0x0020:  8aee 0805 238c 7dc9 afa8 0000 0000 8002  ....#.}.........
	0x0030:  faf0 e560 0000 0204 0578 0103 0308 0101  ...`.....x......
	0x0040:  0402                                     ..
16:47:10.594327 IP (tos 0x0, ttl 64, id 12097, offset 0, flags [DF], proto TCP (6), length 40)
    10.104.138.238.9100 > 116.25.44.136.2053: tcp 0
	0x0000:  feee ffff ffff 5254 00c3 6836 0800 4500  ......RT..h6..E.
	0x0010:  0028 2f41 4000 4006 d597 0a68 8aee 7419  .(/A@.@....h..t.
	0x0020:  2c88 238c 0805 0000 0000 7dc9 afa9 5014  ,.#.......}...P.
	0x0030:  0000 20d5 0000                           ......
16:47:11.102743 IP (tos 0x0, ttl 116, id 14227, offset 0, flags [DF], proto TCP (6), length 52)
    116.25.44.136.2054 > 10.104.138.238.9100: tcp 0
	0x0000:  5254 00c3 6836 feee ffff ffff 0800 4500  RT..h6........E.
	0x0010:  0034 3793 4000 7406 9939 7419 2c88 0a68  .47.@.t..9t.,..h
	0x0020:  8aee 0806 238c 7dc9 afa8 0000 0000 8002  ....#.}.........
	0x0030:  faf0 e55f 0000 0204 0578 0103 0308 0101  ..._.....x......
	0x0040:  0402                                     ..
16:47:11.102767 IP (tos 0x0, ttl 64, id 12233, offset 0, flags [DF], proto TCP (6), length 40)
    10.104.138.238.9100 > 116.25.44.136.2054: tcp 0
	0x0000:  feee ffff ffff 5254 00c3 6836 0800 4500  ......RT..h6..E.
	0x0010:  0028 2fc9 4000 4006 d50f 0a68 8aee 7419  .(/.@.@....h..t.
	0x0020:  2c88 238c 0806 0000 0000 7dc9 afa9 5014  ,.#.......}...P.
	0x0030:  0000 20d4 0000                           ......

so, pls check.

**Comment by membphis** [comment]
I checked your TCP data, and compared with MQTT 5.0 or MQTT 3.1.*, your request data is invalid.

Here is the MQTT document: http://mqtt.org/documentation

If you sure you are using a valid MQTT request, you can email me: membphis@gmail.com . Let us find out why.
