### ISSUE TITLE
bug: Too many redirects when setting `http to https` by redirect plugin

### ISSUE THREAD

**Issue by totemofwolf** [apache/incubator-apisix#900]
### Environment

* apisix version (cmd: `apisix version`): 0.9-rc1
* OS: alpine 3.7

### Minimal test code / Steps to reproduce the issue
1. set redirect plugin (302 https://gitea.nsa.work) to host : gitea.nsa.work

![屏幕快照 2019-11-25 下午4 56 34](https://user-images.githubusercontent.com/1818214/69526179-96f65280-0fa4-11ea-9984-f5529f01da5b.png)

2. upload SSL certs.
![屏幕快照 2019-11-25 下午4 58 42](https://user-images.githubusercontent.com/1818214/69526321-e50b5600-0fa4-11ea-9e36-200a7837e6ce.png)

3. request http://gitea.nsa.work

### What's the actual result? (including assertion message & call stack if applicable)

![屏幕快照 2019-11-25 下午4 43 01](https://user-images.githubusercontent.com/1818214/69526002-44b53180-0fa4-11ea-8116-1918ed6b9495.png)

### What's the expected result?
Normal https page.

**Comment by moonming** [comment]
@totemofwolf can you reproduce this bug by admin API?

**Comment by agile6v** [comment]
I have found the root cause of this problem, which the use of plugin is not determined by conditions. For the above example, request **http://gitea.nsa.work** and **https://gitea.nsa.work** are the same, the plugin `redirect` will be enabled. So I think the plugins should support the condition filtering or Do you have any other ideas?

@moonming @membphis

**Comment by agile6v** [comment]
> I have found the root cause of this problem, which the use of plugin is not determined by conditions. For the above example, request **http://gitea.nsa.work** and **https://gitea.nsa.work** are the same, the plugin `redirect` will be enabled. So I think the plugins should support the condition filtering or Do you have any other ideas?
> 
> @moonming @membphis

Sorry for my limited understanding. Condition filtering has been already supported in route, but does not support in the UI.

For the above example, two routes should be configured. One for HTTP and another for HTTPS.  

Create route via `/apisix/admin/routes` Like below:

For HTTP route:
```json
{
    "uris":[
        "/hello"
    ],
    "hosts":[
        "abc.com"
    ],
    ...
    ...
    "vars": [
      ["scheme", "==", "http"]
    ],
    "plugins":{
        "redirect":{
            "uri":"https://abc.com:9443\${uri}",
            "ret_code":302
        }
    }
}
```

For HTTPS route:
```json
{
    "uris":[
        "/hello"
    ],
    "hosts":[
        "abc.com"
    ],
    ...
    "plugins":{
    },
    "vars":[
        ["scheme", "==","https"]
    ]
}
```
It seems that APISIX capabilities has been prefected, but the UI cannot keep up with its progress.
@totemofwolf

**Comment by totemofwolf** [comment]
> > I have found the root cause of this problem, which the use of plugin is not determined by conditions. For the above example, request **http://gitea.nsa.work** and **https://gitea.nsa.work** are the same, the plugin `redirect` will be enabled. So I think the plugins should support the condition filtering or Do you have any other ideas?
> > @moonming @membphis
> 
> Sorry for my limited understanding. Condition filtering has been already supported in route, but does not support in the UI.
> 
> For the above example, two routes should be configured. One for HTTP and another for HTTPS.
> 
> Create route via `/apisix/admin/routes` Like below:
> 
> For HTTP route:
> 
> ```json
> {
>     "uris":[
>         "/hello"
>     ],
>     "hosts":[
>         "abc.com"
>     ],
>     ...
>     ...
>     "vars": [
>       ["scheme", "==", "http"]
>     ],
>     "plugins":{
>         "redirect":{
>             "uri":"https://abc.com:9443\${uri}",
>             "ret_code":302
>         }
>     }
> }
> ```
> 
> For HTTPS route:
> 
> ```json
> {
>     "uris":[
>         "/hello"
>     ],
>     "hosts":[
>         "abc.com"
>     ],
>     ...
>     "plugins":{
>     },
>     "vars":[
>         ["scheme", "==","https"]
>     ]
> }
> ```
> 
> It seems that APISIX capabilities has been prefected, but the UI cannot keep up with its progress.
> @totemofwolf

it works. 👍🏻
# Https route also need `upstream_id`

Below is the success test case:
@moonming @membphis 

```
# for http
# curl -i 127.0.0.1:9180/apisix/admin/routes -X POST -d '{"uris":["/*"],"hosts":["gitea.nsa.work"],"vars":[["scheme", "==", "http"]],"upstream_id":"00000000000000000043","plugins":{"redirect":{"ret_code":302,"uri":"https://gitea.nsa.work"}},"desc":"gitea.nsa.work"}'
HTTP/1.1 201 Created
Date: Wed, 27 Nov 2019 06:50:12 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
Server: APISIX web server

{"node":{"value":{"plugins":{"redirect":{"uri":"https:\/\/gitea.nsa.work","ret_code":302}},"uris":["\/*"],"hosts":["gitea.nsa.work"],"vars":[["scheme","==","http"]],"desc":"gitea.nsa.work","upstream_id":"00000000000000000043"},"createdIndex":76,"key":"\/apisix\/routes\/00000000000000000076","modifiedIndex":76},"action":"create"}

# for https
# curl -i 127.0.0.1:9180/apisix/admin/routes -X POST -d '
{
    "uris":[
        "/*"
    ],
    "hosts":[
        "gitea.nsa.work"
    ],
    "plugins":{
    },
    "vars":[
        ["scheme", "==","https"]
    ],
    "upstream_id":"00000000000000000043"
}'

HTTP/1.1 201 Created
Date: Wed, 27 Nov 2019 07:03:08 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
Server: APISIX web server

{"node":{"value":{"plugins":{},"uris":["\/*"],"hosts":["gitea.nsa.work"],"vars":[["scheme","==","https"]],"upstream_id":"00000000000000000043"},"createdIndex":77,"key":"\/apisix\/routes\/00000000000000000077","modifiedIndex":77},"action":"create"}


# test
➜  ~ curl -I http://gitea.nsa.work
HTTP/1.1 302 Moved Temporarily
Date: Wed, 27 Nov 2019 07:03:50 GMT
Content-Type: text/html
Content-Length: 215
Connection: keep-alive
Location: https://gitea.nsa.work
Set-Cookie: SERVERID=69e48c1ea229c07f80a7f37ab0f0d76f|1574838230|1574838230;Path=/

➜  ~ curl -I https://gitea.nsa.work
HTTP/2 200
content-type: text/html; charset=UTF-8
date: Wed, 27 Nov 2019 07:03:55 GMT
server: APISIX web server
x-request-id: 001ae571f90aaa7c0024d40a602b2b3f
x-protected-by: OpenRASP
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: sameorigin
x-xss-protection: 1; mode=block

```
