### ISSUE TITLE
bug: plugin key-auth not work as expected

### ISSUE THREAD

**Issue by shaobo322** [apache/incubator-apisix#910]
### Environment

* apisix version (cmd: `apisix version`): 0.8
* OS:darwin/amd64

### Minimal test code / Steps to reproduce the issue
1. add a router to upstream service(works as expected)
2. add key-auth plugin for above router
3. do not add apikey header field 
4. response message is **{"message":"Missing API key found in request"}** as expected
5. add apikey in header
6. request again exception occurs

### What's the actual result? (including assertion message & call stack if applicable)
response message **500 internal server error**
call stack like this
```
coroutine 0:
        /Users/beixi/workspace/code/apisix/lua/apisix/consumer.lua: in function 'create_obj_fun'
        ...beixi/workspace/code/apisix/lua/apisix/core/lrucache.lua:50: in function 'global'
        /Users/beixi/workspace/code/apisix/lua/apisix/consumer.lua:47: in function 'plugin'
        ...xi/workspace/code/apisix/lua/apisix/plugins/key-auth.lua:53: in function 'phase_fun'
        /Users/beixi/workspace/code/apisix/lua/apisix.lua:115: in function 'run_plugin'
        /Users/beixi/workspace/code/apisix/lua/apisix.lua:312: in function 'http_access_phase'
        access_by_lua(nginx.conf:143):2: in main chunk, client: 127.0.0.1, server: , request: "POST /smartcloud/v1.1.5/devicemanager/deviceinfo/list HTTP/1.1", host: "127.0.0.1:9081"

```

**Comment by chnliyong** [comment]
Can you supply more detailed infomation please? 
1. Please give the apisix version(use command line `apisix version` can print the version)
2. More call stack log

When I try to reproduce this error, in step 6, I got this
```
HTTP/1.1 401 Unauthorized
Date: Wed, 27 Nov 2019 13:46:54 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
Server: APISIX web server

{"message":"Missing related consumer"}
```
My apisix version is: `0.9-rc1`

**Comment by shaobo322** [comment]
yes where I try to restart the apisix I got the same result like you
my apisix version is: 0.8

**Comment by shaobo322** [comment]
> Can you supply more detailed infomation please?
> 
> 1. Please give the apisix version(use command line `apisix version` can print the version)
> 2. More call stack log
> 
> When I try to reproduce this error, in step 6, I got this
> 
> ```
> HTTP/1.1 401 Unauthorized
> Date: Wed, 27 Nov 2019 13:46:54 GMT
> Content-Type: text/plain
> Transfer-Encoding: chunked
> Connection: keep-alive
> Server: APISIX web server
> 
> {"message":"Missing related consumer"}
> ```
> 
> My apisix version is: `0.9-rc1`

**Comment by membphis** [comment]
> my apisix version is: 0.8

please update your apisix to latest version, it should be 0.9 now.
