### ISSUE TITLE
Make apisix's production deployment **FHS**able

### ISSUE THREAD

**Issue by chnliyong** [apache/incubator-apisix#914]
Currently, `apisix_home`(`/usr/local/apisix`) is the `prefix` path of `OpenResty`，the configuration, temp data, log are all in this directory.
In `Unix-like` environment, [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) is intuitive.
1. Split conf of `apisix` and `openresty`, new directory `/etc/apisix/` for `apisix`'s conf, new directory `/etc/apisix/nginx/` for `OpenResty`.
2. New directory `/var/lib/apisix` as `openresty`'s `prefix`, add `nginx_config.http.temp_directory` config item in `config.yaml`, the default vaule can be `tmp`, and make nginx's `*_temp_path` under this directory.
3. New directory `/var/log/apisix` as `access_log` and `error_log`.
4. As OpenResty's worker process default is ran as `nobody` system user, we don't need create a user.
5. Add `nginx_config.pidfile` config item in `config.yaml`,  the default vaule can `run/apisix.pid`

Production:
```
Configuartion location:
================
/etc/apisix/config.yaml ...
/etc/apisix/nginx/nginx.conf ...

Need config in /etc/apisix/config.yaml:
===========
nginx_config.error_log: /var/log/apisix/error.log
nginx_config.http.access_log: /var/log/apisix/access.log
nginx_config.http.temp_directory: /var/lib/apisix/tmp
nginx_config.pidfile: /var/run/apisix.pid
===========

OpenResty start command line:
=======
openresty -p /var/lib/apisix -c /etc/apisix/nginx/nginx.conf 
```

Development:
Almost keep the same, only add config item for production.

**Comment by membphis** [comment]
```
openresty -p /var/lib/apisix -c /etc/apisix/nginx/nginx.conf 
```

Putting all files under `/usr/local/apisix` is easier to manage.
If you need to map to a different directory, you can use a file soft link.

**Comment by moonming** [comment]
In short, Apache APISIX tries not to let users know the exists of Nginx.

**Comment by moonming** [comment]
@chnliyong Is this FHS way is good for docker?

**Comment by chnliyong** [comment]
> @chnliyong Is this FHS way is good for docker?

Actually, the docker way does not care this.

As `apisix` run within `OpenResty`, it's hard to pass variable by command line arguments, the most common way is using the nginx `prefix` as a base directory. So the `convention` of apisix is not `FHS`, it's `Nginx`
