### ISSUE TITLE
add configure for the development mode in config.yaml

### ISSUE THREAD

**Issue by moonming** [apache/incubator-apisix#918]
Now the way to enable development mode is using `make`, and the number of processes will be modified to 1.

It will be better to let the user configure the development mode in YAML like https://github.com/apache/incubator-apisix/blob/master/conf/config.yaml#L21

**Comment by sshniro** [comment]
Hi @moonming , I was trying to use apisix for a project and I would also love to contribute. I'm new to this eco-system, I hope I understood the context correctly?

The number of processes refers to the `worker_processes` in the nginx.conf

- Define `enable_dev` mode in the [config YAML file](https://github.com/apache/incubator-apisix/blob/master/conf/config.yaml#L21)
- Modify the [apisix bin file](https://github.com/apache/incubator-apisix/blob/4517e7b57eb074b2e39dc2834486e32ba47d7e45/bin/apisix#L515) and if dev enabled set the `worker_processes` value to 0; else set value to auto. 

Is this correct? TIA.

**Comment by moonming** [comment]
@sshniro Thank you for your attention and welcome contributions.
Yes, You are completely right, Looking forward to your PR :)
