### ISSUE TITLE
support `PATCH` for admin APIs

### ISSUE THREAD

**Issue by moonming** [apache/incubator-apisix#92]
- [x] routes: https://github.com/iresty/apisix/pull/365

- [x] service: https://github.com/iresty/apisix/pull/370

- [x] upstream: https://github.com/iresty/apisix/pull/371

- [ ] consumers: waiting to do

- [ ] ssl: waiting to do

**Comment by soulsoul** [comment]
hello, why we need patch method?  for

**Comment by moonming** [comment]
We can only modify one parameter of the configuration, not the entire configuration.

**Comment by membphis** [comment]
support already
