### ISSUE TITLE
bug: `make deps` will clone apisix repo

### ISSUE THREAD

**Issue by moonming** [apache/incubator-apisix#929]
### Issue description
`make deps` will clone `apisix` repo:
```
✗ make deps
luarocks install rockspec/apisix-master-0.rockspec --tree=deps --only-deps --local
Using rockspec/apisix-master-0.rockspec... switching to 'build' mode
Cloning into 'incubator-apisix'...
^C
Error: Failed cloning git repository.
```

### Environment

* apisix version (cmd: `apisix version`): 0.9
* OS: ubuntu 18.04

### Minimal test code / Steps to reproduce the issue
1. make deps

### What's the expected result?
should ONLY install deps, not including apisix repo.

**Comment by membphis** [comment]
Your `luarocks` is too old. It should be a bug of old `luarocks`.
