### ISSUE TITLE
request help: Doc on Getting Started guide for APISIX

### ISSUE THREAD

**Issue by sshniro** [apache/incubator-apisix#930]
### Issue description
Is there step by step guide on getting started guide to onboard new users to APISIX?
1. Link to set up APISIX
2. Register a service/configure route
3. Basic Auth to service
4. Configure a rate limit plugin
5. additional Plugins etc

**Comment by moonming** [comment]
I hope [this doc](https://github.com/apache/incubator-apisix/blob/master/doc/README.md) will give you some help. 
Apache APISIX does not have the full getting started guide now, so PR is welcomed too.

**Comment by sshniro** [comment]
@moonming I've started on the doc, but I'm having problems with the setup, maybe I'm doing it in the wrong way. I'm trying to expose a simple get endpoint from [httpbin](https://httpbin.org) via APISIX. 

GET endpoint: [https://httpbin.org/get](https://httpbin.org/get)

The following are my configurations (Currently trying to access the base site).

```bash
curl http://127.0.0.1:9080/apisix/admin/services/201 -X PUT -d '
{
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "https://httpbin.org:443": 1
        }
    }
}'
```
Then I define a route to access the service.
```bash
curl http://127.0.0.1:9080/apisix/admin/routes/100 -X PUT -d '
{
    "methods": ["GET"],
    "uri": "/foo",
    "service_id": "201"
}'
```
Following is the command I'm using to access my API.
```bash
curl -i http://127.0.0.1:9080/foo
```
But this ends up in 501 bad gateway error. Omitting the `https` section from the node configuration also yields the same error.

**Comment by membphis** [comment]
```
curl http://127.0.0.1:9080/apisix/admin/services/201 -X PUT -d '
{
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "https://httpbin.org:443": 1
        }
    }
}'
```

https://github.com/apache/incubator-apisix/blob/master/doc/architecture-design.md#upstream

The address of node is wrong.

**Comment by sshniro** [comment]
Thank you for the reply, according to the doc I removed the protocol (https) and only added the address and port. But still, APISIX is giving me a 502 gateway error.
![image](https://user-images.githubusercontent.com/13045528/70379919-d8d3b100-1933-11ea-82fb-3237a726c18c.png)

```
curl http://127.0.0.1:9080/apisix/admin/routes/777 -X PUT -i -d '
{
    "uri": "/",
    "host": "httpbin.org",
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "httpbin.org:443": 1
        }
    }
}'
```

`curl -i http://127.0.0.1:9080/ -H "Host: httpbin.org" -X GET`

Should I specify the protocol somewhere else?

**Comment by sshniro** [comment]
Thanks for the update @membphis , I used the proxy-rewrite plugin to change the scheme as the default it http, and removed the protocol `https` from the adress node.

**Comment by sshniro** [comment]
Closing the issue as the PR got merged.
