### ISSUE TITLE
request help: Authentications 想与OAUTH2集成，有文档介绍？

### ISSUE THREAD

**Issue by jiezaizone** [apache/incubator-apisix#932]
### Issue description
APISIX Authentications 自带有key-auth, JWT插件，若想与oauth2集成使用，可以怎么操作，是否有文档介绍？

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by moonming** [comment]
the same as https://github.com/apache/incubator-apisix/issues/927.

Apache APISIX not support oauth2 directly, and you can use [openid-connect](https://github.com/apache/incubator-apisix/blob/master/lua/apisix/plugins/openid-connect.lua) plugin to connect oauth2 server.

Welcome PR for oauth2 doc.

**Comment by jiezaizone** [comment]
> the same as #927.
> 
> Apache APISIX not support oauth2 directly, and you can use [openid-connect](https://github.com/apache/incubator-apisix/blob/master/lua/apisix/plugins/openid-connect.lua) plugin to connect oauth2 server.
> 
> Welcome PR for oauth2 doc.

thanks
