### ISSUE TITLE
bug: the APISIX icon is not show in the dashboard

### ISSUE THREAD

**Issue by lilien1010** [apache/incubator-apisix#939]
### Issue description
![image](https://user-images.githubusercontent.com/3814966/70304617-4f41b780-183d-11ea-97af-7cc4a2694a2f.png)

### Environment

* apisix version (cmd: `apisix version`): master
* OS: Centos
 

### What's the actual result? (including assertion message & call stack if applicable)
the APISIX icon is not show in the dashboard while visit the dashboard 
with URL `HOST/apisix/dashboard` rather than  Trailing Slash  appened

### What's the expected result?
 show the APISIX icon, when user request apisix/dashboard , it should redirect user to apisix/dashboard/

**Comment by juzhiyuan** [comment]
Please sync your codes with `incubator-apisix-dashboard`'s master branch
