### ISSUE TITLE
request help: 插件扩展可行性咨询

### ISSUE THREAD

**Issue by simplechen** [apache/incubator-apisix#944]
HI：
　　我们公司现有有一个正在使用的网关标准如下，现在想看看是否可以通过写apisix plugin　实现。

- 接口标准

1. 接口调用统一地址
> http://127.0.0.1:8080/default

2. 调用方法
> POST

3. 请求参数 http request body
```
/*　头部信息　用于服务定位及身份认证　*/
{
  "head": {
    "service_code": "000100010001",
    "token": "88c91dd128484c8e8addc53a12f5411c"
  },
/*　body 为变参　根据服务不同参数不同，是一个json结构　*/
  "body": {
　　'uid':1
    }
}
```

-  想法
　上述head.service_code为12位编码，前4位对应于一个应用服务（可部署在份)，这和apisix是的route是相悖的，我现在想法是否有可能apisix只写一个route，通过plugin解析里面的json参数拿到服务所在的upstream进而进行分发。

多谢了

**Comment by moonming** [comment]
Sure, Apache APISIX supports custom router, which can resolve your issue.
@membphis can you give a more detail example?

**Comment by moonming** [comment]
by the way, the plugin is not a good idea for your issue.

**Comment by simplechen** [comment]
没错，我这个方案确实不是太好，有一些性能损失，当然我也可以对外时把接口地址变成
http://127.0.0.1:8080/<service_code_prefix> 　service_code_prefix和后面的upstream是对应的，在中间做一个plugnin 重新组合request body json数据　和我们现在的结构无缝对接。

**Comment by moonming** [comment]
> 没错，我这个方案确实不是太好，有一些性能损失，当然我也可以对外时把接口地址变成
> http://127.0.0.1:8080/<service_code_prefix> 　service_code_prefix和后面的upstream是对应的，在中间做一个plugnin 重新组合request body json数据　和我们现在的结构无缝对接。

yes, that will be easier as long as the number of services is not large.
