### ISSUE TITLE
It could not add more than one upstreams to a route

### ISSUE THREAD

**Issue by DHB-liuhong** [apache/incubator-apisix#946]
### Issue description
i want add more than one upstreams to a route ，but I find it doesn't work

### Environment
[root@lhdev2 routes]# curl -i -X PUT http://10.139.6.35:9080/apisix/admin/routes/00000001 -d '
> {
>     "uri": "/*",
>     "methods": ["PUT", "GET", "POST", "DELETE"],
>     "upstream_id": ["00000001", "00000002"]
> }'
HTTP/1.1 400 Bad Request
Date: Fri, 06 Dec 2019 09:52:22 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
Server: APISIX web server
{"error_msg":"invalid configuration: property \"upstream_id\" validation failed: object matches none of the alternatives"}

**Comment by DHB-liuhong** [comment]
我发现用http请求不能灵活的修改upstream中的ip和权重，每次修改，发送请求，都需要将nodes中的所有ip重新写一边，其实我只想修改nodes中某一个ip的权重

**Comment by moonming** [comment]
@DHB-liuhong Apache APISIX does not support yet.  
I think you can refer to https://github.com/apache/incubator-apisix/pull/371 if you want to do this.

**Comment by DHB-liuhong** [comment]
@moonming if i have
