### ISSUE TITLE
How to add a prefix to a route

### ISSUE THREAD

**Issue by sshniro** [apache/incubator-apisix#948]
### Issue description
Hi, I'm new to APISIX and having trouble configuring a route to proxy a remote endpoint

I want to proxy a request via APISIX to example.com (via the route: `test/example`). Thus when I execute this route it will return the homepage(text/HTML) as a response.

The following is my route definition.
```
curl http://127.0.0.1:9080/apisix/admin/routes/777 -X PUT -i -d '
{
    "uri": "/test/example",
    "host": "localhost",
    "methods": ["GET"],
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "example.com:80": 1
        }
    }
}'
```
This gives a successful response. Then I try to access this route via the following command.

`curl -i http://127.0.0.1:9080/test/example -H "Host: localhost" -i -v`

The following returns a 404 HTML page. But when I try to curl command straight to example.com it provides the home page. I'm following the instructions in the [architecture document](https://github.com/apache/incubator-apisix/blob/master/doc/architecture-design.md#route)

Can someone help me out on what I'm missing here? Thanks in advance.

![image](https://user-images.githubusercontent.com/13045528/70377735-4540b700-1918-11ea-9496-5fd7cf86191a.png)

**Comment by sshniro** [comment]
Found the problem, the host header should be similar to the domain.

```
curl http://127.0.0.1:9080/apisix/admin/routes/777 -X PUT -i -d '
{
    "uri": "/",
    "host": "example.com",
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "example.com:80": 1
        }
    }
}'

`curl -i http://127.0.0.1:9080/ -H "Host: example.com" -i -v -X GET`
```

**Comment by sshniro** [comment]
How can I provide a path like `test/example` to access the example.com?

Like: `curl -i http://127.0.0.1:9080/test/example -X GET` should return the example.com

Because I have multiple domains that need different paths. 
For example: 
Domain1: foo.com
Domain 2: bar.com

`http://127.0.0.1:9080/service/foo` should point to foo.com
`http://127.0.0.1:9080/service/bar` should point to bar.com

Is this kind of workflow supported in APISIX? An example snippet would be helpful, I could not find any relevant docs for this.

@membphis @moonming

**Comment by moonming** [comment]
Do you want to use one routing rule to handle multiple domain names? 
As far as I know, Apache APISIX is still not supported. Apache APISIX prefers to deal with flat structures.

**Comment by sshniro** [comment]
I want something like this, Here is the same URL.
- https://httpbin.org/get

Here the host is `https://httpbin.org` and the URI is `get`. So when I configure a route in APISIX it will look like this.

```bash
curl "http://127.0.0.1:9080/apisix/admin/routes/1" -X PUT -d '
{
    "uri": "/get",
    "host": "httpbin.org",
..... // Other confgis
```
Therefore, I can access this route via the following URL.
`curl -i -X GET "http://127.0.0.1:9080/get" -H "Host: httpbin.org"`

What I want to do is put a prefix path before the URI, so I can call the service like this.

`curl -i -X GET "http://127.0.0.1:9080/pathprefix1/pathprefix2/get" -H "Host: httpbin.org"`

I guess this is still not supported yet, because I could not find a relevant doc for this.

**Comment by sshniro** [comment]
I've learned that prefix can be achieved via uri_regex in the plugin rewrite. I will update the getting started guide with the information.
