### ISSUE TITLE
request help: How to replace uri?

### ISSUE THREAD

**Issue by dabingya** [apache/incubator-apisix#949]
route configures:
urls: /abc
upstream: abc   

upstream configures:
abc: 127.0.0.1:17777

want:
curl 127.0.0.1:9080/abc/hello -> 127.0.0.1:17777/hello?

**Comment by membphis** [comment]
please take a look at this doc: https://github.com/apache/incubator-apisix/blob/master/doc/plugins/proxy-rewrite-cn.md#%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0

**Comment by dabingya** [comment]
这样只能影响一个url，有设置一次 可以匹配所有的吗？
就如 nginx :
location /abc {
    proxy_pass 127.0.0.1:17777/ ;
}

**Comment by membphis** [comment]
You can implement a new option in the proxy-rewrite plugin, such as: "uri": "$matched_uri".

**Comment by dabingya** [comment]
could you give more detail ?

**Comment by moonming** [comment]
you can add `sub_uri` option in the schema of `proxy_rewite` plugin: https://github.com/apache/incubator-apisix/blob/master/lua/apisix/plugins/proxy-rewrite.lua#L25

Then you can add replace code in this plugin, and the API like this:
```
"proxy-rewrite": {
            "sub_uri": ["\/abc\/(.*)", "/$1"],
            "scheme": "http",
            "host": "iresty.com",
        }
```

**Comment by agile6v** [comment]
@moonming I agree with your suggestion. Is it better to change sub_uri to regex_uri? If possible, I will submit a PR later.

**Comment by moonming** [comment]
sure, welcome PR ：） thx
