### ISSUE TITLE
bug: Attempt to index field 'plugins' Error, when configuring route and referencing services with DNS.

### ISSUE THREAD

**Issue by sshniro** [apache/incubator-apisix#954]
### Issue description
I'm trying to create a service and reference it in a route. The following are my configurations:

```bash
curl "http://127.0.0.1:9080/apisix/admin/services/200" -X PUT -d '
{
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "httpbin.org:443": 1
        }
    }
}'
```

```bash
curl "http://127.0.0.1:9080/apisix/admin/routes/1" -X PUT -d '
{
    "uri": "/get",
    "host": "httpbin.org",
    "plugins": {
                "proxy-rewrite": {
                        "scheme": "https"
                    
                }
            },
    "service_id": "200"
}'
```
```bash
curl -i -X GET "http://127.0.0.1:9080/get" -H "Host: httpbin.org"
```

### What's the actual result? (including assertion message & call stack if applicable)
When I call the endpoint it gives a 500 Internal server error.
![image](https://user-images.githubusercontent.com/13045528/70428102-3708ad00-1a76-11ea-9af9-2ee544391527.png)

The following are the error logs.
```
2019/12/09 10:08:31 [error] 29#29: *80103 lua entry thread aborted: runtime error: ...l/apisix/deps/share/lua/5.1/apisix/lua/apisix/plugin.lua:306: attempt to index field 'plugins' (a nil value)
stack traceback:
coroutine 0:
        ...l/apisix/deps/share/lua/5.1/apisix/lua/apisix/plugin.lua: in function 'create_obj_fun'
        ...x/deps/share/lua/5.1/apisix/lua/apisix/core/lrucache.lua:64: in function 'merge_service_route'
        /usr/local/apisix/deps/share/lua/5.1/apisix/lua/apisix.lua:287: in function 'http_access_phase'
        access_by_lua(nginx.conf:139):2: in main chunk, client: 127.0.0.1, server: , request: "GET /get?foo1=bar1&foo2=bar2 HTTP/1.1", host: "httpbin.org"

```

### What's the expected result?
It should return the actual results. 

The contradicting behavior is, if I configure everything in a route then I can access the endpoint without any problems.

```bash
curl http://127.0.0.1:9080/apisix/admin/routes/1 -X PUT -d '
{
    "uri": "/get",
    "plugins": {
        "proxy-rewrite": { "scheme": "https" }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "httpbin.org:443": 1
        }
    }
}'
```

![image](https://user-images.githubusercontent.com/13045528/70427852-c5306380-1a75-11ea-85b3-995ad21dab22.png)

Is this an expected behavior? Or am I doing something wrong here?

**Comment by sshniro** [comment]
It seems providing a DNS name to the service provokes this error. I tried the similar with [http://example.com](http://example.com) . When I include the exact IP of the service, it works, but when I include the domain name it fails.

**Comment by membphis** [comment]
It should be a bug, we need to fix it
