### ISSUE TITLE
bug: custom etcd host is invalid.

### ISSUE THREAD

**Issue by shuaijinchao** [apache/incubator-apisix#963]
[lua/apisix/core/etcd.lua](https://github.com/apache/incubator-apisix/blob/master/lua/apisix/core/etcd.lua#L35) When calling `lua-resty-etcd` for initialization, the configuration file passed in is the structure defined in [conf/config.yaml](https://github.com/apache/incubator-apisix/blob/master/conf/config.yaml#L71), but the etcd structure defined in config is connected to the address key Is `host`, and the key accepted in [lua-resty-etcd](https://github.com/iresty/lua-resty-etcd/blob/master/lib/resty/etcd/v2.lua#L49) is `http_host`, so the current configuration is invalid.

When initializing etcd, you can change the configuration structure from `etcd_conf.host` to` etcd_conf.http_host` to make it take effect.

**Comment by moonming** [comment]
welcome PR

**Comment by agile6v** [comment]
Hi @shuaijinchao 

APISIX currently depends on `lua-resty-etcd(0.7)`, which is valid in `lua-resty-etcd(0.7)`. If APISIX upgrades `lua-resty-etcd` to the latest version, it's necessary to update this option at the same time.

**Comment by shuaijinchao** [comment]
> Hi @shuaijinchao
> 
> APISIX currently depends on `lua-resty-etcd(0.7)`, which is valid in `lua-resty-etcd(0.7)`. If APISIX upgrades `lua-resty-etcd` to the latest version, it's necessary to update this option at the same time.

Yes, I found this problem too. Currently APISIX refers to version 0.7 so there is no this problem.
