### ISSUE TITLE
HTTP logger to send logs to external log management tool

### ISSUE THREAD

**Issue by sshniro** [apache/incubator-apisix#965]
Does  APISIX provide an HTTP logger to send gateway request (url, uri, time, key) logs to an external endpoint? I want to send the access logs to [Kibana/Logstash](https://www.elastic.co/what-is/elk-stack) for further analysis.

**Comment by moonming** [comment]
APISIX does not have such plugins now, but we definitely need them to send logs to ELK, Datadog, Kafka, etc.
And welcome PR.

**Comment by moonming** [comment]
I think this job can start now. @sshniro are you interested?

**Comment by sshniro** [comment]
Yes @moonming , We are evaluating APISIX as a potential microservice gateway for a [Europian Union](https://www.efactory-project.eu/) project. Also, the HTTP logger is an essential component of the project to track the service consumption. 

I would love to contribute to this feature. Unfortunately, I'm not available the next week. I already started working on it (will need some guidance). I planning to send a PR in the following weeks.

**Comment by moonming** [comment]
Great, I'm looking forward to it. @sshniro

**Comment by sshniro** [comment]
Hi, @moonming  I've started to work on this, would appreciate some guidance, as all the external loggers (ELK, syslog) need to send the same log data I'm creating a common function to get all the information. The following is the function.

```lua
function get_full_log(){
    local ctx = ngx.ctx.api_ctx
    local var = ngx.var
    
    local request_uri = var.request_uri or ""
    local url = var.scheme .. "://" .. var.host .. ":" .. var.server_port .. request_uri
    
    local service_name
    if ctx.matched_route and ctx.matched_route.value then
        service_name = ctx.matched_route.value.desc or
                ctx.matched_route.value.id
    else
        service_name = var.host
    end

    local full_log =  {
        request = {
            url = url,
            uri = request_uri,
            method = ngx.req.get_method(),
            headers = ngx.req.get_headers(),
            querystring = ngx.req.get_uri_args(), 
            size = var.request_length
        },
        response = {
            status = ngx.status,
            headers = ngx.resp.get_headers(),
            size = var.bytes_sent
        },
        upstream = var.upstream_addr,
        service = service_name,
        consumer = ctx.consumer,
        client_ip = core.request.get_remote_client_ip(ngx.ctx.api_ctx),
        start_time = req.start_time() * 1000,
        latency = (ngx.now() - ngx.req.start_time()) * 1000
    }
}
```

Questions.
1. Does it make sense to put this method in `core->log` file as it consolidates all logs or should this be a file inside the plugin directory
2. Is the log attribute complete or should I add anything else (request body etc) ?
3. `ngx.ctx.api_ctx.var` and `ngx.var` both contain the same variables, but `ngx.var` only contains strings. Is there a preference for what to be used or both are the same?

**Comment by moonming** [comment]
@membphis please have a look, you are more familiar with the logic of log than I am, thx

**Comment by moonming** [comment]
1. I think put this method inside the plugin is ok
2. the log attributes are enough. the request body may be large, it can be omitted by default
3. better use `ngx.ctx.api_ctx.var`, which has a better performance then `ngx.var`

by the way, it's better to have the log buffer and send logs in batches.

**Comment by sshniro** [comment]
The coroutine bug has been resolved for the batch processor, I will send a PR during the weekend for the HTTP logger.
