### ISSUE TITLE
request help:  coding

### ISSUE THREAD

**Issue by dabingya** [apache/incubator-apisix#966]
### Environment

* apisix version (cmd: `apisix version`):
* OS: max os

i want to do some study and coding, after git clone , how can i run the project  ?

**Comment by moonming** [comment]
https://github.com/apache/incubator-apisix/blob/master/doc/getting-started.md is a good start, then you can try plugins: https://github.com/apache/incubator-apisix/tree/master/doc#plugins

**Comment by dabingya** [comment]
i do git clone ,then make deps ,add conf/nginx.conf ,make run ,finally it work.

**Comment by moonming** [comment]
Enjoy:)
