### ISSUE TITLE
request help:  开启health健康检查，不能自动剔除有问题的节点

### ISSUE THREAD

**Issue by asher86v** [apache/incubator-apisix#975]
### Issue description
开启health健康检查，不能自动剔除有问题的节点

### Environment
* apisix version (cmd: `apisix version`): 0.9-rc1
* OS:  CentOS Linux release 7.4.1708 (Core)

curl -i -X PUT http://10.110.2.120:9080/apisix/admin/routes/1112 -d '
{
"uri": "/*",
"hosts": ["www.dd.com"],
"methods": ["PUT", "GET", "POST", "DELETE"],
"upstream": {
"type": "roundrobin",
"nodes": {
"10.110.2.95:5000": 1,
"10.110.2.95:5001": 1
},
"checks": {
"passive": {
"healthy": {
"http_statuses": [200, 201, 204, 301],
"successes": 1
},
"unhealthy": {
"http_statuses": [500, 504,502, 403],
"http_failures": 1,
"tcp_failures": 1
}
}
}
}
}'

这时候关掉其中一个节点得服务，会出现502错误。

➜  ~ curl www.dd.com:9080
5000%                                                                                                                                                                                           ➜  ~ curl www.dd.com:9080
5001%                                                                                                                                                                                           ➜  ~ curl www.dd.com:9080
5000%                                                                                                                                                                                           ➜  ~ curl www.dd.com:9080
5001%                                                                                                                                                                                           ➜  ~ curl www.dd.com:9080
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>openresty</center>
</body>
</html>

**Comment by chnliyong** [comment]
You just only use `passive` method, which it's your code's responsibility to call the `report_*` function provided by `lua-resty-healthcheck`.

More detail docs: https://kong.github.io/lua-resty-healthcheck/modules/resty.healthcheck.html

**Comment by agile6v** [comment]
@asher86v 配置`retries`可以解决你的问题。

个人觉得重试应该是一个默认操作，使用的人理解起来也会容易一些。
@moonming @membphis 


```lua
    local checker = fetch_healthchecker(up_conf, healthcheck_parent, version)
    local retries = up_conf.retries
    if retries and retries > 0 then
        ctx.balancer_try_count = (ctx.balancer_try_count or 0) + 1
        if checker and ctx.balancer_try_count > 1 then
            local state, code = get_last_failure()
            if state == "failed" then
                if code == 504 then
                    checker:report_timeout(ctx.balancer_ip, ctx.balancer_port,
                                           up_conf.checks.host)
                else
                    checker:report_tcp_failure(ctx.balancer_ip,
                        ctx.balancer_port, up_conf.checks.host)
                end

            else
                checker:report_http_status(ctx.balancer_ip, ctx.balancer_port,
                                           up_conf.checks.host, code)
            end
        end

        if ctx.balancer_try_count == 1 then
            set_more_tries(retries)
        end
    end
```

**Comment by moonming** [comment]
> @asher86v 配置`retries`可以解决你的问题。
> 
> 个人觉得重试应该是一个默认操作，使用的人理解起来也会容易一些。
> @moonming @membphis
> 
> ```lua
>     local checker = fetch_healthchecker(up_conf, healthcheck_parent, version)
>     local retries = up_conf.retries
>     if retries and retries > 0 then
>         ctx.balancer_try_count = (ctx.balancer_try_count or 0) + 1
>         if checker and ctx.balancer_try_count > 1 then
>             local state, code = get_last_failure()
>             if state == "failed" then
>                 if code == 504 then
>                     checker:report_timeout(ctx.balancer_ip, ctx.balancer_port,
>                                            up_conf.checks.host)
>                 else
>                     checker:report_tcp_failure(ctx.balancer_ip,
>                         ctx.balancer_port, up_conf.checks.host)
>                 end
> 
>             else
>                 checker:report_http_status(ctx.balancer_ip, ctx.balancer_port,
>                                            up_conf.checks.host, code)
>             end
>         end
> 
>         if ctx.balancer_try_count == 1 then
>             set_more_tries(retries)
>         end
>     end
> ```

welcome PR. and I think the origin issue resolved.
