### ISSUE TITLE
request help: 关于负载均衡健康检查配置问题

### ISSUE THREAD

**Issue by jiezaizone** [apache/incubator-apisix#977]
### Issue description
安装健康检查文档进行如下配置确实可以实现过滤掉宕机的节点，配置相当于直接给路由添加一个新的upstream。
**问题1**:健康检查能否与upstreams中已经配置了的upstream直接关联？通过admin 操作添加upstreams 是关联了upstream_id: "00000000000000000016"
**问题2**：当upstreams 设置 ```"type":"chash",    "key":"remote_addr",```后，健康检查就无效了。两个节点，宕机掉其中一个后就直接502，不会切换到存活的节点上。
**问题3**：现在的 负载均衡 是手动将所有的node的节点添加进去的，能否实现扩容时候自动将节点添加进负载均衡节点列表？可以怎么实现。
```shell
curl http://192.168.4.122/apisix/admin/routes/00000000000000000015 -X PUT -d '
{
    "uris": [
        "/*"
    ],
    "hosts": [
        "local-web.com"
    ],
    "plugins": {
        
    },
    "upstream": {
         "nodes": {
            "192.168.4.122:8081": 1,
            "192.168.4.122:8082": 1
        },
        "type": "roundrobin",
        "retries": 2,
        "checks": {
            "active": {
                "http_path": "/status",
                "host": "local-web.com",
                "healthy": {
                    "interval": 2,
                    "successes": 1
                },
                "unhealthy": {
                    "interval": 1,
                    "http_failures": 2
                },
                "req_headers": ["User-Agent: curl/7.29.0"]
            },
            "passive": {
                "healthy": {
                    "http_statuses": [200, 201],
                    "successes": 3
                },
                "unhealthy": {
                    "http_statuses": [500],
                    "http_failures": 3,
                    "tcp_failures": 3
                }
            }
        }
    }
}'
```

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by agile6v** [comment]
问题2：我这里并没有复现，主动健康检查的间隔是2秒，很可能会碰到一次502的情况。

**Comment by agile6v** [comment]
Hi @jiezaizone 

我简单测试了retries参数和主动&被动健康检查配置遇到502的情况：

#### 未配置retries参数
##### 1.1  仅配置主动健康检查
  结论：upstream中指定了多个node时，当其中一个node不可访问并不会将请求转发至其他node，所以有可能碰到502情况（健康检查并没有发现node状态是不健康的）

##### 1.2 仅配置被动健康检查
结论：upstream中指定了多个node时，当其中一个node不可访问并不会将请求转发至其他node，一定会碰到502情况（因为没有配置retries所以这里的被动健康检查并没有生效等同于1.4）

##### 1.3 同时配置主动健康检查和被动健康检查
结论：upstream中指定了多个node时，当其中一个node不可访问并不会将请求转发至其他node，所以有可能碰到502情况（同1.1）

##### 1.4 未配置任何健康检查
结论：upstream中指定了多个node时，当其中一个node不可访问并不会将请求转发至其他node，一定会碰到502情况

#### 2. 配置了retries参数
##### 2.1 仅配置主动健康检查
结论：upstream中指定了多个node时，当其中一个node不可访问会将请求转发至健康的node上，可以认为不会502情况，与retries配置次数有关（遇到502的情况：假设尝试次数是1，当配置刚生效第一次访问碰到不健康node，再次尝试如果再碰到不健康node此时会返回502，因为在此时并没有健康node）

##### 2.2 仅配置被动健康检查
结论：upstream中指定了多个node时，当其中一个node不可访问会将请求转发至健康的node上，可以认为不会502情况，与retries配置次数有关（遇到502的情况：假设尝试次数是1，当配置刚生效第一次访问碰到不健康node，再次尝试如果再碰到不健康node此时会返回502，因为在此时并没有健康node）

##### 2.3 同时配置主动健康检查和被动健康检查
结论：同2.1和2.2

##### 2.4 未配置任何健康检查
结论：upstream中指定了多个node时，会根据retries参数指定值执行重试操作，所以有可能碰到502情况

**NOTE**： 主动健康检查会周期检查node健康状态，如果node状态从不健康变为健康会再次被加入到转发列表中；而被动健康检查（2.2）并不会将从不健康状态变为健康状态的node加入到转发列表。

@moonming reries参数建议还是配置一个合理的默认值，我先想想如何配置reries参数

**Comment by moonming** [comment]
@agile6v nice work👍
@membphis please have a look too

**Comment by jiezaizone** [comment]
> Hi @jiezaizone
> 
> 我简单测试了retries参数和主动&被动健康检查配置遇到502的情况：
> 
> #### 1. 未配置retries参数
> ##### 1.1 仅配置主动健康检查
> 结论：upstream中指定了多个node时，当其中一个node不可访问并不会将请求转发至其他node，所以有可能碰到502情况（健康检查并没有发现node状态是不健康的）
> 
> ##### 1.2 仅配置被动健康检查
> 结论：upstream中指定了多个node时，当其中一个node不可访问并不会将请求转发至其他node，一定会碰到502情况（因为没有配置retries所以这里的被动健康检查并没有生效等同于1.4）
> 
> ##### 1.3 同时配置主动健康检查和被动健康检查
> 结论：upstream中指定了多个node时，当其中一个node不可访问并不会将请求转发至其他node，所以有可能碰到502情况（同1.1）
> 
> ##### 1.4 未配置任何健康检查
> 结论：upstream中指定了多个node时，当其中一个node不可访问并不会将请求转发至其他node，一定会碰到502情况
> 
> #### 2. 配置了retries参数
> ##### 2.1 仅配置主动健康检查
> 结论：upstream中指定了多个node时，当其中一个node不可访问会将请求转发至健康的node上，可以认为不会502情况，与retries配置次数有关（遇到502的情况：假设尝试次数是1，当配置刚生效第一次访问碰到不健康node，再次尝试如果再碰到不健康node此时会返回502，因为在此时并没有健康node）
> 
> ##### 2.2 仅配置被动健康检查
> 结论：upstream中指定了多个node时，当其中一个node不可访问会将请求转发至健康的node上，可以认为不会502情况，与retries配置次数有关（遇到502的情况：假设尝试次数是1，当配置刚生效第一次访问碰到不健康node，再次尝试如果再碰到不健康node此时会返回502，因为在此时并没有健康node）
> 
> ##### 2.3 同时配置主动健康检查和被动健康检查
> 结论：同2.1和2.2
> 
> ##### 2.4 未配置任何健康检查
> 结论：upstream中指定了多个node时，会根据retries参数指定值执行重试操作，所以有可能碰到502情况
> 
> **NOTE**： 主动健康检查会周期检查node健康状态，如果node状态从不健康变为健康会再次被加入到转发列表中；而被动健康检查（2.2）并不会将从不健康状态变为健康状态的node加入到转发列表。
> 
> @moonming reries参数建议还是配置一个合理的默认值，我先想想如何配置reries参数

👍

**Comment by membphis** [comment]
> 而被动健康检查（2.2）并不会将从不健康状态变为健康状态的node加入到转发列表。
This should be a bug, we cannot just enable passive health checks.

**Comment by agile6v** [comment]
> > 而被动健康检查（2.2）并不会将从不健康状态变为健康状态的node加入到转发列表。
> 
> This should be a bug, we cannot just enable passive health checks.
> 
> > reries参数建议还是配置一个合理的默认值
> 
> How about the number `3`?

Nginx calculates the number of retries based on the number of configured `servers` in `upstream block` by default. And if the `proxy_next_upstream_tries` directive is set, it will override the default value.  Could APISIX also follow this logic? @membphis

**Comment by membphis** [comment]
@agile6v I love your way. PR welcome.
