### ISSUE TITLE
request help: apisix 数据是存储在哪儿？怎么直接查看与备份？

### ISSUE THREAD

**Issue by jiezaizone** [apache/incubator-apisix#978]
### Issue description
apisix 数据是存储在哪儿？怎么直接查看与备份？

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by moonming** [comment]
The data of APISIX all stored in etcd, and you can read [the doc of etcd](https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/recovery.md) for details of snapshotting and recovery.
