### ISSUE TITLE
bug: A document description error : incubator-apisix/doc/plugins/ip-restriction-cn.md

### ISSUE THREAD

**Issue by 1996yarbrough** [apache/incubator-apisix#984]
### Issue description
The test case for the 'ip-restriction' plug-in is wrong.
I think you should only change client IP, request segment IP unchanged,
such as 
$ curl http://127.0.0.1:9080/index.html
HTTP/1.1 200 OK
...
$ curl http://127.0.0.2:9080/index.html -i
HTTP/1.1 403 Forbidden
...
{"message":"Your IP address is not allowed"}

### What's the expected result?

1. 
curl http://127.0.0.1:9080/apisix/admin/routes/1 -X PUT -d '
{
    "uri": "/index.html",
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:1980": 1
        }
    },
    "plugins": {
        "ip-restriction": {
            "whitelist": [
                "127.0.0.1",
                "113.74.26.106/24"
            ]
        }
    }
}'
2.
$ curl http://127.0.0.1:9080/index.html
HTTP/1.1 200 OK
...
3.
curl http://127.0.0.1:9080/apisix/admin/routes/1 -X PUT -d '
{
    "uri": "/index.html",
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:1980": 1
        }
    },
    "plugins": {
        "ip-restriction": {
            "whitelist": [
                "127.0.0.2",
                "113.74.26.106/24"
            ]
        }
    }
}'
4.
$ curl http://127.0.0.1:9080/index.html -i
HTTP/1.1 403 Forbidden
...
{"message":"Your IP address is not allowed"}

**Comment by moonming** [comment]
welcome PR
