### ISSUE TITLE
request help: How to get consumer id from upstream service ?

### ISSUE THREAD

**Issue by songpspan** [apache/incubator-apisix#999]
### Issue description
How to get consumer id from upstream service when the request has passed authentication plugin (e.g., jwt-auth, key-auth) ?

### Environment

* apisix version (cmd: `apisix version`): 0.9
* OS: Ubuntu 18.04

**Comment by membphis** [comment]
You can get it from `ctx. consumer_id`.

Here is the source code link:

https://github.com/apache/incubator-apisix/blob/master/lua/apisix/plugins/key-auth.lua#L85
